import re
import os

def translate_file(src_path, dst_path, title_fr, translations):
    with open(src_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', content)
    
    for orig, trans in translations:
        content = content.replace(orig, trans)
    
    credit = '\n[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    elif '</pre></div>' in content:
        content = content.replace('</pre></div>', credit + '</pre></div>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {os.path.basename(src_path)}")

# 08.html - ARM32 ELF Sizecoding
translate_file('/home/ubuntu/tmpout-fr/3/08.html', '/home/ubuntu/tmpout-fr/3/fr/08.html',
    'ARM32 ELF Sizecoding', [
    ("--- 1) Background", "--- 1) Contexte"),
    ("In the demoscene there are various size-coding competitions where", "Dans la demoscene, il existe diverses compétitions de programmation réduite où"),
    ("the goal is to write the most interesting program in a certain size", "le but est d'écrire le programme le plus intéressant dans une certaine taille"),
    ("range (often a power of two, like 256 bytes or 4k).", "de portée (souvent une puissance de deux, comme 256 octets ou 4k)."),
    ("Usually the rules count the executable header against the file size.", "Généralement, les règles comptent l'en-tête exécutable contre la taille du fichier."),
    ("This isn't much of a problem for most 8-bit systems,", "Ce n'est pas vraiment un problème pour la plupart des systèmes 8 bits,"),
    ("and it is definitely not a problem for the most infamous platform (MS-DOS .COM files).", "et il ne l'est certainement pas pour la plateforme la plus célèbre (fichiers .COM MS-DOS)."),
    ("It is, however, an extreme headache for people trying to write tiny Linux demos.", "C'est cependant une douleur de tête extrême pour ceux qui essayent d'écrire de petits demos Linux."),
    ("Often a significant part of the file size ends up being the ELF header.", "Souvent, une partie importante de la taille du fichier se révèle être l'en-tête ELF."),
    ("There has been a lot of work figuring out ways to abuse the ELF header", "Il y a eu beaucoup de travail pour trouver des façons d'abuser de l'en-tête ELF"),
    ("to allow smaller programs, however this work often concentrates on the x86 architecture.", "pour permettre des programmes plus petits, cependant ce travail se concentre souvent sur l'architecture x86."),
    ("We were interested in seeing the limits on a 32-bit ARM system,", "Nous étions intéressés pour voir les limites sur un système ARM 32 bits,"),
    ("specifically a Raspberry Pi running Raspbian Linux.", "spécifiquement un Raspberry Pi fonctionnant sous Raspbian Linux."),
    ("On this architecture with traditional tools a gcc-compiled executable", "Sur cette architecture avec des outils traditionnels, un exécutable compilé avec gcc"),
    ("has 340 bytes of headers tacked to the front.", "a 340 octets d'en-têtes ajoutés à l'avant."),
    ("By using hand-built techniques you can craft a custom statically-linked executable", "En utilisant des techniques faites main, vous pouvez créer un exécutable personnalisé lié statiquement"),
    ("with only 84 bytes of ELF header.", "avec seulement 84 octets d'en-tête ELF."),
    ("This is much better, and may be suitable for a 256 byte demo,", "C'est beaucoup mieux, et peut-être adapté à un demo de 256 octets,"),
    ("but what if we want things smaller?", "mais que faire si on veut plus petit ?"),
    ("Can we create a 128 byte demo?", "Peut-on créer un demo de 128 octets ?"),
    ("--- 2) The Challenge", "--- 2) Le défi"),
    ("An ARM32 executable with an 84 byte header leaves only 44 bytes free.", "Un exécutable ARM32 avec un en-tête de 84 octets ne laisse que 44 octets libres."),
    ("The default ARM32 RISC machine code has 32-bit instructions,", "Le code machine ARM32 RISC par défaut a des instructions de 32 bits,"),
    ("which means any 128 byte program would only have room for eleven instructions.", "ce qui signifie que tout programme de 128 octets n'aurait de place que pour onze instructions."),
    ("This isn't much, especially when you're running Linux and just setting", "Ce n'est pas beaucoup, surtout quand vous exécutez Linux et que la simple configuration"),
    ("up a proper exit() system call takes 3 instructions.", "d'un appel système exit() correct prend 3 instructions."),
    ("Things can be mildly helped by using one of the ARM embedded instruction", "Les choses peuvent être légèrement aidées en utilisant l'une des encodages d'instructions ARM embarquées"),
    ("encodings that provide improved code density.", "qui offrent une densité de code améliorée."),
    ("We use THUMB-2 which allows many common instruction patterns to fit in half the size", "Nous utilisons THUMB-2 qui permet à de nombreux motifs d'instructions courants de tenir dans la moitié de la taille"),
    ("(16-bits).", "(16 bits)."),
    ("You do need a new enough CPU to support this;", "Vous avez besoin d'un CPU assez récent pour supporter ceci ;"),
    ("the original Raspberry Pi Model 1 machines with ARM 1176 processors can't do this,", "les machines Raspberry Pi modèle 1 originales avec des processeurs ARM 1176 ne peuvent pas le faire,"),
    ("but more recent models did add support for THUMB-2.", "mais les modèles plus récents ont ajouté le support de THUMB-2."),
    ("--- 3) The Demo", "--- 3) Le demo"),
    ("This project evolved into a demo called \"Thumbpinski\" which finished", "Ce projet a évolué en un demo appelé \"Thumbpinski\" qui a fini"),
    ("in 9th place in the combined 128 byte demo category at the Lovebyte 2022", "à la 9e place de la catégorie demo combinée de 128 octets au Lovebyte 2022"),
    ("size-coding demoparty.", "size-coding demoparty."),
    ("The demo doesn't have room to do much.", "Le demo n'a pas beaucoup d'espace pour faire des choses."),
    ("It draws a purple \"Sierpinski Triangle\" to the screen.", "Il dessine un \"Triangle de Sierpinski\" violet à l'écran."),
    ("This is a much overdone effect in sizecoding because you can generate it with a single bitwise AND", "Cet effet est beaucoup utilisé en sizecoding parce que vous pouvez le générer avec un seul ET bit à bit"),
    ("of the X and Y co-ordinates.", "des coordonnées X et Y."),
    ("The graphics are actually just text made", "Les graphismes sont en fait du texte fait"),
    ("by generating ANSI escape codes and printing to Linux stdout via", "en générant des codes d'échappement ANSI et en les imprimant sur la sortie standard Linux via"),
    ("syscalls.", "des appels système."),
    ("In addition a call to the nanosleep() syscall ensures", "De plus, un appel au syscall nanosleep() assure"),
    ("a consistent frame rate.", "un taux de rafraîchissement constant."),
    ("--- 4) Summary of the tricks", "--- 4) Résumé des astuces"),
    ("+ Placing code/data in the ELF Header", "+ Placement du code/données dans l'en-tête ELF"),
    ("Our biggest trick is that even though the ELF header is still 84 bytes,", "Notre plus grande astuce est que même si l'en-tête ELF est toujours de 84 octets,"),
    ("we manage to stash some code and data in the header itself at unimportant", "nous réussissons à cacher du code et des données dans l'en-tête lui-même à des"),
    ("or unused offsets.", "offsets inutiles ou inutilisés."),
    ("We change things so execution is launched 8 bytes into the header,", "Nous changeons les choses pour que l'exécution commence 8 octets dans l'en-tête,"),
    ("where 8 bytes of extended ABI/padding lives.", "où vivent 8 octets d'ABI étendu/remplissage."),
    ("We fit in a few instructions", "Nous plaçons quelques instructions"),
    ("here with the last one being a branch to the main executable at the", "ici, la dernière étant une branche vers l'exécutable principal à l'"),
    ("normal location.", "emplacement normal."),
    ("We also store some data in the e_shoff/e_flags area.", "Nous stockons également certaines données dans la zone e_shoff/e_flags."),
    ("Linux doesn't seem to complain as long as the first byte of e_flags is 0,", "Linux ne semble pas se plaindre tant que le premier octet de e_flags est 0,"),
    ("so we crafted our data so that location starts at 0 but we set it to a proper", "nous avons donc fabriqué nos données pour que cet endroit commence à 0 mais nous le"),
    ("value later (it will eventually hold ASCII value '0' or '5' depending on", "définissons à une valeur appropriée plus tard (il finira par contenir la"),
    ("if the current text being drawn is black or purple).", "valeur ASCII '0' ou '5' selon que le texte courant est noir ou violet)."),
    ("+ Overlapping the end of the header with code", "+ Chevauchement de la fin de l'en-tête avec le code"),
    ("Linux seems to ignore the p_align field which is the last 4 bytes", "Linux semble ignorer le champ p_align qui est les 4 derniers octets"),
    ("of the header, so we start the main code block overlapped with", "de l'en-tête, donc nous commençons le bloc de code principal chevauché avec"),
    ("this area.", "cette zone."),
    ("+ Loading at a non-standard location", "+ Chargement à un emplacement non standard"),
    ("To save some space we force the executable to load at address 0x8000 instead of", "Pour gagner de la place, nous forçons l'exécutable à charger à l'adresse 0x8000"),
    ("the more typical 0x10000.", "plutôt que l'adresse plus typique 0x10000."),
    ("By having the address fit in a single 16 bit offset it allows smaller constants", "En ayant l'adresse qui tient dans un seul décalage de 16 bits, cela permet des"),
    ("(and thus smaller instructions) when working on pointers.", "constantes plus petites (et donc des instructions plus petites) lors de la"),
    ("+ Optimizing the Code", "manipulation de pointeurs."),
    ("The rest of the challenge was THUMB2 size optimization at the", "+ Optimisation du code"),
    ("assembly language level and so not really ELF related.", "Le reste du défi était une optimisation de taille THUMB2 au niveau de"),
    ("There's nothing extra clever here,", "l'assembleur et donc pas vraiment lié à ELF."),
    ("just careful use of short constants, making sure", "Il n'y a rien de plus malin ici,"),
    ("we have as many 16-bit instructions as possible,", "juste une utilisation soigneuse de constantes courtes, en s'assurant"),
    ("using a few THUMB-2 specific instructions,", "d'avoir autant d'instructions 16 bits que possible,"),
    ("and not having an exit() syscall as the program is an infinite loop.", "en utilisant quelques instructions spécifiques à THUMB-2,"),
    ("--- 5) Conclusion", "et en n'ayant pas d'appel système exit() car le programme est une boucle infinie."),
    ("With our changes we managed to make an ARM32 Linux demo that fits in", "--- 5) Conclusion"),
    ("exactly 128 bytes.", "Avec nos changements, nous avons réussi à créer un demo Linux ARM32 qui tient"),
    ("The executable runs, but readelf doesn't like it and gdb refuses to work on it.", "exactement dans 128 octets."),
    ("We've tested on many systems and it still runs as of the Linux 6.1.21 kernel", "L'exécutable fonctionne, mais readelf n'aime pas et gdb refuse de travailler dessus."),
    ("that ships with Raspbian in June of 2023.", "Nous l'avons testé sur de nombreux systèmes et il fonctionne toujours avec le"),
    ("Our new challenge is to use this knowledge to make a more exciting demo", "noyau Linux 6.1.21 qui est livré avec Raspbian en juin 2023."),
    ("for next time.", "Notre nouveau défi est d'utiliser cette connaissance pour créer un demo plus"),
    ("----------- the source code ------------", "plus passionnant pour la prochaine fois."),
    ("----------- end code ------------", "----------- le code source ------------"),
])

print("Batch 2a done: 08.html")

# 09.html - Silver Bullet to ELF Projects
translate_file('/home/ubuntu/tmpout-fr/3/09.html', '/home/ubuntu/tmpout-fr/3/fr/09.html',
    "Une balle d'argent pour les projets ELF", [
    ("I've been thinking about fuzzing the projects that take ELF binaries as an input", "J'ai été en train de réfléchir à faire du fuzzing sur les projets qui prennent des binaires ELF en entrée"),
    ("since I read xcellerator's \"Dead Bytes\"[0] blog in tmpout #1.", "depuis que j'ai lu le blog de xcellerator \"Dead Bytes\"[0] dans tmpout #1."),
    ("In his blog, he clearly demonstrates that some ELF and program headers are ignored by", "Dans son blog, il démontre clairement que certains en-têtes ELF et de programme sont ignorés par"),
    ("the loader.", "le chargeur."),
    ("I took the inspiration from these corruptions and targeted the open source projects", "Je me suis inspiré de ces corruptions et ai ciblé des projets open source"),
    ("with just one silver bullet,", "avec une seule balle d'argent,"),
    ("which is the `dead_bytes.bin`.", "qui est le `dead_bytes.bin`."),
    ("I wanted to prove the idea of \"Linux loader is the least picky parsers among the", "Je voulais prouver l'idée que \"le chargeur Linux est le parseur le moins exigeant parmi"),
    ("standart Linux toolkit\".", "les outils Linux standard\"."),
    ("However, surprisingly, even though I haven't written any advanced harnesses (was", "Cependant, étonnamment, même si je n'avais pas écrit de harnesses avancés (j'utilisais"),
    ("just using argv, which means slower execution per sec), this heretic and barely", "juste argv, ce qui signifie une exécution plus lente par seconde), ce binaire hérétique"),
    ("valid \"dead_bytes.bin\" binary alone was able to cause some problems!", "et à peine valide \"dead_bytes.bin\" a pu causé des problèmes !"),
    ("I spent my time mostly with crash triages.", "J'ai passé mon temps principalement en triage de plantements."),
    ("As you can imagine,", "Comme vous pouvez l'imaginer,"),
    ("after a while it started to get really exhausting.", "ça a commencé à devenir vraiment éprouvant."),
    ("(Reaching out developers, checking how the project owner handles things,", "(Contacter les développeurs, vérifier comment le propriétaire du projet gère les choses,"),
    ("accepted naming, CoC's etc etc.)", "les noms acceptés, la CoC etc etc.)"),
    ("It may sound I have worked on thousand projects but no.", "Il peut sembler que j'ai travaillé sur mille projets mais non."),
    ("─ S c o p e ─", "─ S c o p e ─"),
    ("I tested eight projects which are;", "J'ai testé huit projets qui sont ;"),
    ("no crash", "sans plantement"),
    ("crash", "plantement"),
    ("Infinite Loop", "boucle infinie"),
    ("I also included the AFL build options for targeted projects in my repository[2]", "J'ai également inclus les options de construction AFL pour les projets ciblés dans mon dépôt[2]"),
    ("for the people would want to experience for themselves.", "pour les personnes qui voudraient expérimenter par eux-mêmes."),
    ("─ The Adventure Begins ─", "─ L'aventure commence ─"),
    ("Actually, starting a simple fuzzing campaign with AFL++ is really simple.", "En fait, commencer une simple campagne de fuzzing avec AFL++ est vraiment simple."),
    ("It requires two things;", "Il faut deux choses ;"),
    ("Building and instrumenting the project with AFL++ toolchain", "Construire et instrumenter le projet avec la chaîne d'outils AFL++"),
    ("Finding a function or a example binary that is capable", "Trouver une fonction ou un binaire exemple qui est capable"),
    ("of consuming and handling the mutated input.", "de consommer et de gérer l'entrée mutée."),
    ('You may ask, "What is Instrumentation?".', "Vous pouvez demander, « Qu'est-ce que c'est que l'instrumentation ? »."),
    ("Let's simply clarify that!", "Clarifions simplement cela !"),
    ("Instrumentation can be explained as tailoring code blocks to increase the amount", "L'instrumentation peut être expliquée comme un ajustement de blocs de code pour"),
    ("of code that is tested by the fuzzer.", "augmenter la quantité de code testé par le fuzzer."),
    ("The injected code allows fuzzers to get coverage information and which track code", "Le code injecté permet aux fuzzers d'obtenir des informations de couverture et de"),
    ("paths were executed.", "suivre les chemins de code exécutés."),
    ("Instrumentation also helps to find more complex bugs,", "L'instrumentation aide également à trouver des bugs plus complexes,"),
    ("which is a problem if you do \"brute-force fuzzing\",", "ce qui est un problème si vous faites du \"fuzzing force-brute\","),
    ("(mutating bytes randomly (also known as \"dumb\" mode)).", "(en mutant des octets aléatoirement (également connu sous le nom de \"mode dumb\"))."),
    ("Do not be fooled by the term \"dumb\" mode.", "Ne vous laissez pas tromper par le terme \"mode dumb\"."),
    ("With just 30 lines of python code,", "Avec seulement 30 lignes de code Python,"),
    ("so1den had found a null point deref vulnerability in radare2[3].", "so1den avait trouvé une vulnérabilité de déréférence de pointeur nul dans radare2[3]."),
    ("The difference here is,", "La différence ici est,"),
    ("the guidance and those feedback markers through instrumentation.", "la guidance et ces marqueurs de rétroaction grâce à l'instrumentation."),
    ("Last thing you need to know is, instrumentation is done at compilation time", "La dernière chose à savoir, c'est que l'instrumentation est effectuée au moment de la compilation"),
    ("in the examples in this paper.", "dans les exemples de cet article."),
    ("Now you know about instrumentation, you can see why the project must be built", "Maintenant que vous savez ce qu'est l'instrumentation, vous pouvez voir pourquoi le projet"),
    ("with AFL++.", "doit être construit avec AFL++."),
    ("These two things are enough for a primitive fuzzer.", "Ces deux choses suffisent pour un fuzzer primitif."),
    ("At least, it will test some functions of the target while you are developing", "Au moins, il testera certaines fonctions de la cible pendant que vous développez"),
    ("a much more advanced version of it.", "une version beaucoup plus avancée."),
    ("Let's take radare2 for an example and assume that we do", "Prenons radare2 comme exemple et supposons que nous ne"),
    ("not know anything about the code, how it is written,", "sachions absolument rien du code, de la façon dont il est écrit,"),
    ("or how radare2 processes files.", "ou de la façon dont radare2 traite les fichiers."),
    ("The steps are;", "Les étapes sont ;"),
    ("... Then voila! Our campaign started!", "... Puis voilà ! Notre campagne a commencé !"),
    ("Funny thing is,", "Le fou rien, c'est que"),
    ("this was how CVE-2023-1605 is found in just 15 minutes with", "c'est ainsi que CVE-2023-1605 a été trouvé en 15 minutes avec"),
    ("a silver bullet!", "une balle d'argent !"),
    ("After understanding these simple steps, you can do speedrun", "Après avoir compris ces étapes simples, vous pouvez faire un speedrun"),
    ("them in %ANY% categories!", "dans %ANY% catégories !"),
    ("─ Example Finding ─", "─ Exemple de découverte ─"),
    ("The most interesting project to me was elfmaster's safe ELF parsing library.", "Le projet le plus intéressant pour moi était la bibliothèque d'analyse ELF sécurisée d'elfmaster."),
    ('"libelfmaster"[4] has some sanity checks for malicious headers,', '"libelfmaster"[4] a quelques vérifications de sécurité pour les en-têtes malveillants,'),
    ("and gives warnings about them.", "et donne des avertissements à leur sujet."),
    ("The most interesting modes are ELF_LOAD_F_FORENSICS and", "Les modes les plus intéressants sont ELF_LOAD_F_FORENSICS et"),
    ("ELF_LOAD_F_STRICT (I call it as panic mode).", "ELF_LOAD_F_STRICT (je l'appelle mode panic)."),
    ("I used `elfparse.c` example as a starting point and a harness and found crashes", "J'utilisais `elfparse.c` comme point de départ et harness et j'ai trouvé des plantements"),
    ("in both modes.", "dans les deux modes."),
    ("I find these crashes valuable because I assume that the flags", "Je trouve ces plantements precieux parce que j'assume que les drapeaux"),
    ("will be used by somebody doing forensics, and that somebody", "seront utilisés par quelqu'un faisant du développement judiciaire, et que"),
    ("SERIOUSLY does not want to be in trouble.", "quelqu'un SÉRIEUSEMENT ne veut pas être dans la difficulté."),
    ('Gave "dead_bytes.bin" as a silver seed,', "J'ai donné \"dead_bytes.bin\" comme graine argentée,"),
    ("and the fuzzer could successfully mutate it into something can pass", "et le fuzzer a pu avec succès le muter en quelque chose qui peut passer"),
    ("these sanity checks and crash the library.", "ces vérifications de sécurité et faire planter la bibliothèque."),
    ("For example, there is a check for unsafe program header table values", "Par exemple, il y a une vérification pour des valeurs de table d'en-têtes"),
    ("in libelfmaster.c#2920[5]:", "de programme non sécurisées dans libelfmaster.c#2920[5] :"),
    ("It can be explained like this;", "Cela peut être expliqué comme suit ;"),
    ("Check if ELF_PHDRS_F flag is set and ELF File Identifier is not ET_REL", "Vérifie si le drapeau ELF_PHDRS_F est défini et que l'identifiant de"),
    ("(Relocatable File)", "fichier ELF n'est pas ET_REL (Fichier repositionnable)"),
    ("Calculate if e_phoff + ( e_phnum * sizeof(elf64 program header struct) )", "Calcule si e_phoff + ( e_phnum * sizeof(struct elf64 program header) )"),
    ("exceeds object's actual size", "dépasse la taille réelle de l'objet"),
    ("If exceeds go to error.", "Si cela dépasse, aller à l'erreur."),
    ("Also,  at libelfmaster.c#2915[6], if both e_phnum && e_phoff are greater than", "Aussi, dans libelfmaster.c#2915[6], si e_phnum && e_phoff sont supérieurs à"),
    ("zero, ELF_PHDRS_F is set.", "zéro, ELF_PHDRS_F est défini."),
    ("Did you see how this check can be bypassed already?", "Vous voyez déjà comment cette vérification peut être contournée ?"),
    ("The mutated input that", "L'entrée mutée qui"),
    ("caused the crash had the following attributes;", "a provoqué le plantement avait les attributs suivants ;"),
    ("e_phoff = 0", "e_phoff = 0"),
    ("e_phnum was an integer that is greater than zero.", "e_phnum était un entier supérieur à zéro."),
    ("Type was ET_EXEC (Executable File)", "Le type était ET_EXEC (Fichier exécutable)"),
    ("This input will have no ELF_PHDRS_F flag, thus it will not reach that", "Cette entrée n'aura pas de drapeau ELF_PHDRS_F, donc elle n'atteindra pas"),
    ("offset_len > actual_size sanity check on the first line of the code snippet.", "la vérification de sécurité offset_len > taille_actuelle sur la première ligne de l'extrait de code."),
    ("Then, it -potentially- will lead to some unvalid and dangerous memory mappings.", "Ensuite, cela mènera potentiellement à des mappages mémoire non valides et dangereux."),
    ("─ True Dead Bytes Mutator ─", "─ Vrai mutateur de dead bytes ─"),
    ("The findings so far do not actually have much to do with bytes that", "Les découvertes jusqu'ici n'ont pas vraiment grand-chose à voir avec les"),
    ("xcellerator found as dead.", "octets que xcellerator a trouvés comme morts."),
    ("We need a true mutator that is changing only the dead bytes.", "Nous avons besoin d'un vrai mutateur qui ne modifie que les octets morts."),
    ("Thanks to AFL++, it allows it's users to write a custom mutator.", "Grâce à AFL++, il permet aux utilisateurs d'écrire un mutateur personnalisé."),
    ("To accomplish this goal, I examined the examples in AFLplusplus' github repository[7]", "Pour accomplir cet objectif, j'ai examiné les exemples dans le dépôt github AFLplusplus[7]"),
    ("I took example.c file as a starting point.", "J'ai pris le fichier example.c comme point de départ."),
    ("The custom mutator is ready to be used!", "Le mutateur personnalisé est prêt à être utilisé !"),
    ("Use the shared library like this:", "Utilisez la bibliothèque partagée comme suit :"),
    ("Friendly Reminder: Always check if the instrumented binary is in-use.", "Rappel amical : Vérifiez toujours si le binaire instrumenté est en cours d'utilisation."),
    ("(ex. lazy way to do: strings bin | grep __afl)", "(ex. manière paresseuse de le faire : strings bin | grep __afl)"),
    ("Also, you can check the newly created binaries in example/default/.cur_input:", "Aussi, vous pouvez vérifier les nouveaux binaires créés dans example/default/.cur_input :"),
    ("─ Extras ─", "─ Extras ─"),
    ("I was able to minimize the crasher inputs efficiently with afl-collect:", "J'ai pu minimiser efficacement les entrées plantogènes avec afl-collect :"),
    ('With "splitmind" gdb plugin, I was able to analyze the crashes more easily:', "Avec le plugin gdb \"splitmind\", j'ai pu analyser les plantements plus facilement :"),
    ("For python projects, I found this repository to prepare harnesses for python", "Pour les projets Python, j'ai trouvé ce dépôt pour préparer des harnesses pour"),
    ("projects.", "les projets Python."),
    ("However, when instrumentation is applied, the execution per second", "Cependant, lorsque l'instrumentation est appliquée, l'exécution par seconde"),
    ("speed is not practical for personal setups.", "n'est pas pratique pour les configurations personnelles."),
    ("─ Conclusion ─", "─ Conclusion ─"),
    ("So yeah it's pretty much about it!", "Voilà, c'est à peu près tout !"),
    ("You have seen that even small fuzzing", "Vous avez vu que même de petites campagnes de fuzzing,"),
    ("campaigns, with little bit tinkering, can do find bizarre bugs in a short time", "avec un peu d'ajustement, peuvent trouver des bugs bizarres en peu de temps"),
    ("Special \"yo!\" to richinseattle, elfmaster, xcellerator and tmp0ut crew!", "Un grand « yo ! » à richinseattle, elfmaster, xcellerator et l'équipe tmp0ut !"),
    ("Thanks for reading, you absolute legends!", "Merci d'avoir lu, vous êtes des légendes absolues !"),
    ("─ Links & References ─", "─ Liens & Références ─"),
    ("1. Uncrackable Program?", "1. Programme incraquable ?"),
    ("Finding a Parser Differential in loading ELF", "Trouver un différentiel de parseur lors du chargement ELF"),
    ("3. Fuzzing Radare2 For 0days In About 30 Lines Of Code", "3. Fuzzing Radare2 Pour 0days Environ 30 Lignes De Code"),
    ("libelfmaster -", "libelfmaster -"),
    ("libelfmaster.c: Sanity check -", "libelfmaster.c : vérification de sécurité -"),
    ("libelfmaster.c: ELF_PHDRS_F is set -", "libelfmaster.c : ELF_PHDRS_F est défini -"),
    ("Custom Mutators -", "Mutateurs personnalisés -"),
    ("Endless Loop in LIEF::ELF::Binary::eh_frame_functions() -", "Boucle infinie dans LIEF::ELF::Binary::eh_frame_functions() -"),
])

print("Batch 2 done: 08.html and 09.html")
PYEOF