#!/usr/bin/env python3
import re
import os

def translate_file(src_path, dst_path, title_fr, translations):
    with open(src_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', content)
    
    for orig, trans in translations:
        content = content.replace(orig, trans)
    
    credit = '\n[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    elif '</pre></div>' in content:
        content = content.replace('</pre></div>', credit + '</pre></div>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {os.path.basename(src_path)}")

# 03.html - UNIX VIRUSES 25th Anniversary Edition
translate_file('/home/ubuntu/tmpout-fr/3/03.html', '/home/ubuntu/tmpout-fr/3/fr/03.html',
    "VIRUS UNIX 25e ANNIVERSAIRE", [
    ("UNIX VIRUSES 25th Anniversary Edition", "VIRUS UNIX 25e ANNIVERSAIRE"),
    ("Dedicated to Silvio Cesare, the father of UNIX Viruses...", "Dédié à Silvio Cesare, le père des virus UNIX..."),
    ("CONTENTS", "CONTENU"),
    ("IMPROVING THIS MANUAL", "AMÉLIORATION DE CE MANUEL"),
    ("THE UNIX-VIRUS MAILING LIST", "LA LISTE DE DIFFUSION UNIX-VIRUS"),
    ("INTRODUCTION", "INTRODUCTION"),
    ("THE NON ELF INFECTOR FILE VIRUS (FILE INFECTION)", "LE VIRUS DE FICHIER SANS ELF INFECTEUR (INFECTION DE FICHIER)"),
    ("MEMORY LAYOUT OF AN ELF EXECUTABLE", "MISE EN PAGE MÉMOIRE D'UN EXÉCUTABLE ELF"),
    ("ELF INFECTION", "INFECTION ELF"),
    ("THE TEXT SEGMENT PADDING VIRUS (PADDING INFECTION)", "LE VIRUS DE REMPLISSAGE DU SEGMENT TEXTE (INFECTION PAR REMPLISSAGE)"),
    ("INFECTING INFECTIONS", "INFECTION DES INFECTIONS"),
    ("THE DATA SEGMENT VIRUS (DATA INFECTION)", "LE VIRUS DU SEGMENT DE DONNÉES (INFECTION DE DONNÉES)"),
    ("VIRUS DETECTION", "DÉTECTION DE VIRUS"),
    ("THE TEXT SEGMENT VIRUS (TEXT INFECTION)", "LE VIRUS DU SEGMENT TEXTE (INFECTION TEXTE)"),
    ("INFECTION USING OBJECT CODE PARASITES", "INFECTION EN UTILISANT DES PARASITES DE CODE OBJET"),
    ("OBJECT CODE LINKING", "LIAISON DE CODE OBJET"),
    ("THE IMPLEMENTED INFECTOR", "L'INFECTEUR IMPLÉMENTÉ"),
    ("NON (NOT AS) TRIVIAL PARASITE CODE", "CODE DE PARASITE NON (PAS TROP) TRIVIAL"),
    ("BEYOND ELF PARASITES AND ENTER VIRUS IN UNIX", "AU-DELÀ DES PARASITES ELF ET ENTREZ LE VIRUS DANS UNIX"),
    ("THE LINUX PARASITE VIRUS", "LE VIRUS PARASITE LINUX"),
    ("DEVELOPMENT OF THE LINUX VIRUS", "DÉVELOPPEMENT DU VIRUS LINUX"),
    ("IMPROVING THE LINUX VIRUS", "AMÉLIORATION DU VIRUS LINUX"),
    ("EVADING VIRUS DETECTION IN ELF INFECTION", "ÉVITER LA DÉTECTION DE VIRUS DANS L'INFECTION ELF"),
    ("CONCLUSION", "CONCLUSION"),
    ("SOURCE (UUENCODED)", "SOURCE (CODÉE EN UUENCODE)"),
    ("For any comments or suggestions (even just to say hi) please contact the author", "Pour tout commentaire ou suggestion (même juste pour dire bonjour), veuillez contacter l'auteur"),
    ("This paper already has future plans to", "Ce document a déjà des projets futurs pour"),
    ("include more parasite techniques and shared object infection.", "inclure plus de techniques de parasitage et d'infection d'objets partagés."),
    ("More to come.", "À suivre."),
    ("This is the charter for the unix-virus mailing list. Unix-virus was created to", "Ceci est la charte de la liste de diffusion unix-virus. Unix-virus a été créée pour"),
    ("discuss viruses in the unix environment from the point of view of the virus", "discuter des virus dans l'environnement unix du point de vue du"),
    ("creator, and the security developer writing anti-virus software.", "créateur et du développeur de sécurité écrivant des logiciels anti-virus."),
    ("Anything related to viruses in the unix environment is open for discussion.", "Toute chose liée aux virus dans l'environnement unix est ouverte à la discussion."),
    ("The list is archived at http://virus.beergrave.net", "La liste est archivée à http://virus.beergrave.net"),
    ("To subscribe to the list send a message to majordomo@virus.beergrave.net", "Pour s'abonner à la liste, envoyez un message à majordomo@virus.beergrave.net"),
    ("with 'subscribe unix-virus' in the body of the message.", "avec 'subscribe unix-virus' dans le corps du message."),
    ("This paper documents the algorithms and implementation of UNIX parasite and", "Ce document documente les algorithmes et l'implémentation des virus et parasites"),
    ("virus code using ELF objects.", "UNIX utilisant des objets ELF."),
    ("Brief introductions on UNIX virus detection and evading", "Des introductions brèves sur la détection des virus UNIX et l'évasion"),
    ("such detection are given.", "de telles détections."),
    ("An implementation of various ELF parasite", "Une implémentation de divers parasites ELF"),
    ("infectors for UNIX is provided,", "pour UNIX est fournie,"),
    ("and an ELF virus for Linux on x86 architecture is also supplied.", "et un virus ELF pour Linux sur architecture x86 est également fourni."),
    ("Elementary programming and UNIX knowledge is assumed,", "Une connaissance élémentaire de la programmation et de UNIX est supposée,"),
    ("and an understanding of Linux x86 architecture is assumed for the Linux implementation.", "et une compréhension de l'architecture x86 de Linux est supposée pour l'implémentation Linux."),
    ("ELF understanding is not required but will help.", "Une compréhension d'ELF n'est pas requise mais sera utile."),
    ("This paper does not document any significant virus programming techniques", "Ce document ne documente aucune technique de programmation de virus significative"),
    ("except those that are only applicable to the UNIX environment.", "sauf celles qui ne s'appliquent qu'à l'environnement UNIX."),
    ("An interesting, yet simple idea for a virus takes note,", "Une idée intéressante, mais simple pour un virus prend note,"),
    ("that when you append one executable to another,", "que lorsque vous ajoutez un exécutable à un autre,"),
    ("the original executable executes,", "l'exécutable original s'exécute,"),
    ("but the latter executable is still intact and retrievable and even executable if copied to", "mais l'exécutable suivant est toujours intact et récupérable et même exécutable si copié dans un"),
    ("a new file and executed.", "nouveau fichier et exécuté."),
    ("Now.. if the parasite keeps track of its own length,", "Maintenant... si le parasite garde la trace de sa propre longueur,"),
    ("it can copy the original host to a new file,", "il peut copier l'hôte original vers un nouveau fichier,"),
    ("then execute it like normal,", "puis l'exécuter normalement,"),
    ("making a working parasite and virus.", "créant un parasite et un virus fonctionnels."),
    ("The algorithm is as follows:", "L'algorithme est le suivant :"),
    ("execute parasite work code", "exécuter le code de travail du parasite"),
    ("lseek to the end of the parasite", "lseek à la fin du parasite"),
    ("read the remaining portion of the file", "lire la portion restante du fichier"),
    ("write to a new file", "écrire dans un nouveau fichier"),
    ("execute the new file", "exécuter le nouveau fichier"),
    ("The downfall with this approach is that the remaining executable no longer", "Le revers de cette approche est que l'exécutable restant n'est plus"),
    ("remains strip safe.", "sécuritaire pour strip."),
    ("This will be explained further on when a greater", "Ceci sera expliqué plus en détail lorsque nous aurons une"),
    ("understanding of the ELF format is obtained,", "compréhension approfondie du format ELF,"),
    ("but to summarize,", "mais pour résumer,"),
    ("the ELF headers no longer hold into account every portion of the file,", "les en-têtes ELF ne tiennent plus compte de chaque portion du fichier,"),
    ("and strip removes unaccounted portions.", "et strip supprime les portions non comptabilisées."),
    ("This is the premise of virus detection with this type of virus.", "C'est la base de la détection de virus avec ce type de virus."),
    ("This same method can be used to infect LKM's following similar procedures.", "Cette même méthode peut être utilisée pour infecter les LKM suivant des procédures similaires."),
    ("A process image consists of a 'text segment' and a 'data segment'.", "Une image de processus consiste en un 'segment texte' et un 'segment de données'."),
    ("The text segment is given the memory protection r-x", "Le segment texte est donné la protection mémoire r-x"),
    ("The data segment is given the protection rw-.", "Le segment de données est donné la protection rw-."),
    ("Padding completes the segment,", "Le remplissage complète le segment,"),
    ("and in practice looks like this.", "et en pratique ressemble à ceci."),
    ("A complete page", "Une page complète"),
    ("Memory used in this segment", "Mémoire utilisée dans ce segment"),
    ("Padding", "Remplissage"),
    ("pages 1, 2, 3 constitute the text segment", "les pages 1, 2, 3 constituent le segment texte"),
    ("pages 4, 5, 6 constitute the data segment", "les pages 4, 5, 6 constituent le segment de données"),
    ("For completeness,", "Pour la complétude,"),
    ("on x86, the stack segment is located after the data segment", "sur x86, le segment de pile est situé après le segment de données"),
    ("giving the data segment enough room for growth.", "donnant au segment de données assez d'espace pour la croissance."),
    ("In an ELF file, loadable segments are present physically in the file,", "Dans un fichier ELF, les segments chargeables sont présents physiquement dans le fichier,"),
    ("which completely describe the text and data segments for process image loading.", "ce qui décrit complètement les segments texte et de données pour le chargement de l'image du processus."),
    ("Loadable program segments (text/data) are identified in a program header by a", "Les segments de programme chargeables (texte/données) sont identifiés dans un en-tête de programme par un"),
    ("p_type of PT_LOAD (1).", "p_type de PT_LOAD (1)."),
    ("The program header table, if present, tells the system how to create a process", "La table des en-têtes de programme, si présente, indique au système comment créer un processus"),
    ("image.", "image."),
    ("Each segment has a virtual address associated with its starting location.", "Chaque segment a une adresse virtuelle associée à son emplacement de départ."),
    ("Absolute code that references within each segment is permissible and very", "Le code absolu qui référence à l'intérieur de chaque segment est permis et très"),
    ("probable.", "probable."),
    ("An ELF object may also specify an entry point of the program,", "Un objet ELF peut également spécifier un point d'entrée du programme,"),
    ("that is, the", "c'est-à-dire l'"),
    ("virtual memory location that assumes control of the program.", "emplacement de mémoire virtuelle qui prend le contrôle du programme."),
    ("Thus to activate parasite code, the program flow must include the new parasite.", "Ainsi, pour activer le code parasite, le flux du programme doit inclure le nouveau parasite."),
    ("This can be done by patching the entry point in the ELF object to point", "Cela peut être fait en modifiant le point d'entrée dans l'objet ELF pour qu'il pointe"),
    ("(jump) directly to the parasite.", "(sauter) directement vers le parasite."),
    ("It is then the parasite's responsibility that the host code be executed -", "C'est ensuite la responsabilité du parasite que le code hôte soit exécuté -"),
    ("typically, by transferring control back to the host", "généralement, en transférant le contrôle de retour à l'hôte"),
    ("once the parasite has completed its execution.", "une fois que le parasite a terminé son exécution."),
    ("The resulting segments after parasite insertion into text segment padding looks", "Les segments résultants après insertion du parasite dans le remplissage du segment texte ressemencent"),
    ("To insert parasite code means that the process image must load it so that the", "Insérer du code parasite signifie que l'image du processus doit le charger afin que"),
    ("original code and data is still intact.", "le code et les données originaux restent intacts."),
    ("This means, that inserting a", "Cela signifie que insérer un"),
    ("parasite requires the memory used in the segments to be increased.", "parasite nécessite que la mémoire utilisée dans les segments soit augmentée."),
    ("The text segment compromises not only code,", "Le segment texte ne comprend pas seulement du code,"),
    ("but also the ELF headers including such things as dynamic linking information.", "mais aussi les en-têtes ELF incluant des choses comme les informations de liaison dynamique."),
    ("It may be possible to keep the text segment as is,", "Il peut être possible de garder le segment texte tel quel,"),
    ("and create another segment consisting of the parasite code,", "et de créer un autre segment constitué du code parasite,"),
    ("however introducing an extra segment is certainly questionable and easy to detect.", "cependant introduire un segment supplémentaire est certainement douteux et facile à détecter."),
    ("Page padding at segment borders however provides a practical location for", "Le remplissage de page aux frontières des segments fournit cependant un emplacement pratique pour"),
    ("parasite code given that its size is able.", "le code parasite si sa taille le permet."),
    ("This space will not interfere with the original segments,", "Cet espace ne interférera pas avec les segments originaux,"),
    ("requiring no relocation.", "n'exigeant aucun déplacement."),
    ("Following the guideline just", "En suivant la directive ci-dessus"),
    ("given of preferencing the text segment,", "de privilégier le segment texte,"),
    ("we can see that the padding at", "nous pouvons voir que le remplissage à"),
    ("the end of the text segment is a viable solution.", "la fin du segment texte est une solution viable."),
    ("Extending the text segment backwards is a viable solution and is documented", "Étendre le segment texte vers l'arrière est une solution viable et est documentée"),
    ("and implemented further in this article.", "et mise en œuvre plus loin dans cet article."),
    ("Extending the text segment forward or extending the data segment backward will", "Étendre le segment texte vers l'avant ou étendre le segment de données vers l'arrière"),
    ("probably overlap the segments.", "chevauchera probablement les segments."),
    ("Relocating a segment in memory will cause", "Déplacer un segment en mémoire causera"),
    ("problems with any code that absolutely references memory.", "des problèmes avec tout code qui référence absolument la mémoire."),
    ("It is possible to extend the data segment,", "Il est possible d'étendre le segment de données,"),
    ("however this isn't preferred,", "cependant ceci n'est pas préféré,"),
    ("as its not UNIX portable that properly implement execute memory protection.", "car il n'est pas portable pour UNIX qui implémente correctement la protection de la mémoire d'exécution."),
    ("An ELF parasite however is implemented using this technique and is explained", "Un parasite ELF est cependant implémenté en utilisant cette technique et est expliqué"),
    ("later in this article.", "plus loin dans cet article."),
    ("A more complete ELF executable layout is (ignoring section content - see", "Une disposition plus complète d'un exécutable ELF est (en ignorant le contenu des sections - voir"),
    ("below).", "ci-dessous)."),
    ("In practice, this is what is normally seen.", "En pratique, voici ce qui est normalement vu."),
    ("Typically, the extra sections (those not associated with a segment) are such", "Typiquement, les sections supplémentaires (celles non associées à un segment) sont telles que"),
    ("things as debugging information, symbol tables etc.", "des choses comme les informations de débogage, les tables de symboles etc."),
    ("An ELF header resides at the beginning and holds a", "Un en-tête ELF réside au début et contient une"),
    ("``road map'' describing the file's organization.", "``carte routière'' décrivant l'organisation du fichier."),
    ("Sections hold the bulk of object file information for the ", "Les sections contiennent la majeure partie des informations de fichier d'objet pour la"),
    ("linking view:", "vue de liaison :"),
    ("instructions, data, symbol table, relocation", "instructions, données, table de symboles, relocalisation"),
    ("information, and so on.", "informations, etc."),
    ("A program header table, if present, tells the system how to create a process image.", "Une table d'en-têtes de programme, si présente, indique au système comment créer une image de processus."),
    ("Files used to build a process image (execute a program) must have a", "Les fichiers utilisés pour construire une image de processus (exécuter un programme) doivent avoir une"),
    ("program header table;", "table d'en-têtes de programme ;"),
    ("relocatable files do not need one.", "les fichiers relocalisables n'en ont pas besoin."),
    ("A section header table contains information describing the file's sections.", "Une table d'en-têtes de section contient des informations décrivant les sections du fichier."),
    ("Every section has an entry in the table;", "Chaque section a une entrée dans la table ;"),
    ("each entry gives information such as the section name,", "chaque entrée donne des informations telles que le nom de la section,"),
    ("the section size, etc.", "la taille de la section, etc."),
    ("Files used during linking must have a section header table;", "Les fichiers utilisés pendant la liaison doivent avoir une table d'en-têtes de section ;"),
    ("other object files may or may not have one.", "d'autres fichiers objets peuvent ou ne pas avoir un."),
    ("Executable and shared object files statically represent programs.", "Les fichiers exécutables et les objets partagés représentent statiquement les programmes."),
    ("To execute such programs, the system uses the files to create dynamic program", "Pour exécuter ces programmes, le système utilise les fichiers pour créer des programmes dynamiques"),
    ("representations, or process images. A process image has segments that hold", "représentations, ou images de processus. Une image de processus a des segments qui tiennent"),
    ("its text, data, stack, and so on.", "son texte, ses données, sa pile, etc."),
    ("Program header. This section complements Part 1,", "En-tête de programme. Cette section complète la Partie 1,"),
    ("describing object file structures that relate directly to program execution.", "en décrivant les structures de fichiers objets qui se rapportent directement à l'exécution du programme."),
    ("The primary data structure, a program header table, locates segment images within the file", "La structure de données principale, une table d'en-têtes de programme, localise les images de segments dans le fichier"),
    ("and contains other information necessary to create the memory image for the program.", "et contient d'autres informations nécessaires pour créer l'image mémoire pour le programme."),
    ("String Table", "Table des chaînes"),
    ("String table sections hold null-terminated character sequences, commonly called", "Les sections de la table de chaînes contiennent des séquences de caractères terminées par un NUL, couramment appelées"),
    ("strings.", "chaînes."),
    ("The object file uses these strings to represent symbol and section", "Le fichier objet utilise ces chaînes pour représenter les symboles et les sections"),
    ("names.", "noms."),
    ("Symbol Table", "Table des symboles"),
    ("An object file's symbol table holds information needed to locate and relocate a", "La table de symboles d'un fichier objet contient les informations nécessaires pour localiser et relocaliser une"),
    ("program's symbolic definitions and references.", "définitions et références symboliques d'un programme."),
    ("A relocation section references two other sections:", "Une section de relocalisation référence deux autres sections :"),
    ("a symbol table and a section to modify.", "une table de symboles et une section à modifier."),
    ("Relocation sections in the ELF object are used for describing what needs to be", "Les sections de relocalisation dans l'objet ELF sont utilisées pour décrire ce qui doit être"),
    ("modified (relocated) in the object.", "modifié (relocalisé) dans l'objet."),
    ("The actual relocation is best presented by looking at the source.", "La relocalisation réelle est mieux présentée en regardant la source."),
    ("For more information on the relocation types refer to the ELF specifications.", "Pour plus d'informations sur les types de relocalisation, consultez les spécifications ELF."),
    ("Note that we ignore the global offset table completely", "Notez que nous ignorons complètement la table de décalage global"),
    ("and any relocation types of its nature.", "et tous les types de relocalisation de sa nature."),
    ("The implemented infector must use C parasite code that avoids libc and uses", "L' infecteur implémenté doit utiliser du code parasite C qui évite libc et utilise"),
    ("Linux syscalls exclusively.", "exclusivement des appels système Linux."),
    ("This means that plt/got problems are avoided.", "Cela signifie que les problèmes plt/got sont évités."),
    ("Likewise the parasite code must end in the following asm:", "De même, le code parasite doit se terminer par le asm suivant :"),
    ("This is so it can jump back to the host correctly.", "C'est ainsi qu'il peut revenir à l'hôte correctement."),
    ("It uses a little trickery", "Il utilise un peu de fourberie"),
    ("to do this properly.", "pour le faire correctement."),
    ("Why the popl loop?", "Pourquoi la boucle popl ?"),
    ("- well.. the jump back to host goes in", "- eh bien... le saut de retour à l'hôte va dans"),
    ("_before_ the end of main,", "_avant_ la fin de main,"),
    ("so there are still some variables to be pop'd back before your back to where you started.", "il reste donc certaines variables à remettre sur la pile avant de revenir où vous avez commencé."),
    ("you dont know how many variables have been pushed,", "vous ne savez pas combien de variables ont été poussées,"),
    ("so a unique magic number is used to mark the start/end of it", "alors un numéro magique unique est utilisé pour marquer le début/fin de celui-ci"),
    ("- check the initcode in relocater.c.", "- vérifiez le initcode dans relocater.c."),
    ("The movl $0x11112222,%ebp ?", "Le movl $0x11112222,%ebp ?"),
    ("- well.. u dont know where", "- eh bien... vous ne savez pas où"),
    ("abouts this jmp (back to host) is going to be in the code,", "ce jmp (retour à l'hôte) va être dans le code,"),
    ("so you substitute a unique magic number where you want the host entry point to go.", "alors vous substituez un numéro magique unique là où vous voulez que le point d'entrée de l'hôte aille."),
    ("Then you search the object code for the magic and replace.", "Ensuite, vous cherchez le code magique dans le code objet et le remplacez."),
    ("Parasite code that requires memory access requires the stack to be used", "Le code parasite qui nécessite un accès mémoire nécessite l'utilisation de la pile"),
    ("manually naturally.", "bien sûr."),
    ("No bss section can be used from within the virus code", "Aucune section bss ne peut être utilisée à partir du code du virus"),
    ("in the padding and text infectors because it can only use part of the text segment.", "dans le remplissage et les infecteurs de texte car il ne peut utiliser qu'une partie du segment texte."),
    ("It is strongly suggested that rodata not be used,", "Il est fortement suggéré de ne pas utiliser rodata,"),
    ("in-fact,", "en fait,"),
    ("it is strongly suggested that no location specific data be used at all that resides outside the parasite at infection time.", "il est fortement suggéré de ne pas utiliser de données spécifiques à un emplacement qui résident à l'extérieur du parasite au moment de l'infection."),
    ("Thus, if initialized data is to be used,", "Ainsi, si des données initialisées doivent être utilisées,"),
    ("it is best to place it in the text segment,", "il est préférable de le placer dans le segment texte,"),
    ("ie at the end of the parasite code - see below on calculating address", "c'est-à-dire à la fin du code parasite - voir ci-dessous pour le calcul de l'adresse"),
    ("locations of initialized data that is not known at compile/infection time.", "des données initialisées qui ne sont pas connues au moment de la compilation/infection."),
    ("If the heap is to be used,", "Si le tas doit être utilisé,"),
    ("then it will be operating system dependent.", "alors il dépendra du système d'exploitation."),
    ("The use of any shared library calls from within the parasite should be removed,", "L'utilisation de tout appel de bibliothèque partagée à partir du parasite devrait être supprimée,"),
    ("to avoid any linking problems and to maintain a portable parasite in files", "pour éviter tout problème de liaison et pour maintenir un parasite portable dans les fichiers"),
    ("that use varying libraries.", "qui utilisent des bibliothèques variées."),
    ("Most importantly, the parasite code must be relocatable.", "Surtout important, le code parasite doit être relocalisable."),
    ("It is possible to patch the parasite code before inserting it,", "Il est possible de patcher le code parasite avant de l'insérer,"),
    ("however the cleanest approach", "cependant l'approche la plus propre"),
    ("is to write code that doesn't need to be patched.", "est d'écrire du code qui n'a pas besoin d'être patché."),
    ("In x86 Linux, some syscalls require the use of an absolute address pointing to", "Sous Linux x86, certains appels système nécessitent l'utilisation d'une adresse absolue pointant vers"),
    ("initialized data.", "des données initialisées."),
    ("This can be made relocatable by using a common trick used in buffer overflow code.", "Cela peut être rendu relocalisable en utilisant une astuce courante utilisée dans le code de débordement de tampon."),
    ("By making a call directly proceeding the string of interest,", "En faisant un appel directement avant la chaîne d'intérêt,"),
    ("the address of the string is pushed onto the stack as the return address.", "l'adresse de la chaîne est poussée sur la pile en tant qu'adresse de retour."),
    ("in a UNIX environment the most probably method for a typical garden variety virus to spread is through", "dans un environnement UNIX, la méthode la plus probable pour qu'un virus typique se propage est par le biais de"),
    ("infecting files that it has legal permission to do so.", "l'infection de fichiers qu'il a la permission légale de faire."),
    ("A simple method of locating new files possible to infect,", "Une méthode simple pour localiser de nouveaux fichiers possibles à infecter,"),
    ("is by scanning the current directory for writable files.", "est de scanner le répertoire courant pour des fichiers modifiables."),
    ("This has the advantage of being", "Ceci a l'avantage d'être"),
    ("relatively fast (in comparison to large tree walks) but finds only a small percentage of infect-able files.", "relativement rapide (par rapport à de grands parcours d'arbres) mais ne trouve qu'un petit pourcentage de fichiers infectables."),
    ("Directory searches are however very slow irrespectively,", "Les recherches de répertoires sont cependant très lentes indépendamment,"),
    ("even without large tree walks.", "même sans grands parcours d'arbres."),
    ("If parasite code does not fork, its very quickly noticed what is happening.", "Si le code parasite ne fork pas, il est très rapidement remarqué ce qui se passe."),
    ("Forking, as mentioned,", "Forking, comme mentionné,"),
    ("easily solves the problem of slowing the startup to", "résout facilement le problème de ralentir le démarrage vers"),
    ("the host code,", "le code hôte,"),
    ("however new processes on the system can be spotted as abnormal if careful observation is used.", "cependant, de nouveaux processus sur le système peuvent être détectés comme anormaux si une observation attentive est utilisée."),
    ("The parasite code as mentioned,", "Le code parasite comme mentionné,"),
    ("must be completely written in machine code,", "doit être entièrement écrit en code machine,"),
    ("this does not however mean that development must be done like this.", "cependant, cela ne signifie pas que le développement doit être fait comme ça."),
    ("Development can easily be done in a high level language such as C and then", "Le développement peut facilement être effectué dans un langage de haut niveau tel que C puis"),
    ("compiled to asm to be used as parasite code.", "compilé en asm pour être utilisé comme code parasite."),
    ("A bootstrap process can be used for initial infection of the virus into a host", "Un processus de démarrage peut être utilisé pour l'infection initiale du virus dans un hôte"),
    ("program that can then be distributed.", "programme qui peut ensuite être distribué."),
    ("That is,", "C'est-à-dire,"),
    ("the ELF infector code is used,", "le code infecteur ELF est utilisé,"),
    ("with the virus as the parasite code to be inserted.", "avec le virus comme code parasite à insérer."),
    ("This virus implements the ELF infection described by utilizing the padding at", "Ce virus implémente l'infection ELF décrite en utilisant le remplissage à"),
    ("the end of the text segment. In this padding, the virus in its entirety is copied,", "la fin du segment texte. Dans ce remplissage, le virus dans sa totalité est copié,"),
    ("and the appropriate entry points patched.", "et les points d'entrée appropriés sont corrigés."),
    ("At the end of the parasite code,", "À la fin du code parasite,"),
    ("are the instructions.", "sont les instructions."),
    ("XXXX is patched when the virus replicates to the host entry point.", "XXXX est corrigé lorsque le virus se réplique vers le point d'entrée de l'hôte."),
    ("This approach does have the side effect of trashing the ebp register", "Cette approche a l'effet secondaire de corrompre le registre ebp"),
    ("which may or may not be destructive to programs who's entry points depend on ebp being set on entry.", "qui peut ou ne peut pas être destructeur pour les programmes dont les points d'entrée dépendent de ebp fixé à l'entrée."),
    ("On execution of an infected host,", "Lors de l'exécution d'un hôte infecté,"),
    ("the virus will copy the parasite (virus) code contained in itself (the file) into memory.", "le virus copiera le code parasite (virus) contenu en lui-même (le fichier) dans la mémoire."),
    ("The virus will then scan randomly (random enough for this instance) through", "Le virus scannera ensuite aléatoirement (assez aléatoirement pour cette instance) à travers"),
    ("the current directory,", "le répertoire courant,"),
    ("looking for ELF files of type ET_EXEC or ET_DYN to infect.", "en cherchant des fichiers ELF de type ET_EXEC ou ET_DYN à infecter."),
    ("It will infect up to Y_INFECT files,", "Il infectera jusqu'à Y_INFECT fichiers,"),
    ("and scan up to N_INFECT files in total.", "et scannera jusqu'à N_INFECT fichiers au total."),
    ("If a file can be infected,", "Si un fichier peut être infecté,"),
    ("ie, its of the correct ELF type, and the padding can sustain the virus,", "c'est-à-dire, s'il est du bon type ELF, et si le remplissage peut soutenir le virus,"),
    ("a a modified copy of the file incorporating the virus is made.", "une copie modifiée du fichier incorporant le virus est faite."),
    ("It then renames the copy to the file its infecting,", "Il renomme ensuite la copie en le fichier qu'il infecte,"),
    ("and thus it is infected.", "et ainsi il est infecté."),
    ("Due to the rather large size of the virus in comparison to the page size", "En raison de la taille assez grande du virus par rapport à la taille de page"),
    ("not all files are able to be infected, in fact only near half on average.", "tous les fichiers ne peuvent pas être infectés, en fait seulement près de la moitié en moyenne."),
    ("The Linux virus was completely written in C,", "Le virus Linux a été entièrement écrit en C,"),
    ("and strongly based around the ELF infector code.", "et fortement basé autour du code infecteur ELF."),
    ("The code requires the use of no libraries,", "Le code nécessite l'utilisation de aucune bibliothèque,"),
    ("and avoids libc by using a similar scheme to the", "_avoidance de libc en utilisant un schéma similaire au"),
    ("_syscall declarations Linux employs modified not to use errno.", "déclarations _syscall Linux employées modifiées pour ne pas utiliser errno."),
    ("Heap memory was used for dynamic allocation of the phdr and shdr tables using 'brk'.", "La mémoire du tas a été utilisée pour l'allocation dynamique des tables phdr et shdr en utilisant 'brk'."),
    ("Linux has some syscalls which require the address of initialized strings to", "Linux a certains appels système qui nécessitent l'adresse de chaînes initialisées pour"),
    ("be passed to it,", "être passées à lui,"),
    ("notably,", "notablement,"),
    ("open, rename, and unlink.", "open, rename et unlink."),
    ("This requires initialized data storage.", "Cela nécessite un stockage de données initialisées."),
    ("As stated before,", "Comme mentionné avant,"),
    ("rodata cannot be used,", "rodata ne peut pas être utilisé,"),
    ("so this data was placed at the end of the code.", "donc ces données ont été placées à la fin du code."),
    ("Making it relocatable required the use of the above mentioned algorithm of using call to push the address (return value) onto the stack.", "Rendre cela relocalisable a nécessité l'utilisation de l'algorithme mentionné ci-dessus consistant à utiliser un appel pour pousser l'adresse (valeur de retour) sur la pile."),
    ("To assist in the asm conversion, extra variables were declared so to leave room on the stack to store the addresses as in some cases the address was used more than once.", "Pour faciliter la conversion en asm, des variables supplémentaires ont été déclarées pour laisser de la place sur la pile pour stocker les adresses car dans certains cas l'adresse était utilisée plusieurs fois."),
    ("The C code form of the virus allowed for a debugging version which produces verbose output,", "La forme C du virus a permis une version de débogage qui produit une sortie verbeuse,"),
    ("and allows argv[0] to be given as argv[1].", "et permet argv[0] d'être donné comme argv[1]."),
    ("This is advantageous because you can setup a pseudo infected host which is non", "C'est avantageux parce que vous pouvez configurer un hôte pseudo-infecté qui est non"),
    ("replicating. Then run the virus making argv[0] the name of the pseudo infected host.", "réplicateur. Exécutez ensuite le virus en faisant de argv[0] le nom de l'hôte pseudo-infecté."),
    ("It would replicate the parasite from that host.", "Il répliquerait le parasite de cet hôte."),
    ("Thus it was possible to test without having a binary version of a replicating virus.", "Ainsi, il était possible de tester sans avoir de version binaire d'un virus réplicateur."),
    ("The C code was converted to asm using the c compiler gcc, with the -S flag to produce assembler.", "Le code C a été converti en asm en utilisant le compilateur gcc, avec l'indicateur -S pour produire de l'assembleur."),
    ("Modifications were made so that use of rodata for initialized data (strings for open, unlink, and rename), was replaced with the relocatable data using the call address methodology.", "Des modifications ont été apportées afin que l'utilisation de rodata pour des données initialisées (chaînes pour open, unlink et rename) soit remplacée par des données relocalisables utilisant la méthode d'adresse d'appel."),
    ("Most of the registers were saved on virus startup and restored on exit (transference of control to host).", "La plupart des registres ont été sauvegardés au démarrage du virus et restaurés à la sortie (transfert de contrôle à l'hôte)."),
    ("The asm version of the virus, can be improved tremendously in regards to efficiency,", "La version asm du virus peut être améliorée considérablement en termes d'efficacité,"),
    ("which will in turn improve the expected life time and replication of the virus (a smaller virus can infect more objects, where previously the padding would dictate the larger virus couldn't infect it).", "ce qui améliorera à son tour la durée de vie et la réplication attendues du virus (un virus plus petit peut infecter plus d'objets, là où le remplissage aurait précédemment dicté que le virus plus grand ne pouvait pas l'infecter)."),
    ("The asm virus was written with development time the primary concern and hence almost zero time was spent on hand optimization of the code gcc generated from the C version.", "Le virus asm a été écrit avec le temps de développement comme préoccupation principale et donc presque zéro temps a été consacré à l'optimisation manuelle du code généré par gcc à partir de la version C."),
    ("In actual fact,", "En fait,"),
    ("less than 5 minutes were spent in asm editing - this is", "moins de 5 minutes ont été consacrées à l'édition asm - ceci est"),
    ("indicative that extensive asm specific skills are not required for a non", "indicatif que des compétences asm approfondies ne sont pas nécessaires pour un"),
    ("optmized virus.", "virus non optimisé."),
    ("The edited asm code was compiled (elf-p-virus-egg.c), and then using objdump", "Le code asm édité a été compilé (elf-p-virus-egg.c), puis en utilisant objdump"),
    ("with the -D flag, the addresses of the parasite start, the required offsets for", "avec l'indicateur -D, les adresses du début du parasite, les décalages requis pour"),
    ("patching were recorded. The asm was then edited again using the new", "le patchage ont été enregistrés. L'asm a ensuite été modifié à nouveau en utilisant les nouvelles"),
    ("information.", "informations."),
    ("The executable produced was then patched manually for any bytes needed.", "L'exécutable produit a ensuite été patché manuellement pour les octets nécessaires."),
    ("elf-egg2text", "elf-egg2text"),
    ("The infector was recompiled and thus can infect the host it was compiled for", "L' infecteur a été recompilé et peut ainsi infecter l'hôte pour lequel il a été compilé"),
    ("making it a live virus.", "en le rendant un virus vivant."),
    ("null-carrier is the supplied host program that the", "null-carrier est le programme hôte fourni que"),
    ("infector is compiled for.", "l' infecteur est compilé pour."),
    ("This completed the manual infection of the virus to a host.", "Ceci a terminé l'infection manuelle du virus à un hôte."),
    ("The newly infected", "Le nouvellement infecté"),
    ("host would then attempt replication on execution.", "l'hôte tenterait alors la réplication lors de l'exécution."),
    ("A live virus has been included in the source package (live-virus-be-warned).", "Un virus vivant a été inclus dans le paquet source (live-virus-be-warned)."),
    ("A simplified carrier", "Un porteur simplifié"),
    ("program (carrier.S) was used to host the virus (null-carrier is the uninfected host as stated).", "programme (carrier.S) a été utilisé pour héberger le virus (null-carrier est l'hôte non infecté comme indiqué)."),
    ("The first major change that would increase the life time and replication rates", "Le premier changement majeur qui augmenterait la durée de vie et les taux de réplication"),
    ("of the virus is to optimise the code to be space efficient.", "du virus est d'optimiser le code pour qu'il soit efficace en espace."),
    ("The replication is notable rather slow scanning only the current directory.", "La réplication est assez lente, ne scannant que le répertoire courant."),
    ("The virus may be modified to do small tree walks increasing infection rates dramatically.", "Le virus peut être modifié pour effectuer de petits parcours d'arbres augmentant considérablement les taux d'infection."),
    ("The virus is easily detected - see below.", "Le virus est facilement détectable - voir ci-dessous."),
    ("The virus described is relatively easy to detect.", "Le virus décrit est relativement facile à détecter."),
    ("The blatant oddity is that", "L'absurdité évidente est que"),
    ("the entry point of the program isn't in a normal section or not in a section at all.", "le point d'entrée du programme n'est pas dans une section normale ou pas dans une section du tout."),
    ("Typically the last section in the text segment is .rodata which obviously", "Typiquement, la dernière section dans le segment texte est .rodata qui est évident"),
    ("shouldn't be the entry point.", "ne devrait pas être le point d'entrée."),
    ("Likewise,", "De même,"),
    ("it is suspicious if a program does not have a corresponding section then this arouses any would be virus scanner.", "il est suspect si un programme n'a pas de section correspondante alors cela suscite la suspicion de tout scanner de virus."),
    ("Also if no section table at all,", "Aussi, si aucune table de section du tout,"),
    ("which will disguise what section the entry point is in,", "ce qui masquera quelle section est le point d'entrée,"),
    ("is certainly an odd event (even though this is optional).", "est certainement un événement étrange (même si ceci est optionnel)."),
    ("Removal of the virus described here, is similar to infection,", "La suppression du virus décrit ici, est similaire à l'infection,"),
    ("requiring", "nécessitant"),
    ("deletion of the virus code,", "la suppression du code virus,"),
    ("modification of the ELF headers to reflect segment relocation in the file and patching of the entry point to jump to the proper code.", "la modification des en-têtes ELF pour refléter le déplacement du segment dans le fichier et le correctif du point d'entrée pour sauter vers le code approprié."),
    ("Location of the correct entry point can be easily seen by disassembling the executable using objdump,", "L'emplacement du point d'entrée correct peut être facilement vu en désassemblant l'exécutable en utilisant objdump,"),
    ("matching the entry point of the infected file to", "en correspondant le point d'entrée du fichier infecté au"),
    ("the disassembled code,", "code désassemblé,"),
    ("and tracing through the code to find where the parasite code returns flow back to the host.", "en traçant à travers le code pour trouver où le code parasite revient le flux vers l'hôte."),
    ("On occasion no section matches the parasite code and hence the entry point.", "Occasionnellement, aucune section ne correspond au code parasite et donc au point d'entrée."),
    ("However, gdb can be used to disassemble manually,", "Cependant, gdb peut être utilisé pour désassembler manuellement,"),
    ("and the same method of manually finding the host entry point can be used as above.", "et la même méthode de trouver manuellement le point d'entrée de l'hôte peut être utilisée comme ci-dessus."),
    ("Automated virus detection of these variety of UNIX virus is practical by", "La détection automatisée de virus de cette variété de virus UNIX est pratique en"),
    ("detecting missing section headers and/or entry points to non permissible", "détectant les en-têtes de section manquants et/ou les points d'entrée vers des sections"),
    ("sections or segments.", "ou segments non admissibles."),
    ("Typical general virus detection algorithms are directly applicable in UNIX,", "Les algorithmes généraux typiques de détection de virus sont directement applicables dans UNIX,"),
    ("including signature strings, code flagging, file integrity checking etc.", "y compris les chaînes de signature, le marquage de code, la vérification d'intégrité des fichiers, etc."),
    ("The major problem in terms of evading detection with the parasite described,", "Le principal problème en termes d'évasion de la détection avec le parasite décrit,"),
    ("is that the entry point changes to a suspicious position.", "est que le point d'entrée change vers une position suspecte."),
    ("Ideally,", "Idéalement,"),
    ("the entry point of the program either wouldn't change or stay within expected sections.", "le point d'entrée du programme ne changerait pas ou resterait dans les sections attendues."),
    ("A possible method using the parasite described would be to find unused memory in normal entry point sections such as the .text section,", "Une méthode possible en utilisant le parasite décrit serait de trouver de la mémoire inutilisée dans des sections de points d'entrée normaux comme la section .text,"),
    ("and insert code to jump to the parasite code.", "et insérer du code pour sauter vers le code parasite."),
    ("This would require only a small number of bytes,", "Ceci ne nécessiterait qu'un petit nombre d'octets,"),
    ("and such empty space is common,", "et un tel espace vide est courant,"),
    ("as can be noted by looking through disassembly of executables.", "comme on peut le noter en regardant la désassemblage des exécutables."),
    ("Alternatively,", "Alternativement,"),
    ("one of the original ideas of where to insert the parasite code,", "l'une des idées originelles de où insérer le code parasite,"),
    ("thrown away,", "jetée, "),
    ("by extending the text segment backwards may be possible.", "par l'extension du segment texte vers l'arrière peut être possible."),
    ("The parasite code and entry point would belong in the .text section and thus", "Le code parasite et le point d'entrée seraient dans la section .text et ainsi"),
    ("seemingly be quite normal.", "apparemment assez normal."),
    ("The algorithms and implementation presented gives a clear example and proof of concept that UNIX while not popular for,", "Les algorithmes et l'implémentation présentés donnent un exemple clair et une preuve de concept que UNIX, bien qu'aucement populaire pour,"),
    ("is actually a viable breeding ground for parasites and virus.", "est en fait un terrain de chasse viable pour les parasites et les virus."),
    ("begin 644 unix-viruses-src.tgz", "begin 644 unix-viruses-src.tgz"),
    ("The year was 1998, I \"elfmaster\" was about 15yrs old. At this time, the", "L'année était 1998, j'« elfmaster » avais environ 15 ans. À cette époque, la"),
    ("underground hacking scene had a mystical undercurrent and was teaming with", "scène underground du hacking avait une sous-courante mystique et fourmillait de"),
    ("digital life on EFNET IRC: #phrack, #hackers, #b4b0, etc.", "vie numérique sur EFNET IRC : #phrack, #hackers, #b4b0, etc."),
    ("I was acquainted", "Je me suis fait connaître"),
    ("with Silvio through mutual channels and zines.", "avec Silvio à travers des canaux et des zines mutuels."),
    ("It was quickly apparent to me", "Il était rapidement évident pour moi"),
    ("that Silvio was a mad scientist who's brilliant research only got more", "que Silvio était un scientifique fou dont la recherche brillante ne faisait que"),
    ("innovative with each publication.", "s'améliorer avec chaque publication."),
    ("At this time Silvio's deepest interest", "À cette époque, l'intérêt le plus profond de Silvio"),
    ("lay in the pioneering of ELF virus infection,", "réside dans la pionnière de l'infection par virus ELF,"),
    ("for which he paved the way through a series of radical papers dropping non-trivial details on this subject that was", "pour laquelle il a ouvert la voie à travers une série de papiers radicaux détaillant des aspects non triviaux de ce sujet qui était"),
    ("considered esoteric even amongst the most elite hackers of the time-- at this\ntime UNIX/Linux reverse engineering and virus design was infintile in its", "considéré comme ésotérique même parmi les hackers les plus élus de l'époque-- à l'époque, le reverse engineering de UNIX/Linux et la conception de virus étaient dans leur"),
    ("state of evolution.", "état d'évolution."),
    ("Silvio raised the state of the art in UNIX/Linux reversing", "Silvio a élevé le niveau de l'art du reverse engineering UNIX/Linux"),
    ("through his innovation of ELF virus technology,", "à travers son innovation de la technologie de virus ELF,"),
    ("greatly impacting the\nunderground hacker scene and academia for decades to come...", "en impactant considérablement la scène underground des hackers et l'académie pour des décennies à venir..."),
    ("At some point during the golden era of 1998,", "À un moment donné pendant l'ère d'or de 1998,"),
    ("the paper \"UNIX Viruses\"", "le papier \"UNIX Viruses\""),
    ("caught my attention on VXHeaven under the \"UNIX and Clones\" reading section.", "a attiré mon attention sur VXHeaven sous la section de lecture \"UNIX and Clones\"."),
    ("A highly technical paper by Silvio detailing 3 new infection techniques,", "Un papier hautement technique par Silvio détaillant 3 nouvelles techniques d'infection,"),
    ("relocatable code injection, position-independent code techniques, ELF virus", "injection de code relocalisable, techniques de code indépendant de la position, virus ELF"),
    ("detection, and more.", "détection, et plus encore."),
    ("This paper (And others) of Silvio's invograted me,", "Ce papier (Et d'autres) de Silvio m'a inspiré,"),
    ("I was compelled to learn with", "je me suis senti obligé d'apprendre avec"),
    ("a tenacity purely inspired by this magical and arcane research. Silvio's work in", "une ténacité purement inspirée par cette recherche magique et arcanique. Le travail de Silvio dans"),
    ("pioineering ELF virus technology was groundbreaking for computer security and", "la pionnière de la technologie de virus ELF a été révolutionnaire pour la sécurité informatique et"),
    ("computer science technologies in general...", "les technologies des sciences informatiques en général..."),
    ("Here we are now, 25 years later.", "Nous voilà maintenant, 25 ans plus tard."),
    ("At tmp.0ut we carry deep love and respect", "Dans tmp.0ut nous portons un profond amour et respect"),
    ("for Silvio and his profound body of research.", "pour Silvio et son vaste corpus de recherche."),
    ("Let us honor his work by releasing", "Honorons son travail en publiant"),
    ("the 25th Anniversary edition of \"UNIX Viruses\"!", "l'édition du 25e anniversaire de \"UNIX Viruses\" !"),
    ("self-replicator", "auto-réplicateur"),
    ("self-replicators", "auto-réplicateurs"),
    ("virus", "virus"),
    ("viruses", "virus"),
    ("parasite", "parasite"),
    ("ELF", "ELF"),
    ("UNIX", "UNIX"),
    ("Linux", "Linux"),
    ("C compiler", "compilateur C"),
    ("syscall", "appel système"),
    ("memory", "mémoire"),
    ("stack", "pile"),
    ("kernel", "noyau"),
    ("binary", "binaire"),
    ("source code", "code source"),
    ("assembler", "assembleur"),
    ("executable", "exécutable"),
    ("relocatable", "relocalisable"),
    ("infect", "infecter"),
    ("infection", "infection"),
    ("replicate", "répliquer"),
    ("replication", "réplication"),
    ("mutation", "mutation"),
    ("metamorphism", " métamorphisme"),
    ("LLM", "LLM"),
    ("LLMs", "LLM"),
    ("GPT", "GPT"),
])

print("Batch done: 03.html")
