import re

def translate_file(src_path, dst_path, title_fr, translations):
    with open(src_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', content)
    
    for orig, trans in translations:
        content = content.replace(orig, trans)
    
    credit = '\n[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    elif '</pre></div>' in content:
        content = content.replace('</pre></div>', credit + '</pre></div>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {dst_path}")

# 13.html - Weird ELFs
translate_file('/home/ubuntu/tmpout-fr/3/13.html', '/home/ubuntu/tmpout-fr/3/fr/13.html',
    "Des ELFs bizarres, ou l'histoire de casser des parseurs encore une fois", [
    ("Some time ago i enjoyed a speedrun  of  LiveOverflow videos, and ideas from one",
     "Il y a un certain temps, j'ai apprécié une speedrun de vidéos de LiveOverflow, et des idées d'une"),
    ("of them [1] haunted  me until my  curiosity took over and  i finally started my",
     "d'entre elles [1] m'a hanté jusqu'à ce que ma curiosité prenne le dessus et que j'aie"),
    ("own research.  The  point was simple: feed a program an ELF corrupted so that a",
     "commencé ma propre recherche. Le point était simple : donner à un programme un ELF corrompu"),
    ("parser breaks, but the kernel nevertheless successfully runs the executable.",
     "de sorte qu'un parseur se casse la gueule, mais le noyau exécute quand même l'exécutable."),
    ("I decided to dig a bit deeper and not just get  broken-but-runnable ELF files--",
     "J'ai décidé d'approfondir et de ne pas me contenter de fichiers ELF cassés mais exécutables--"),
    ("it  has been done many times before me already--but also comprehend the problem",
     "ça a déjà été fait plusieurs fois avant moi--mais aussi de comprendre le problème"),
    ("of parsers more entirely and widely. And here i want to share my story.",
     "des parseurs plus en profondeur et plus largement. Et ici je veux partager mon histoire."),
    ("0x01: langsec", "0x01: langsec"),
    ("langsec+0x10: a note on polyglots", "langsec+0x10: une note sur les polyglottes"),
    ("langsec+0x20: parse tree differentials", "langsec+0x20: différentielles d'arbres d'analyse"),
    ("0x02: ELF parsers", "0x02: analyseurs ELF"),
    ("ELF parsers+0x10: defining targets", "analyseurs ELF+0x10: définition des cibles"),
    ("0x03: finding differentials", "0x03: trouver des différentielles"),
    ("finding differentials+0x10: Linux", "trouver des différentielles+0x10: Linux"),
    ("finding differentials+0x20: gdb", "trouver des différentielles+0x20: gdb"),
    ("finding differentials+0x30: edb and CVE-2023-27734", "trouver des différentielles+0x30: edb et CVE-2023-27734"),
    ("finding differentials+0x40: r2hang", "trouver des différentielles+0x40: r2hang"),
    ("0x04: .atexit", "0x04: .atexit"),
    ("0xfe: thanks", "0xfe: remerciements"),
    ("0xff: references", "0xff: références"),
    ("Research dedicated  to parser  problems specifically ", "Recherche dédiée aux problèmes de parseurs spécifiquement "),
    ("started with the birth of", "a commencé avec la naissance de"),
    ("langsec [2], and many parser bugs were discovered and discussed ever since.", "langsec [2], et de nombreux bugs de parseurs ont été découverts et discutés depuis."),
    ("Langsec studies different parser problems, namely where the theory (i.e. specs)", "Langsec étudie différents problèmes de parseurs, notamment là où la théorie (c.-à-d. les spécifications)"),
    ("and implementations differ.  Be liberal in what you recieve, they say [3]. This", "et les implémentations diffèrent. Soyez libéraux dans ce que vous recevez, disent-ils [3]. Cela"),
    ("is, some deviations from the standards are ok  as long as the context is enough", "signifie que certaines déviations des normes sont acceptables tant que le contexte est suffisant"),
    ("to recover the meaning of the input data.  That is,  a parser can fill the gaps", "pour récupérer le sens des données d'entrée. C'est-à-dire, qu'un analyseur peut combler les lacunes"),
    ("and presume  the missing  data as  it wants.  Sometimes being much more liberal", "et supposer les données manquantes comme il l'entend. Parfois, être beaucoup plus libéral"),
    ("than  the spec tells to be.  And,  sometimes,  different parsers  fill the gaps", "que le spécifie la norme. Et parfois, différents analyseurs remplissent les lacunes"),
    ("different ways.", "de différentes manières."),
    ("These lead to an interesting outcome, making funny things possible. Here we'll", "Cela conduit à un résultat intéressant, rendant possible des choses amusantes. Nous allons voir"),
    ("take a look at two of them: polyglot files and parse tree differentials.", "deux exemples : les fichiers polyglottes et les différentielles d'arbres d'analyse."),
    ("Polyglot files happen when a standard or its implementation are loose enough to", "Les fichiers polyglottes se produisent quand une norme ou son implémentation sont assez lâches pour"),
    ("embed another file into it,  so that two parsers  of two different  formats can", "intégrer un autre fichier dedans, de sorte que deux analyseurs de deux formats différents puissent"),
    ("successfully operate with such file.  As corkami mentions [4],  PDF allows much", "fonctionner correctement avec un tel fichier. Comme le mentionne corkami [4], le PDF permet beaucoup"),
    ("liberty in this sense,  and he uses PDF a lot in his own PoCs of polyglots. One", "de liberté dans ce sens, et il utilise PDF beaucoup dans ses propres PoC de polyglottes. Un"),
    ("of my favourites is a PDF that, when run, acts as a python web-server with a JS", "de mes préférés est un PDF qui, lorsqu'il est exécuté, agit comme un serveur web Python avec un"),
    ("compiler and many more [5]. It's much fun to reverse that :D", "compilateur et bien plus [5]. C'est amusant à reverse :D"),
    ("Another example i'd like to mention is an a actually portable executable [6]. Its",
     "Un autre exemple que j'aimerais mentionner est un exécutable réellement portable [6]. Son"),
    ("author managed to mix PE, ELF, Mach-O, sh and bare bootsector into one, so that", "auteur a réussi à mélanger PE, ELF, Mach-O, sh et bootsector nu en un seul, de sorte que"),
    ("a single file is able to run in those environments.  Incredible research, may i", "un seul fichier puisse s'exécuter dans ces environnements. Recherche incroyable, puis-je"),
    ("This type  of parser issues  becomes  possible when  two implementations of the", "Ce type de problème de parseur devient possible quand deux implémentations de la"),
    ("same  standard  behave  differently  in  some cases.", "même norme se comportent différemment dans certains cas."),
    ("During  my  research,  i", "Pendant ma recherche, j'ai"),
    ("gathered several examples i find the most demonstrative.", "rassemblé plusieurs exemples que je trouve les plus démonstratifs."),
    ("The first one i ought to mention is bugs in x509 certificates parsers described",
     "Le premier que je dois mentionner est les bugs dans les analyseurs de certificats x509 décrits"),
    ("in 2010 by langsec pioneers, Len Sassaman and Meredith Patterson, who wondered:",
     "en 2010 par les pionniers de langsec, Len Sassaman et Meredith Patterson, qui se sont demandé :"),
    ("what if put a  NULL-byte in a CN field [7]?  This  turned out to be a phisher's",
     "et si on mettait un octet nul dans un champ CN [7] ? Cela s'est révélé être un rêve"),
    ("dream,  as the browsers under test showed a user only a part of domain prior to", "de pêle-mineur, car les navigateurs en test ne montraient à l'utilisateur qu'une partie du domaine"),
    ("the NULL-byte, while the domain might be something like:", "avant l'octet nul, tandis que le domaine pourrait être quelque chose comme :"),
    ("with a completely valid certificate.", "avec un certificat complètement valide."),
    ("Another example i like  is  about XML.  XML is  an  amazing format to find bugs",
     "Un autre exemple que j'aime bien concerne XML. XML est un format étonnant pour trouver des bugs"),
    ("around: it's generally so simple for humans yet so hard to be parsed correctly.",
     "autour : il est généralement si simple pour les humains mais si difficile à analyser correctement."),
    ("A security  researcher once asked:  `Find me two  different  XML  parsers  that",
     "Un chercheur en sécurité a demandé un jour : « Trouvez-moi deux analyseurs XML"),
    ("always, for every input, result in the same output' [8]. What could possibly go", "différents qui donnent toujours le même résultat pour toute entrée » [8]. Que pourrait-il"),
    ("wrong if it was used to hold entitlements info an PLIST files?  Even more, what", "se passer de travers si c'était utilisé pour contenir des informations d'entitlement dans des"),
    ("could ever go wrong  if  we had four XML parsers  in  the system,  one of which", "fichiers PLIST ? Encore plus, que pourrait-il se passer de travers si nous avions quatre"),
    ("operated in kernel space?", "analyseurs XML dans le système, dont un fonctionnait dans l'espace noyau ?"),
    ("This bug could be used for  a  sandbox  escape  in  iOS.  And  at that time, an",
     "Cette faille pourrait être utilisée pour une évasion de sandbox sous iOS. Et à cette époque,"),
    ("incredible solution  was  to  introduce  the  fifth  PLIST  parser,",
     "une solution incroyable a été d'introduire le cinquième analyseur PLIST,"),
    ("making the researcher who found the bug even more  happy  [9, section 5].  Later,",
     "rendant le chercheur qui a trouvé le bug encore plus heureux [9, section 5]. Plus tard,"),
    ("however, they decided to move to a binary DER format [10].", "ils ont décidé de passer à un format binaire DER [10]."),
    ("Yet another  amusing  parser  issue  is  named  Sophail,  after  Sophos AV,",
     "Un autre problème de parseur amusant s'appelle Sophail, d'après Sophos AV,"),
    ("and relates to the fact that the AV  skipped  further checks on an ELF if it was of",
     "et concerne le fait que l'AV a ignoré d'autres vérifications sur un ELF s'il était"),
    ("one specific architecture [11].", "d'une architecture spécifique [11]."),
    ("As for breaking analysis in  practice,  a  crash due to insufficient checks on",
     "En ce qui concerne la cassure d'analyse en pratique, un plantement dû à des vérifications"),
    ("some PE header data in x64dbg was said to be used by malware in the wild [12].",
     "insuffisantes sur des données d'en-tête PE dans x64dbg aurait été utilisé par un malware"),
    ("Now that we've  come closer to ELF parsers,  let's see what has been done on it",
     "Maintenant que nous nous sommes rapprochés des analyseurs ELF, voyons ce qui a été fait"),
    ("already. Back in 2012 nitr0us performed similar research [13] on how to make an",
     "déjà. En 2012, nitr0us a effectué une recherche similaire [13] sur la façon de rendre un"),
    ("ELF debug-resistant,  but  not by the runtime checks, as it ways for the latter",
     "ELF résistant au débogage, mais pas par les vérifications à l'exécution, car cela"),
    ("were known already and thus not that interesting.", "était déjà connu et donc pas très intéressant."),
    ("nitr0us managed to break gdb", "nitr0us a réussi à casser gdb"),
    ("7.5.1 and IDA Pro 6.3 with an ELF that ran perfectly;", "7.5.1 et IDA Pro 6.3 avec un ELF qui fonctionnait parfaitement ;"),
    ("and a bug in OpenBSD ELF", "et un bug dans le chargeur ELF d'OpenBSD"),
    ("loader was also found [14].", "a également été trouvé [14]."),
    ("Now it's time to clarify the task.  First i wanted to get an ELF that would run",
     "Il est temps de préciser la tâche. D'abord, je voulais obtenir un ELF qui s'exécute"),
    ("but would fail to open in gdb, edb-debugger, radare2. Later, however, it turned",
     "mais échoue à s'ouvrir dans gdb, edb-debugger, radare2. Cependant, plus tard, il s'est"),
    ("out to be about debugging  the  debugger  (much fun, i must admit!)  and fixing bugs",
     "avéré que c'était du débogage du débogueur (très amusant, je dois l'avouer !) et de"),
    ("i found since all the tools are open source.", "retrouver des bugs que j'ai trouvés puisque tous les outils sont open source."),
    ("The easiest way  to  find  a  differential  is  by  fuzzing.  There are several",
     "La façon la plus facile de trouver une différence est de fuzzer. Il existe plusieurs"),
    ("approaches that could be used:", "approches qui pourraient être utilisées :"),
    ("1. 30-lines python script. This is what LiveOverflow used in his video, and ",
     "1. Script Python de 30 lignes. C'est ce que LiveOverflow a utilisé dans sa vidéo, et"),
    ("   just the same logic helped in finding several r2 bugs published in tmp.0ut",
     "   la même logique a aidé à trouver plusieurs bugs r2 publiés dans tmp.0ut"),
    ("   issue 1 [15].", "   numéro 1 [15]."),
    ("2. AFL++ or LibFuzzer. They are goot when targeting a particular software, but",
     "2. AFL++ ou LibFuzzer. Ils sont bons quand on cible un logiciel particulier, mais"),
    ("   that's not what i wanted (which was to get a bunch of corrupted ELF files to",
     "   ce n'est pas ce que je voulais (je voulais obtenir un tas de fichiers ELF corrompus pour"),
    ("   analyze with all the tools in question).", "   analyser avec tous les outils en question)."),
    ("3. Some ELF-aware fuzzer that generates ELFs corrupted in a special way. OS is",
     "3. Un fuzzer conscient des ELF qui génère des ELF corrompus d'une manière spéciale. Le"),
    ("   known to ignore section headers info, but debuggers and disassemblers  parse",
     "   système d'ignore les informations d'en-têtes de section, mais les débogueurs et"),
    ("   it to name functions, sections, or apply DWARF data if any. Section headers", "   les désassembleurs analysent pour nommer les fonctions, sections, ou appliquer les"),
    ("   is exactly what could be targeted to get a runnable ELF that would not", "   données DWARF si disponibles. Les en-têtes de section sont exactement ce qui"),
    ("   analyze.", "   pourrait être ciblé pour obtenir un ELF exécutable qui ne s'analyse pas."),
    ("I found a fuzzer authored by nitr0us already familiar to us. The fuzzer proudly",
     "J'ai trouvé un fuzzer créé par nitr0us déjà connu de nous. Le fuzzer, fier de"),
    ("named Melkor [16]  can corrupt specific parts of ELF files which is just what i",
     "ses nom Melkor [16], peut corrompre des parties spécifiques de fichiers ELF, ce qui"),
    ("needed. So, i generated a hundred of ELF files with broken Section Header Table", "était exactement ce dont j'avais besoin. J'ai donc généré cent fichiers ELF avec une"),
    ("(SHT) out of a template ELF with the following command:", "table d'en-têtes de section (SHT) cassée à partir d'un ELF modèle avec la commande suivante :"),
    ("I decided to generate only 100 ELF files with broken SHT so that i have a set", "J'ai décidé de générer seulement 100 fichiers ELF avec SHT cassée afin d'avoir un"),
    ("of inputs small enough to embrace if i need to manually analyze some cases.", "ensemble d'entrées suffisamment petit pour l'adopter si je dois analyser manuellement certains cas."),
    ("10 of the generated files segfaulted when run.  Most of this problem was due to",
     "10 des fichiers générés ont fait un segfault lors de l'exécution. La plupart de ce"),
    ("requested interpreter was the same as the binary:", "problème était que l'interpréteur demandé était le même que le binaire :"),
    ("[Requesting program interpreter: orcs_foo/orc_0013]", "[Requesting program interpreter: orcs_foo/orc_0013]"),
    ("However, this was not the only  cause.  In  a  couple of ELFs  Melkor broke plt",
     "Cependant, ce n'était pas la seule cause. Dans quelques ELF, Melkor a cassé la PLT"),
    ("(procedure linkage table),  so that any call to external function from such ELF",
     "(table de liaison des procédures), de sorte que tout appel à une fonction externe"),
    ("would segfault, because instead of jumping to .got.plt the execution would jump",
     "de cet ELF ferait un segfault, car au lieu de sauter vers .got.plt, l'exécution"),
    ("to an ASCII smiley in .rodata section.", "sauterait vers un sourire ASCII dans la section .rodata."),
    ("6 more files wouldn't run because their dynamic dependencies were messed up:",
     "6 autres fichiers ne pouvaient pas s'exécuter car leurs dépendances dynamiques étaient cassées :"),
    ("orcs_foo/orc_0050: error while loading shared libraries: lib %x .6: cannot",
     "orcs_foo/orc_0050 : erreur lors du chargement des bibliothèques partagées : lib %x .6 : impossible"),
    ("So, i was left with 84 files that run. Do they break debuggers?",
     "d'ouvrir le fichier objet partagé : No such file or directory."),
    ("gdb is your friend #1 if you want to prevent analysis.  It is a mature debugger",
     "J'ai donc 84 fichiers qui fonctionnent. Est-ce qu'ils cassent les débogueurs ?"),
    ("that performs many sanity checks and refuses to analyze a malformed file.",
     "gdb est votre ami n°1 si vous voulez empêcher l'analyse. C'est un débogueur mature"),
    ("In 98", "qui effectue de nombreuses vérifications de sécurité et qui refuse d'analyser un fichier malformé."),
    ("cases it said:", "Dans 98"),
    ("not in executable format: file format not recognized", "cas, il a dit :"),
    ("And in one:", "not in executable format: file format not recognized"),
    ("Can't read symbols from .../orcs_foo/orc_0063: bad value", "Et dans un seul cas :"),
    ("Eventually, gdb agreed to open and run only one file of the broken hundred.",
     "Impossible de lire les symboles depuis .../orcs_foo/orc_0063 : bad value"),
    ("edb segfaulted 55 times and was killed with SIGFPE (Floating point exception) 9",
     "Finalement, gdb a accepté d'ouvrir et d'exécuter un seul fichier des cent cassés."),
    ("times. Both bugs originated in the code responsible for symbols parsing, namely",
     "edb a fait un segfault 55 fois et a été tué avec SIGFPE (exception de virgule flottante) 9 fois."),
    ("the BinaryInfo edb plugin.", "Les deux bugs provenaient du code chargé de l'analyse des symboles, à savoir"),
    ("In the first case,  the  section name string pointer (more precisely, an offset", "le plugin BinaryInfo d'edb."),
    ("into the section names section, .shstrtab)  was  not  checked to lie within the", "Dans le premier cas, le pointeur de chaîne de nom de section (plus précisément, un"),
    ("file when looking  for specific sections.  In case of FPE,  edb tried iterating", "offset dans la section des noms de sections, .shstrtab) n'était pas vérifié pour"),
    ("through symbol tables.  Prior to walking, it needed to  calculate the number of", "se trouver dans le fichier lors de la recherche de sections spécifiques. Dans le cas"),
    ("entries in the table.  This was done by dividing section size by its entry size", "d'FPE, edb a essayé d'itérer à travers les tables de symboles. Avant de marcher,"),
    ("with no check wether entry was was zero. SIGFPE, despite its name, is generated", "il devait calculer le nombre d'entrées dans la table. Cela a été fait en divisant"),
    ("in case of a division by zero as well.", "la taille de la section par la taille de son entrée sans vérifier si l'entrée était zéro."),
    ("Both bugs were fixed [17], and  for  some reason only one  of them got assigned", "SIGFPE, malgré son nom, est également généré en cas de division par zéro."),
    ("CVE-2023-27734.", "Les deux bugs ont été corrigés [17], et pour une raison quelconque, seul un d'eux a été attribué"),
    ("r2 did not crash on any file.  When  trying to debug,  it reported segfaults of", "CVE-2023-27734."),
    ("the binaries that segfaulted when executing in Linux. But this section wouldn't", "r2 n'a pas planté sur aucun fichier. Lors de la tentative de débogage, il a rapporté"),
    ("exist if there were no problems with r2, would it? :)", "des segfaults des binaires qui faisaient un segfault lors de l'exécution sous Linux."),
    ("About a quarter of executables made r2 hang when just opening them for analysis", "Mais cette section n'existerait pas s'il n'y avait pas de problèmes avec r2, non ? :)"),
    ("with 100% CPU core usage.", "Environ un quart des exécutables ont fait planter r2 en le chargeant simplement pour l'analyse"),
    ("Further investigation included debugging r2 and some", "avec une utilisation de 100 % du CPU."),
    ("binary diffing,  and revealed that r2 got tangled up in the loop when trying to", "Une investigation plus approfondie comprenait le débogage de r2 et un"),
    ("locate  plt_addr  within .plt.got  in get_import_addr_x86_manual(), and  Melkor", "diffage binaire, et a révélé que r2 s'était emmêlé les pieds dans une boucle"),
    ("had created this section with reported size of 0x4242424258aebf0b.  In the file", "en essayant de localiser plt_addr dans .plt.got dans get_import_addr_x86_manual(),"),
    ("tested, r2 iterated from the start of .plt.got (0x10f0 in this case) about that", "et que Melkor avait créé cette section avec une taille signalée de 0x4242424258aebf0b."),
    ("many times:", "Dans le fichier testé, r2 a itéré à partir du début de .plt.got (0x10f0 dans ce cas) environ"),
    ("Notably, after about an eternity or  two  r2  would happily proceed to the next", "cette nombre de fois :"),
    ("step of binary analysis. Still, the bug is enough to prevent the analysis.", "(0x4242424258aebf0b — 0x10f0)/8 = 596806425961158083."),
    ("Despite iterating goes beyond the file size, there were no buffer overruns that", "Notamment, après une éternité ou deux, r2 passait heureusement à l'étape suivante"),
    ("in the end could result in the crash when exceeding the mapping, like it was in", "de l'analyse binaire. Néanmoins, le bug suffit à empêcher l'analyse."),
    ("the case of edb 'out-of-file' reads.  This was because the reading was done via", "Malgré le fait qu'itérer dépasse la taille du fichier, il n'y avait pas de"),
    ("r2 wrappers that are aware of the file size,  and  r2 just kept reading 0 bytes", "débordement de tampon pouvant résulter en un plantement en dépassant la cartographie,"),
    ("from the file buffer. This was also fixed and included in 5.8.4 release [18].", "comme dans le cas de la lecture 'hors fichier' d'edb. Cela était dû au fait que"),
    ("Finding bugs in parsers in fun.", "la lecture était effectuée via des wrappers r2 qui connaissent la taille du fichier,"),
    ("Finding bugs in  ELF parsers is even more fun,", "et r2 continuait à lire 0 octets du tampon de fichier. Cela a également été corrigé"),
    ("as it's the way to learn more about the ELF itself, about its loading, and also", "et inclus dans la version 5.8.4 [18]."),
    ("contribute to opensource and make things better!", "Trouver des bugs dans les analyseurs est amusant."),
    ("my respects to liveoverflow and corkami  (and the whole researchers community!)", "Trouver des bugs dans les analyseurs ELF est encore plus amusant,"),
    ("for sharing the knowledge, langsec guys for opening  my eyes to see parser bugs", "car c'est la façon d'apprendre davantage sur ELF lui-même, sur son chargement,"),
    ("from a different angle, and tmp.0ut crew for this amazing zine! :^)", "et aussi de contribuer à l'open source et d'améliorer les choses !"),
])

print("Batch 3 done: 13.html")
PYEOF