import re

def translate_file(src_path, dst_path, title_fr, line_translations):
    with open(src_path, 'r') as f:
        lines = f.readlines()
    
    # Replace title
    for i, line in enumerate(lines):
        if '<title>' in line:
            lines[i] = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', line)
    
    # Apply line-by-line translations
    for i, line in enumerate(lines):
        orig = line.rstrip('\n')
        if orig in line_translations:
            lines[i] = line_translations[orig] + '\n'
        else:
            # Try replacing substrings within the line
            for orig_str, trans_str in line_translations.items():
                if orig_str in orig and len(orig_str) > 10:
                    lines[i] = orig.replace(orig_str, trans_str) + '\n'
                    break
    
    content = ''.join(lines)
    
    credit = '[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {dst_path}")

# Build the translation dict mapping exact original lines to French
lines = {}

lines["<title>SPTH INTERVIEW</title>"] = "<title>ENTRETIEN AVEC SPTH</title>"
lines["                              SPTH INTERVIEW"] = "                              ENTRETIEN AVEC SPTH"

# Q1
lines["1.1 Q: Thank you for agreeing to be interviewed by us! Tell us a little"] = "1.1 Q: Merci d'avoir accepté d'être interviewé par nous ! Racontez-nous un peu"
lines["about yourself and your interests."] = "vous-même et vos centres d'intérêt."
lines["1.1.1 A: I am an old-school virus writer publishing stuff under the name Second"] = "1.1.1 A: Je suis un virus writer old-school publiant des trucs sous le nom Second"
lines["Part To Hell (<https://github.com/SPTHvx/>). In my early days (2002-2006), I"] = "Part To Hell (<https://github.com/SPTHvx/>). Dans mes débuts (2002-2006), j'étais"
lines["was a member of rRlf (we had several real-life meetings which was fun), and"] = "membre de rRlf (nous avons eu plusieurs réunions en présentiel ce qui était amusant), et"
lines["published a few things also in other zines such as 29a. After a break,"] = "j'ai publié quelques trucs aussi dans d'autres zines comme 29a. Après une pause,"
lines["from 2010-2014/2015 I worked closely with hh86 to get the Valhalla zines"] = "de 2010-2014/2015 j'ai travaillé en étroite collaboration avec hh86 pour lancer les zines Valhalla"
lines["running. I was active during that time mainly because of hh86’s constant"] = "La raison pour laquelle j'étais actif à cette époque était principalement la motivation constante"
lines["motivation and excitement. Then I  went silent in 2014 but published another"] = "et l'excitation d'hh86. Ensuite je suis parti silencieux en 2014 mais j'ai publié une autre"
lines["code that some liked a few months ago in 2023. I am mainly interested in fancy"] = "code que certains ont aimé quelques mois plus tôt en 2023. Je suis principalement intéressé par"
lines["proof-of-principle virus-related technologies, such as:"] = "des technologies virus liées aux preuves de principe, telles que :"
lines["  • New file-or programming language infections."] = "  • Infections de nouveaux fichiers ou langages de programmation."
lines["  For example, I hosted the Language Infection Project (LIP) from"] = "  Par exemple, j'ai hébergé le Language Infection Project (LIP) de"
lines["  2013-2016, intending to write a virus for all of the top 100"] = "  2013-2016, dans le but d'écrire un virus pour les 100 principaux"
lines["  programming languages. This was really exciting, it motivated the"] = "  langages de programmation. C'était vraiment passionnant, ça a motivé la"
lines["  community, and many people contributed new viruses to languages"] = "  communauté, et beaucoup de gens ont contribué avec de nouveaux virus pour des langages"
lines["  nobody would have thought to infect otherwise for decades."] = "  que personne n'aurait pensé à infecter autrement depuis des décennies."
lines["  Contributors among others were hh86 (Scilab, Falcon, and others),"] = "  Parmi les contributeurs figuraient hh86 (Scilab, Falcon, et autres),"
lines["  Genetix (Ocaml and Erlang were some weird functional programming"] = "  Genetix (Ocaml et Erlang étaient quelques langages de programmation fonctionnelle"
lines["  languages), herm1t (mySQL), TMZ contributed some codes infecting Vala,"] = "  bizarres), herm1t (mySQL), TMZ a contribué avec des codes infectant Vala,"
lines["  Google's Go and Nim binaries; and roy g biv, who invented an idea that"] = "  Google's Go and Nim binaries; and roy g biv, who invented an idea that"
lines["  made it very simple to infect more and more languages with the same"] = "  rendait très simple d'infecter de plus en plus de langues avec la même"
lines["  strategy, based on Quines (see Valhalla #4)."] = "  stratégie, basée sur des Quines (voir Valhalla #4)."
lines["  In my early days, I wrote the first boot sector virus for CD ROMs (rRlf#6),"] = "  Dans mes débuts, j'ai écrit le premier virus de secteur de démarrage pour CD ROMs (rRlf#6),"
lines["  the first Ruby viruses (29a#7) and the first infectors for Microsoft"] = "  les premiers virus Ruby (29a#7) et les premiers infecteurs pour Microsoft"
lines["  Infopath and F# (both in rRlf7)."] = "  Infopath et F# (tous deux dans rRlf7)."
lines[" Probably my personal favourite was my code which was able to infect"] = "Probablement mon code préféré personnel était celui qui pouvait infecter"
lines["DNA files via code (see Valhalla #4). It was spreading in the digital"] = "des fichiers ADN via du code (voir Valhalla #4). Il se propageait dans le monde numérique"
lines["world and was searching for .fasta files, which is a format in which"] = "et cherchait des fichiers .fasta, qui est un format dans lequel"
lines["genetic information is stored. The idea is: if my codes get into a lab"] = "les informations génétiques sont stockées. L'idée est : si mes codes arrivent dans un laboratoire"
lines["with access to in-cell DNA generation, such as those of Craig Venter"] = "avec accès à une génération d'ADN intra-cellulaire, comme ceux de Craig Venter"
lines["and others, then my code can wander from the digital to the biological"] = "et autres, alors mon code peut errer du monde numérique vers le monde biologique"
lines["world. New Code-Mutation techniques."] = "world. New Code-Mutation techniques."
lines["I tried to invent new types of code mutations. Potentially my 3"] = "J'ai essayé d'inventer de nouveaux types de mutations de code. Potentiellement mes 3"
lines["favourites were:"] = "favoris étaient :"
lines["a) Artificial Evolution in the W32 binary system, by employing ideas"] = "a) Evolution artificielle dans le système binaire W32, en employant des idées"
lines["from the field of Artificial Life (pioneered by Thomas S. Ray, and"] = "du domaine de la Vie Artificielle (pionnière par Thomas S. Ray, et"
lines["employed in awesome ways by Christof Adami and Richard Lenski), such"] = "exploité de manière étonnante par Christof Adami et Richard Lenski), de"
lines["that the file stays relatively robust under random mutations of the"] = "telle sorte que le fichier reste relativement robuste sous des mutations aléatoires du"
lines["binary code. This opens the possibility of collecting many mutations over"] = "code binaire. Cela ouvre la possibilité de collecter beaucoup de mutations sur"
lines["time, and potentially getting micro and later macro mutation"] = "le temps, et potentiellement d'obtenir des mutations micro et plus tard macro"
lines["modifications. Peter Ferrie wrote 3 texts in Virus Bulletin about it"] = "modifications. Peter Ferrie a écrit 3 textes dans Virus Bulletin à ce sujet"
lines["(called Flibi). Those texts and codes were published in hh86's virus"] = "(appelés Flibi). Ces textes et codes ont été publiés dans le bulletin"
lines["writing bulletin (which I call Valhalla #0) and Valhalla #1."] = "de virus d'hh86 (que j'appelle Valhalla #0) et Valhalla #1."
lines["b) First metamorphic script virus, in JavaScript. The idea was"] = "b) Premier virus script métamorphique, en JavaScript. L'idée était"
lines["developed after many discussions with herm1t, that metalanguages are"] = "développée après de nombreuses discussions avec herm1t, que les méta-langues sont"
lines["crucial. JS.Transcriptase carried its own metalanguage and compiler"] = "cruciales. JS.Transcriptase portait sa propre méta-langue et compilateur"
lines["from metalanguage to JavaScript. The compilation was highly"] = "de méta-langue vers JavaScript. La compilation était hautement"
lines["probabilistic. It was a pain to debug because some bugs could"] = "probabiliste. C'était une douleur à déboguer parce que certains bugs pouvaient"
lines["propagate to the 4th or 5th generation without being noticed. This was"] = "se propager à la 4e ou 5e génération sans être remarqués. C'était"
lines["probably my technologically most advanced code. that was published in"] = "probablement mon code le plus avancé techniquement. ça a été publié dans"
lines["Valhalla #3."] = "Valhalla #3."
lines["c) Metamorphism via GPT. GPT can translate language to code, so I can"] = "c) Métamorphisme via GPT. GPT peut traduire le langage en code, donc je peux"
lines["describe in a natural language a code, and get back a Python code. Now"] = "décrire en langage naturel un code, et obtenir du code Python en retour. Maintenant"
lines["I can make it such that the virus does not contain any viral Python"] = "je peux faire en sorte que le virus ne contienne aucun code Python viral,"
lines["code, but just English text that is sent to GPT, translated there to"] = "mais juste du texte anglais qui est envoyé à GPT, traduit là-bas en"
lines["Python, and in the end I run the compiled code from GPT. The cool"] = "Python, et à la fin j'exécute le code compilé de GPT. Le truc cool"
lines["thing is: GPT can make modifications to both the Python code, as well"] = "c'est que : GPT peut faire des modifications tant au code Python que"
lines["as the prompts themselves. That's beyond metamorphism and introduces the"] = "aux prompts eux-mêmes. C'est au-delà du métamorphisme et introduit le"
lines["new concept of language-morphism or linguisto-morphism (unfortunately,"] = "nouveau concept de language-morphism ou linguisto-morphism (malheureusement,"
lines["no one took up this concept and was happy with the GPT code mutation),"] = "personne n'a adopté ce concept et était content avec la mutation de code GPT),"
lines["but I think the language-mutation ability is much more crucial in the"] = "mais je pense que la capacité de mutation linguistique est beaucoup plus cruciale"
lines["long term. let's see. These ideas are published in the current tmp.0ut"] = "à long terme. voyons ce qui se passe. Ces idées sont publiées dans le tmp.0ut actuel"
lines["zine – thanks for giving them a nice place."] = "zine - merci de leur avoir donné une belle place."

# Q2
lines["1.2 Q: What do you currently do for work and hobbies? Still coding or working"] = "1.2 Q: Que faites-vous actuellement pour le travail et les loisirs ? Toujours coder ou travailler"
lines["with physics (I understand that this was your major)?"] = "avec la physique (je comprends que c'était votre spécialité) ?"
lines["1.2.1 A: I am a researcher mainly working with AI to understand the world. I"] = "1.2.1 A: Je suis un chercheur travaillant principalement avec l'IA pour comprendre le monde. J'aime"
lines["love to read about all sorts of natural sciences and math and intelligence"] = "lire à propos de toutes sortes de sciences naturelles, de mathématiques et d'intelligence"
lines["(human, artificial, swarm, emergent, ...); also I am a big fan of space."] = "(humaine, artificielle, essaim, émergente, ...); aussi je suis un grand fan de l'espace."

# Q3
lines["1.3 Q: LIP was one of the first times I released full"] = "1.3 Q: LIP était l'une des premières fois où j'ai publié"
lines["viruses. I guess I just want to say thank you for that, I've learned a lot"] = "des virus complets. Je crois que je veux juste dire merci pour cela, j'ai beaucoup appris"
lines["since then. What do you think about doing another version of it (or something"] = "depuis. Que pensez-vous de refaire une version (ou quelque chose de"
lines["similar) and what do you think about BGGP <https://tmpout.sh/bggp/3/>?"] = "similaire) et que pensez-vous de BGGP <https://tmpout.sh/bggp/3/> ?"
lines["1.3.1 A: Oh, I didn't know it was your first published file infector. Great to"] = "1.3.1 A: Oh, je ne savais pas que c'était votre premier infecteur de fichiers publié. Génial de"
lines["hear - 7 years later :). LIP was cool, it brought many people to play with new"] = "l'entendre - 7 ans plus tard :). LIP était sympa, ça a amené beaucoup de gens à jouer avec de nouveaux"
lines["languages. The design was good, and a top-100 list allowed for a big variation,"] = "langues. Le design était bon, et une liste top-100 a permis une grande variation,"
lines["you just chose one, learned a few days something new, and got your place at the"] = "vous choisissiez juste un, appreniez quelque chose de nouveau en quelques jours, et obteniez votre place à"
lines["\"Great Wall of LIP participations\". Total unexpected was roy g biv's"] = "\"Great Wall of LIP participations\". Le plus inattendu a été le"
lines["hyper-efficient way to kick out quine-based infectors. In Valhalla #4, he"] = "façon hyper-efficace de roy g biv pour éjecter les infecteurs basés sur des quines. Dans Valhalla #4,"
lines["published one text which infected 32 different languages! BGGP (with the goal"] = "il a publié un texte qui infectait 32 langues différentes ! BGGP (avec l'objectif de"
lines["of finding methods to crash pre-defined programs) sounds like a very interesting"] = "trouver des méthodes pour faire planter des programmes prédéfinis),"
lines["variation. The tasks sound more challenging than those for LIP and thus may"] = "sonne comme une variation très intéressante. Les tâches sonnent plus difficiles que celles pour LIP et donc,"
lines["not be directly applicable for newbies, also apparently it only ran for two"] = "peuvent ne pas être directement applicables aux débutants,"
lines["months. I need to go through the results - it's outside of my expertise, and"] = "et apparemment il n'a duré que deux mois. Je dois aller à travers les résultats - c'est en dehors de mon expertise,"
lines["I wouldn't know how to start."] = "je ne saurais pas par où commencer."

# Q4
lines["1.4 Q: Feels like just yesterday but LIP, discussing ideas on VXHeavens was"] = "1.4 Q: Ça fait presque hier que LIP, en discutant d'idées sur VXHeavens,"
lines["almost 10 years ago. Do you miss the scene?"] = "c'était presque 10 ans. Tu regrettes la scène ?"
lines["1.4.1 A: I enjoyed the time a lot, knowing that computers can be used in"] = "1.4.1 A: J'ai beaucoup aimé cette époque, savoir que les ordinateurs peuvent être utilisés de"
lines["highly unusual ways is an extremely valuable piece of information that I"] = "manières très inhabituelles est une information extrêmement précieuse que j'ai"
lines["collected over these years, and from which I benefit these days a lot. Meeting"] = "collecté pendant ces années, et dont je bénéficie beaucoup aujourd'hui. Rencontrer"
lines["(IRL or virtual) with many fun and creative people was certainly exciting. I"] = "(IRL ou virtuellement) avec beaucoup de gens amusants et créatifs a certainement été passionnant. J'ai"
lines["have great memories and do not miss it now. I stayed quiet for nearly 10 years"] = "de bons souvenirs et je ne le regrette pas maintenant. Je suis resté silencieux pendant près de 10 ans"
lines["as I had no good ideas for projects that needed to be done. Until February"] = "car je n'avais pas de bonnes idées pour des projets à faire. Jusqu'en février"
lines["2023 when I got access to the OpenAI's GPT APIs. There it was clear what had"] = "2023 quand j'ai eu accès aux API GPT d'OpenAI. Là, il était clair ce qu'il fallait faire."
lines["to be done."] = "à faire."
lines["So while I do not miss the scene, I am extremely happy and grateful"] = "Alors, même si je ne regrette pas la scène, je suis extrêmement heureux et reconnaissant"
lines["that a younger generation built the new library vx-underground and"] = "qu'une génération plus jeune a construit la nouvelle bibliothèque vx-underground"
lines["keep creating vx-zines such as tmp.0ut."] = "et continue de créer des zines vx comme tmp.0out."

# Q5
lines["1.5 Q: What made you decide to retire from the scene back then? How did it"] = "1.5 Q: Qu'est-ce qui vous a amené à prendre votre retraite de la scène à l'époque ? Comment"
lines["felt making this decision?"] = "ça s'est senti de prendre cette décision ?"
lines["1.5.1 A: I was mainly active because the collaboration of hh86 was highly"] = "1.5.1 A: J'étais principalement actif parce que la collaboration avec hh86 était hautement"
lines["productive and motivating. We used Google chat while coding; spending hours"] = "productive et motivating. Nous utilisions Google Chat pendant que nous codions; passant des heures"
lines["of decreasing the BugCount and thinking about the next awesome ideas and how"] = "à diminuer le BugCount et à réfléchir aux prochaines idées géniales et à la façon de"
lines["to make the next very best Valhalla issue. We wanted to push each issue to"] = "faire le prochain très bon numéro de Valhalla. Nous voulions pousser chaque numéro à"
lines["new extremes. For me valhalla#3, JS.Transcriptase was the most technologically"] = "de nouveaux extrêmes. Pour moi, valhalla#3, JS.Transcriptase était le plus techniquement"
lines["demanding code - it took ages to debug. I was only able to top that with a"] = "exigeant - ç'as pris des âges à déboguer. Je n'ai été capable de le surpasser que avec une"
lines["wild idea - infection of DNA in Valhalla #4 (Mycoplasma mycoides SPTH-syn1.0)."] = "idée folle - l'infection d'ADN dans Valhalla #4 (Mycoplasma mycoides SPTH-syn1.0)."
lines["After that, we talked several times about v5, but honestly, I didn't have"] = "Après ça, nous avons parlé plusieurs fois de v5, mais honnêtement, je n'avais pas"
lines["any idea how to top Transcripase and my DNA-infector SPTH-syn1.0 in"] = "d'idée de comment surpasser Transcripase et mon infecteur d'ADN SPTH-syn1.0"
lines["human-possible reasonable time."] = "dans un temps raisonnable possible pour un humain."
lines["Also, real life kicked in, and there I started to see how I could apply my"] = "Aussi, la vie réelle est entrée en jeu, et là, j'ai commencé à voir comment j'"
lines["abilities creatively IRL. I think similar things happened to hh86. I"] = "pouvais appliquer mes capacités créativement IRL. Je pense que des choses similaires sont"
lines["always told myself that I would write another code when I had another"] = "arrivées à hh86. Je me suis toujours dit que j'écrirais un autre code quand j'aurais"
lines["good idea. it took 10 years, but I think my GPT code indicates what"] = "une bonne idée. Ç'as pris 10 ans, mais je pense que mon code GPT indique ce"
lines["might be possible."] = "qui pourrait être possible."

# Q6
lines["1.6 Q: How do you see AI affecting computer viruses and general malware and"] = "1.6 Q: Comment voyez-vous l'IA affectant les virus informatiques et le malware général et"
lines["exploits in the future from the offensive and defensive perspective?"] = "les exploits à l'avenir du point de vue offensif et défensif ?"
lines["1.6.1 A: I have been wondering for ages how AI can be applied, I had several"] = "1.6.1 A: Je me suis beaucoup questionné sur la façon dont l'IA peut être appliquée, j'ai eu plusieurs"
lines["chats with herm1t about it - but never got any really good idea (besides my text"] = "discussions avec herm1t à ce sujet - mais je n'ai jamais eu vraiment d'idée (à part mon texte"
lines["in Valhalla #2 on \"Dynamic Anti-Emulation using Blackbox Analysis\", where a"] = "dans Valhalla #2 sur \"Dynamic Anti-Emulation using Blackbox Analysis\", où un"
lines["virus learns to memorize new anti-debugging tricks. but it was incredible"] = "virus apprends à mémoriser de nouveaux tricks anti-débogage. Mais c'était incroyablement"
lines["brittle.)"] = "fragile.)"
lines["Now time has changed. Large language models like GPT seem to make an"] = "Maintenant le temps a changé. Les modèles de langue comme GPT semblent faire un"
lines["enormous step towards some more general intelligent system. It allows"] = "bond important vers un système plus généralement intelligent. Ça permet"
lines["for the interaction between natural and computer language. At the"] = "l'interaction entre le langage naturel et informatique. Pour le"
lines["moment, these systems are still a bit unstable, so one needs to break"] = "moment, ces systèmes sont encore un peu instables, donc il faut casser"
lines["down code into micro-instructions. But imagine a few years from now"] = "le code en micro-instructions. Mais imaginez dans quelques années"
lines["when they create rock-solid codes for macro-instructions. Of course,"] = "quand ils créeront des codes roides pour des macro-instructions. Bien sûr,"
lines["OpenAI could restrict access to malicious systems - but training these"] = "OpenAI pourrait restreindre l'accès aux systèmes malveillants - mais l'entraînement de ces"
lines["systems will become significantly cheaper, and their memory"] = "systèmes deviendra beaucoup moins cher, et leur mémoire"
lines["requirement will be reduced."] = "sera réduite."
lines["At some point, a virus can carry its own trained LLM, trained without"] = "À un certain moment, un virus peut porter son propre LLM entraîné sans"
lines["restrictions. It may be the last VX technique that will ever be"] = "restrictions. Ça pourrait être la dernière technique VX qui sera jamais"
lines["invented."] = "inventée."
lines["I wonder whether this application destroys society before LLMs that"] = "Je me demande si cette application détruit la société avant les LLM qui"
lines["solve the new-age Turing test invented by DeepMind's Mustafa Suleyman"] = "résolvent le nouveau test de Turing inventé par Mustafa Suleyman de DeepMind"
lines["(a code that makes 1mio$ from 100k$). Or maybe some innovative defense"] = "(un code qui gagne 1M$ de 100k$). Ou peut-être qu'une entreprise de défense"
lines["company stores GPT5 in their war robots. Anyway - let's watch the race"] = "innovante stocke GPT5 dans leurs robots de guerre. Bref - regardons la course"
lines["about what goes wrong first :)\n"] = "à voir ce qui se passe en premier :)\n"

# Q7
lines["1.7 Q: One of your most interesting articles has to be \"Infecting Biological"] = "1.7 Q: L'un de vos articles les plus intéressants doit être \"Infecting Biological"
lines["DNA With Digital Computer Code\". I remember you had some worries about the"] = "DNA With Digital Computer Code\". Je me souviens que vous aviez des inquiétudes sur"
lines["misuse of such techniques. What are your current thoughts about this, also"] = "la mauvaise utilisation de ces techniques. Que pensez-vous actuellement de cela, aussi"
lines["considering AI as a factor here?"] = "en considérant l'IA comme un facteur ici ?"
lines["1.7.1 A: Thank you! I would love to see one of my codes being written in DNA"] = "1.7.1 A: Merci ! J'adorerais voir l'un de mes codes écrit en ADN"
lines["and copied into an E. coli genome one day. I mean - imagine that! ... But I think"] = "et copié dans un génome d'E. coli un jour. Je veux dire - imaginez ça ! ... Mais je pense"
lines["it is not as dangerous as other techniques at the moment. I trust that"] = "qu'aucune n'est aussi dangereuse que d'autres techniques pour le moment. J'ai confiance en"
lines["laboratories with the ability to write and encode DNA fragments into cell"] = "les laboratoires qui ont la capacité d'écrire et de coder des fragments d'ADN dans des cellules"
lines["genomes are highly secure. And the progress of research in that field seems"] = "sont très sécurisés. Et le progrès de la recherche dans ce domaine semble"
lines["to be significantly slower than for AI, so it's much better to predict what"] = "être significativement plus lent que pour l'IA, donc il est beaucoup plus facile de prédire ce"
lines["might happen and people have more time to prepare. I worry a bit about projects"] = "qui pourrait arriver et les gens ont plus de temps pour se préparer. Je m'inquiète un peu des projets"
lines["for the gain-of-function of biological viruses (which is related, as you write"] = "pour le gain de fonction des virus biologiques (ce qui est lié, car vous écrivez)"
lines["the DNA code in a computer) - I am not motivated to get infected by a super-HIV"] = "le code ADN dans un ordinateur) - je ne suis pas motivé pour être infecté par un super-HIV)"
lines["or Ebola bug."] = "ou un bug Ebola."
lines["Oh - btw there is one thing that is missing. So far we have:"] = "Oh - au fait, il y a un truc manquant. Jusqu'ici, nous avons :"
lines["bio -> bio infection: Since 4 billion years ago due to Evolution"] = "bio -> bio infection : Depuis 4 milliards d'années due à l'Évolution"
lines["digital -> digital infection: in the 1980s by Rich Skrenta (Elk Cloner), Amjad"] = "digital -> digital infection : dans les années 1980 par Rich Skrenta (Elk Cloner), Amjad"
lines["and Basit Farooq Alvi (Brain), and many other"] = "et Basit Farooq Alvi (Brain), et beaucoup d'autres"
lines["heroes."] = "héros."
lines["digital -> bio infection: 2013 by me (Mycoplasma mycoides SPTH-syn1.0)"] = "digital -> bio infection : 2013 par moi (Mycoplasma mycoides SPTH-syn1.0)"
lines["bio -> digital infection: noone yet (you?)"] = "bio -> digital infection : personne encore (toi ?)"
lines["Let me know if you find out how to do it. I will invite you for"] = "Faites-moi savoir si vous découvrez comment faire. Je vous invite pour"
lines["beer&whiskey.\n"] = "beer&whiskey.\n"

# Q8
lines["1.8 Q: What do you think about modern malware and in which ways do you think"] = "1.8 Q: Que pensez-vous du malware moderne et de quelles manières pensez-vous que"
lines["malware has changed since the last decade?"] = "le malware a changé depuis la dernière décennie ?"
lines["1.8.1 A: I didn't follow the developments too much; what I see on Twitter and"] = "1.8.1 A: Je n'ai pas suivi les développements trop longtemps; ce que je vois sur Twitter et"
lines["tmp.0ut are very cool technological ideas. However, I was never good at"] = "tmp.0ut sont des idées technologiques super cool. Cependant, je n'étais jamais bon pour"
lines["super-fancy technology (in contrast to ppl like hh86, roy g biv, or herm1t), thus"] = "la technologie super-fancy (contrairement à des gens comme hh86, roy g biv, ou herm1t), donc"
lines["I fear I cannot appreciate them without further context. I usually"] = "j'ai peur de ne pas pouvoir les apprécier sans plus de contexte. J'aime habituellement"
lines["enjoy simple ideas so it seems I am a bit rusty in giving a well-informed"] = "des idées simples donc il semble que je sois un peu rouillé pour donner une réponse bien informée"
lines["answer here. That said: If you have developed some fancy unexpected"] = "ici. Cela dit : Si vous avez développé une technique fancy inattendue"
lines["code-mutation technique, or infected some cool new target, please write me an"] = "de mutation de code, ou infecté une nouvelle cible sympa, veuillez m'écrire un"
lines["email with the text/code and a one-sentence dummy explanation :)\n"] = "email avec le texte/code et une explication d'une phrase :)\n"

# Q9
lines["1.9 Q: You mentioned once that hh86 and roy g biv were collective pseudonyms."] = "1.9 Q: Vous avez dit un jour que hh86 et roy g biv étaient des pseudonymes collectifs."
lines["Would you be comfortable on shedding some light on this?"] = "Seriez-vous à l'aise de révéler un peu plus à ce sujet ?"
lines["1.9.1 A: Oh, yes I wrote that - I think it's not true. hh86 suggested to make"] = "1.9.1 A: Oh, oui j'ai écrit ça - je pense que c'est pas vrai. hh86 a suggéré de faire"
lines["this joke, and I believe for roy g biv, this rumor was around for some time"] = "cette blague, et je crois que pour roy g biv, cette rumeur a circulé pendant un certain temps"
lines["(probably because of his enormous productivity over decades)."] = "(probablement à cause de sa productivité énorme sur plusieurs décennies)."
lines["All I know, hh86 and roy g biv were two enormously gifted vxers, two"] = "Tout ce que je sais, hh86 et roy g biv étaient deux vxers incroyablement doués, deux"
lines["of the best and most productive in the vx history. I mostly had"] = "des meilleurs et plus productifs de l'histoire du vx. J'ai surtout eu"
lines["contact with them via mail and Google chat, so who knows? Well - for"] = "contact avec eux via mail et Google Chat, alors qui sait ? Bien - pour"
lines["hh86, I also sent two letters IRL. One with Carl Sagan's book Contact,"] = "hh86, j'ai aussi envoyé deux lettres IRL. Une avec le livre Contact de Carl Sagan,"
lines["and the other with a printed version of Peter Ferrie's pre-publication"] = "et l'autre avec une version imprimée du draft pré-publication de Peter Ferrie"
lines["draft of the first Flibi article.\n"] = "du premier article Flibi.\n"

# Q10
lines["1.10 Q: What are some of your favorite viruses and/or authors and people from"] = "1.10 Q: Lequel de vos virus préférés et/ou auteurs et gens de"
lines["the scene?"] = "la scène ?"
lines["1.10.1 A: Woa so many!"] = "1.10.1 A: Woa tellement de gens !"
lines["MTE by Dark Avenger."] = "MTE par Dark Avenger."
lines["Must be on every list number one. No one must forget our prophet!"] = "Doit être sur toutes les listes en premier. Personne ne doit oublier notre prophète !"
lines["Regswap, MetaPHOR, ZMist by the Popes of Metamorphism in the late"] = "Regswap, MetaPHOR, ZMist par les Popes of Metamorphism à la fin des années"
lines["90s/early 2000s: Vecna, The Mental Driller, Z0MBiE. (in 29a#4,"] = "90/2000 : Vecna, The Mental Driller, Z0MBiE. (dans 29a#4,"
lines["29a#6, 29a#6, respectively)"] = "29a#6, 29a#6, respectivement)"
lines["Benny's Linux-Windows cross-infector Winux"] = "Winux, l'infecteur croisé Linux-Windows de Benny"
lines["Masterpiece in 29a #6, infects PE/ELF files. Benny was super skilled"] = "Chef-d'œuvre dans 29a #6, infecte des fichiers PE/ELF. Benny était super qualifié"
lines["and creative to go new paths."] = "et créatif pour aller sur de nouveaux chemins."
lines["Apparition by LordAsd (in 29a#3)"] = "Apparition par LordAsd (dans 29a#3)"
lines["Carries its own C++ source code and relied on a C++ compiler to create"] = "Porte son propre code source C++ et s'appuyait sur un compilateur C++ pour créer"
lines["new metamorphic versions of itself."] = "de nouvelles versions métamorphiques de lui-même."
lines["New Virus Virus Generation Kit by SnakeByte"] = "New Virus Virus Generation Kit par SnakeByte"
lines["A beautiful powerful tool that produced highly sophisticated assembler"] = "Un bel outil puissant qui produisait des assembleurs très sophistiqués de"
lines["codes of custom-made win32 viruses. Highly variable code generator,"] = "codes de virus win32 personnalisés. Générateur de code hautement variable,"
lines["which made detection enormously difficult. Was one of the first"] = "qui rendait la détection extrêmement difficile. C'était un des premiers"
lines["advanced VX tools I saw, the main motivation for my first tool, BWG"] = "outils VX avancés que j'ai vus, la motivation principale pour mon premier outil, BWG"
lines["(Batch Worm Generator)."] = "(Batch Worm Generator)."
lines["Caribe by Vallez/29A"] = "Caribe par Vallez/29A"
lines["First infector for mobile phones via BlueTooth. (in 29a #8)"] = "Premier infecteur pour téléphones mobiles via BlueTooth. (dans 29a #8)"
lines["jackie's tutorials on very fancy script techniques, e.g. javascript"] = "Tutoriels de jackie sur des techniques de script très fancy, par ex. javascript"
lines["and macro viruses."] = "et virus macro."
lines["Big inspiration when I started, especially as he lived in Austria too."] = "Grande inspiration quand j'ai commencé, surtout qu'il vivait aussi en Autriche."
lines["Win32 assembly tutorials by vorgon/iKx"] = "Tutoriels d'assembleur Win32 par vorgon/iKx"
lines["Must be around 2004, I learned assembler with them, and vorgon was one"] = "Doit être autour de 2004, j'apprenais l'assembleur avec eux, et vorgon était un"
lines["of the nicest vxers I ever met. he spent hours and hours in IRC (or"] = "des vxers les plus sympas que j'aie rencontré. Il passait des heures et des heures sur IRC (ou"
lines["MSN Messenger?) with me, explaining me everything. A complete hero!"] = "MSN Messenger ?) avec moi, m'expliquant tout. Un héros complet !"
lines["roy g biv's work; so many!"] = "Le travail de roy g biv; tellement de choses !"
lines["rgb pioneered for 20 years or more, James Cook of VXing. Win64"] = "rgb a pionnier pour 20 ans ou plus, James Cook du VXing. Win64"
lines["conquered. A quine technique that can easily infect 32 different"] = "vaincu. Une technique de quine qui peut facilement infecter 32 langues différentes"
lines["programming languages. High-Tech Windows tricks (heaven's gate in"] = "de programmation. Astuces Windows High-Tech (heaven's gate dans"
lines["Valhalla #1) which I wish I would understand but can confirm that they"] = "Valhalla #1) que j'aimerais comprendre mais que je peux confirmer qu'elles"
lines["are awesome by hh86's judgement :)"] = "sont géniales selon le jugement de hh86 :)"
lines["philet0ast3r & DiA"] = "philet0ast3r & DiA"
lines["Philet0ast3r was founder and leader of rRlf, DiA was one of the most"] = "Philet0ast3r était le fondateur et leader de rRlf, DiA était l'un des plus"
lines["active members and zine-editor. I joined rRlf very early (similar time"] = "membres actifs et zine-editor. Je me suis joint à rRlf très tôt (à peu près à la même époque"
lines["as DiA), I was a newby but because of the motivation was motivated to"] = "quoi que DiA), j'étais un newby mais à cause de la motivation j'étais motivé pour"
lines["learn quickly. Without these two guys, I would likely not have"] = "apprendre vite. Sans ces deux gars, je n'aurais probablement pas"
lines["continued to push. Also met DiA and philet0ast3r at least 3 times IRL,"] = "continué. J'ai aussi rencontré DiA et philet0ast3r au moins 3 fois IRL,"
lines["maybe more often - memories are blurred because of strong alcohol (I"] = "peut-être plus souvent - les souvenirs sont flous à cause de l'alcool fort (je"
lines["used to bring one or more bottles of 80% KORN)."] = "apportais une ou plusieurs bouteilles de KORN à 80%)."
lines["DiA's Tamiami Worm (in rRlf#7)"] = "Le ver Tamiami de DiA (dans rRlf#7)"
lines["DiA was a hell of a vxer who created one of my all time favorite"] = "DiA était un enfer de vxer qui a créé l'un de mes codes préférés de tous les temps"
lines["codes: it had its own HTTP server, and creates a fake website using"] = "il avait son propre serveur HTTP, et créait un site web faux en utilisant"
lines["images from the computer. To download the full pictures of the images,"] = "des images de l'ordinateur. Pour télécharger les images complètes,"
lines["you can download a .zip file, which contained the virus. I executed it"] = "vous pouvez télécharger un fichier .zip, qui contenait le virus. Je l'ai exécuté"
lines["on my own computer - it worked amazingly!"] = "sur mon propre ordinateur - ça a marché incroyablement bien !"
lines["herm1t's ideas and VX Heavens"] = "Les idées de herm1t et VX Heavens"
lines["VX Heavens was our library in the old times, kept alive by herm1t."] = "VX Heavens était notre bibliothèque dans les vieux temps, gardée en vie par herm1t."
lines["Herm1t is also an amazing coder, highly skilled and interested in"] = "Herm1t est aussi un codeur incroyable, hautement qualifié et intéressé par"
lines["using meta-languages for EPO and mutation tricks (see herm1t's metamorphic"] = "l'utilisation de méta-langues pour les tricks EPO et de mutation (voir le virus"
lines["Linux virus Linux.Lacrimae in EOF #2 and his article \"Recompiling the"] = "Linux.Lacrimae de herm1t dans EOF #2 et son article \"Recompiling the"
lines["Metamorphism\" in Valhalla #2). Many exciting discussions about all sort"] = "Metamorphism\" dans Valhalla #2). Beaucoup de discussions passionnantes sur"
lines["of VX tech, such as AI for viruses before AlexNet :)."] = "toute sorte de technologies VX, comme l'IA pour les virus avant AlexNet :)."
lines["Eric Filiol's amazing theory articles"] = "Les articles théoriques incroyables d'Eric Filiol"
lines["The text \"From the design of a generic metamorphic engine to a"] = "Le texte \"From the design of a generic metamorphic engine to a"
lines["black-box classification of antivirus detection techniques\" introduces"] = "black-box classification of antivirus detection techniques\" introduit"
lines["the idea of tau-obfuscation which is an incredible anti-debugging"] = "l'idée de tau-obfuscation qui est un trick anti-débogage incroyable"
lines["trick which I wouldn't know how to overcome. (I used this idea in"] = "que je ne saurais pas dépasser. (J'ai utilisé cette idée dans)"
lines["Matlab.MicrophoneFever2 in Valhalla #1). His idea of \"Metamorphism,"] = "Matlab.MicrophoneFever2 dans Valhalla #1). Son idée de \"Metamorphism,"
lines["Formal grammars and Undecidable Code Mutation\" was extremely"] = "Formal grammars and Undecidable Code Mutation\" était extrêmement"
lines["inspiring, because of this article, I took a full course on"] = "inspirant, parce que de cet article, j'ai suivi un cours complet sur)"
lines["theoretical computer science - just to understand wtf Eric is talking"] = "les sciences informatiques théoriques - juste pour comprendre ce que Eric"
lines["about. Was worth it, I use these ideas in some of my work these days"] = "parle. Ça valait le coup, j'utilise ces idées dans mon travail aujourd'hui)"
lines[":)"] = ":)"
lines["Qozah - \"Polymorphism and Grammars\", 29A#4"] = "Qozah - \"Polymorphism and Grammars\", 29A#4"
lines["First usage of formal grammar to analyse code mutation. A breakthrough"] = "Première utilisation de la grammaire formelle pour analyser la mutation de code. Un"
lines["idea!"] = "idée !"
lines["Mark Stamp's statistical AV techniques and countermeasures."] = "Techniques statistiques AV et contre-mesures de Mark Stamp."
lines["Mark Stamp's analysed JS.Transcriptase (my complex metamorphic virus)"] = "Mark Stamp a analysé JS.Transcriptase (mon virus métamorphique complexe)"
lines["and round-house kicked it using statistical methods (\"Hunting for"] = "et l'a défoncé avec des méthodes statistiques (\"Hunting for)"
lines["metamorphic JavaScript malware\" by M Musale, TH Austin, M Stamp)."] = "metamorphic JavaScript malware\" par M Musale, TH Austin, M Stamp)."
lines["Another student then took up the project and implemented defence"] = "Un autre étudiant a ensuite repris le projet et implémenté des)"
lines["methods into JS.Transcriptase (\"Advanced transcriptase for JavaScript"] = "méthodes dans JS.Transcriptase (\"Advanced transcriptase for JavaScript)"
lines["malware\", Fabio Di Troia; Corrado Aaron Visaggio; Thomas H. Austin;"] = "malware\", Fabio Di Troia; Corrado Aaron Visaggio; Thomas H. Austin;)"
lines["Mark Stamp)."] = "Mark Stamp)."
lines["JPanic - CAPZLOQ 2.0 in valhalla#4"] = "JPanic - CAPZLOQ 2.0 dans valhalla#4"
lines["CAPZLOQ infects Win32 PE, Linux i386 ELF, i386 Macho (OS X"] = "CAPZLOQ infecte Win32 PE, Linux i386 ELF, i386 Macho (OS X)"
lines["Executable/Linkable) and FAT (OS X Universal Binary) files. The virus"] = "Executable/Linkable) et FAT (OS X Universal Binary) fichiers. Le virus)"
lines["runs under x86-32bit (i386) Windows, Linux, and Mac OS X. (!!)"] = "fonctionne sous Windows x86-32bit (i386), Linux, et Mac OS X. (!!)"
lines["JPanic planned to extend it to Linux64 (see his tutorial in Valhalla #4), but"] = "JPanic a prévu de l'étendre à Linux64 (voir son tutoriel dans Valhalla #4), mais)"
lines["did not have enough time to finish it..."] = "n'a pas eu assez de temps pour le finir..."
lines["smelly - the organizer of vx underground, our new Library of"] = "smelly - l'organisateur de vx underground, notre nouvelle Bibliothèque de"
lines["Alexandria! Thanks so much, and congratulations on this amazingly"] = "Alexandrie ! Merci beaucoup, et félicitations pour ce projet )"
lines["well-organized project!"] = "incroyablement bien organisé !"
lines["TMZ - organizing tmp.0ut, a high-tech vx/hacking ezine that is still"] = "TMZ - organisant tmp.0ut, un ezine vx/hacking haute technologie qui est toujours"
lines["going strong. Congratulations and thanks for the interview!"] = "très actif. Félicitations et merci pour l'interview !"
lines["Peter Ferrie – Wonderful analyses of our works; very clever"] = "Peter Ferrie - Des analyses merveilleuses de nos travaux; des)"
lines["extensions of some of the ideas at a conceptual level (smallest"] = "extensions très intelligentes de certaines des idées au niveau conceptuel (alphabet le plus petit)"
lines["alphabet for mutationally robust codes, see Flibi2 in VirusBulletin)."] = "pour les codes mutent-robustes, voir Flibi2 dans VirusBulletin)."
lines["Mikko Hypponen – One nice virus researcher. One of the few"] = "Mikko Hypponen - Un chercheur de virus sympa. L'un des rares)"
lines["who took my DNA infector at least remotely seriously. Same with my GPT"] = "qui a pris mon infecteur d'ADN au moins à distance au sérieux. Même chose avec mon GPT )"
lines["mutation engine. Thanks. Oh, if you haven't seen it, check out the"] = "moteur de mutation. Merci. Oh, si vous ne l'avez pas vu, vérifiez la )"
lines["video where he goes to Pakistan and meets the inventors of Brain"] = "vidéo où il va au Pakistan et rencontre les inventeurs de Brain )"
lines["(first PC virus). Thats amazing."] = "(premier virus PC). C'est incroyable."
lines["hh86 – Last but not least. One of the most skilled, productive, and"] = "hh86 - Pour ne pas dire la dernière. L'un des plus qualifiés, productifs et )"
lines["motivating vxers. hh86 is responsible that I didn't back to sleep"] = "motivants vxers. hh86 est responsable du fait que je ne suis pas retourné dormir )"
lines["after publishing my Artificial Evolution article in 2010. Rather, she"] = "après avoir publié mon article Evolution artificielle en 2010. Plutôt, elle )"
lines["made me (and others such as roy g biv, JPanic, and herm1t) contribute"] = "m'a fait (et d'autres comme roy g biv, JPanic, et herm1t) contribuer )"
lines["heavily to 5 magazine issues of her Valhalla e-zine (valhalla#0-#4). I"] = "fortement à 5 numéros de magazine de son e-zine Valhalla (valhalla#0-#4). J'ai )"
lines["published most of my best codes there - that means they only exist"] = "publié la plupart de mes meilleurs codes là - ça veut dire qu'ils n'existent )"
lines["because of hh86. She wrote amazing codes of very high skill level,"] = "que par hh86. Elle a écrit des codes incroyables de très haut niveau,)"
lines["examples are codes that use CUDA and GPUs for virus cryptography and"] = "exemples sont des codes qui utilisent CUDA et GPU pour la cryptographie de virus et )"
lines["infection, Java Bytecode viruses, Win32-Win64 cross infector"] = "l'infection, des virus Bytecode Java, un infecteur croisé Win32-Win64 )"
lines["(W48.Sofia!) and many many more."] = "(W48.Sofia !) et beaucoup d'autres."
lines["Best greetz to many others that were nice and skilled such as perforin"] = "Les meilleures salutations à beaucoup d'autres personnes sympas et qualifiées comme perforin"
lines["(who hosted my website for a long time), kefi, BlueOwl (both rRlf),"] = "(qui a hébergé mon site web pour longtemps), kefi, BlueOwl (les deux rRlf),"
lines["malfunction, Belial, genetix, promix, wargame, slagehammer, dahmer,"] = "malfunction, Belial, genetix, promix, wargame, slagehammer, dahmer,"
lines["r3s1stanc3, Luca, alcopaul, cyneox, ..."] = "r3s1stanc3, Luca, alcopaul, cyneox, ..."
lines["1.12 Q: This space is reserved for you SPTH, feel free to say anything you wish."] = "1.12 Q: Cet espace est réservé pour vous SPTH, dites-nous tout ce que vous voulez."

translate_file('/home/ubuntu/tmpout-fr/3/02.html', '/home/ubuntu/tmpout-fr/3/fr/02.html',
    'ENTRETIEN AVEC SPTH', lines)

print("02.html translation complete")
