#!/usr/bin/env python3
import re
import os

def translate_file(src_path, dst_path, title_fr, translations):
    with open(src_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', content)
    
    for orig, trans in translations:
        content = content.replace(orig, trans)
    
    credit = '\n[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    elif '</pre></div>' in content:
        content = content.replace('</pre></div>', credit + '</pre></div>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {os.path.basename(src_path)}")

# 12.html - u used 2 call me on my polymorphic shell phone
translate_file('/home/ubuntu/tmpout-fr/3/12.html', '/home/ubuntu/tmpout-fr/3/fr/12.html',
    'tu m’appelais sur mon téléphone à coquilles polymorphes', [
    ("u used 2 call me on my polymorphic shell phone", "tu m'appelais sur mon téléphone à coquilles polymorphes"),
    ("pt. 1: gospel for a new epoch [tales from the crypt", "pt. 1 : gospel pour une nouvelle ère [récits du cimetière"),
    ("virus archaeology and its applications to modern vx]", "archéologie des virus et ses applications au vx moderne]"),
    ("note: the title of this article is a reference to Yves Tumor's", "note : le titre de cet article est une référence à l'album"),
    ("earth-shatteringly brilliant 2020 album", "remarquablement brillant de 2020 de Yves Tumor"),
    ("and the album's track which bears the same name as this article,", "et le morceau de l'album qui porte le même nom que cet article,"),
    ("caveat s/epoch/century]", "avec la remarque s/epoch/century]"),
    ("TOC", "TABLE DES MATIÈRES"),
    ("Introduction", "Introduction"),
    ("VX PoC/article roadmap and goals", "Feuille de route PoC/vx et objectifs"),
    ("Part 1: For this evening's entertainment, a virus' evolution in 7 acts!", "Partie 1 : Pour le divertissement de cette soirée, l'évolution d'un virus en 7 actes !"),
    ("Part 2: Silvio Cesare's Unix VX techniques", "Partie 2 : Techniques VX Unix de Silvio Cesare"),
    ("Part 2a. Text segment padding infection", "Partie 2a. Infection par remplissage de segment texte"),
    ("Part 2b: Linux virus requirements breakdown", "Partie 2b : Analyse des exigences du virus Linux"),
    ("Part 2c: Infection algorithm implementation", "Partie 2c : Implémentation de l'algorithme d'infection"),
    ("Part 2d: PoC", "Partie 2d : Preuve de concept (PoC)"),
    ("Part 2e: Reflections", "Partie 2e : Réflexions"),
    ("Part 3: A squeeze of LiME", "Partie 3 : Une touche de LiME"),
    ("A toast to new beginnings", "Un toast aux nouveaux débuts"),
    ("Party favors", "Cadeaux de fête"),
    ("Greetz", "Salutations"),
    ("References", "Références"),
    ("Like da Vinci, I am predisposed to visiting morgues and studying the corpses for ", "Comme da Vinci, je suis enclin à visiter les morgues et à étudier les corps pour "),
    ("my anatomical studies.", "mes études anatomiques."),
    ("Yes, dear reader, da Vinci was a goth baddie who snuck", "Oui, cher lecteur, da Vinci était un dark type qui s'infiltrait"),
    ("into Italian morgues so he could practice anatomical drawings with models who", "dans les morgues italiennes pour pouvoir pratiquer des dessins anatomiques avec des modèles qui"),
    ("would stay still.) We're taking a page out of his book,", "restaient immobiles.) Nous empruntons une page de son livre,"),
    ("so to speak. However,", "pour ainsi dire. Cependant,"),
    ("in my case, and for the collective sigh of relief for all readers here,", "dans mon cas, et pour le soupir collectif de soulagement de tous les lecteurs ici,"),
    ("we can", "nous pouvons"),
    ("recuse ourselves from any notion of being accessories to a crime,", "nous absoudre de toute idée d'être complices d'un crime,"),
    ("since the", "puisque les"),
    ("corpses we're excavating will be those of Unix vx of days past.", "corps que nous exhumons seront ceux du vx Unix d'autrefois."),
    ("The careful reader will note that referring to the work of such foundational", "Le lecteur attentif notera que faire référence au travail de ces"),
    ("Unix/ELF vx grandmasters (do we have a better term for this? Legends?", "grands-maîtres du vx Unix/ELF (avons-nous un meilleur terme pour cela ? Des légendes ?"),
    ("1337 royalty? Another moniker that isn't so dreadfully gauche? Please call in with", "1337 royalty ? Un autre surnom qui n'est pas si maladroit ? Appelez avec"),
    ("your suggestions, operators are standing by.) as \"corpses\" is a rhetorical", "vos suggestions, les opérateurs sont en attente.) comme « corps » est une technique rhétorique"),
    ("technique used to set the scene.", "utilisée pour établir le décor."),
    ("These \"corpses\" are alive+well, relevant,", "Ces « corps » sont vivants et bien, pertinents,"),
    ("well-written and brilliant;", "bien écrits et brillants ;"),
    ("we're going to shine a spotlight on the work of a few notable authors of early Linux vx.", "nous allons mettre en avant le travail de quelques auteurs notables du vx Linux d'antan."),
    ("This article is the first in a series where I'll be revisiting classic Linux vx ", "Cet article est le premier d'une série où je revisite les techniques classiques de vx Linux "),
    ("techniques and adapting them for targeting modern systems.", "et les adapte pour cibler les systèmes modernes."),
    ("Why?", "Pourquoi ?"),
    ("Know your history, bb!", "Connais ton histoire, bb !"),
    ("Or to put it more formally,", "Ou pour le dire plus formellement,"),
    ("our goals will be two-fold", "nos objectifs seront doubles"),
    ("First, from a theoretical perspective it's important to know your history.", "Premièrement, du point de vue théorique, il est important de connaître son histoire."),
    ("This is all well and good,", "C'est bien et bon,"),
    ("but we want to write interesting viruses *now.*", "mais nous voulons écrire des virus intéressants *maintenant.*"),
    ("So, secondly,", "Donc, deuxièmement,"),
    ("from a practical perspective,", "du point de vue pratique,"),
    ("as will be demonstrated by the", "comme le démontrera"),
    ("author of our first Unix vx archaeological study,", "l'auteur de notre première étude archéologique de vx Unix,"),
    ("sometimes you want to look", "parfois, vous voulez regarder"),
    ("*backwards* [in an ELF text segment as a means of locating a region to inject a", "*en arrière* [dans un segment texte ELF comme moyen de localiser une région pour injecter un"),
    ("virus], and sometimes you want to look *forward.*", "virus], et parfois, vous voulez regarder *en avant.*"),
    ("And sometimes,", "Et parfois,"),
    ("you can do interesting things by doing both.", "vous pouvez faire des choses intéressantes en faisant les deux."),
    ("So that is what we will do here.", "C'est ce que nous allons faire ici."),
    ("We are going to be looking backwards and", "Nous allons regarder en arrière et"),
    ("forwards in rapid succession and at the end of it,", "en avant en succession rapide et à la fin de cela,"),
    ("we'll have a Linux virus", "nous aurons un virus Linux"),
    ("(or 2... or 3...) to write home about.", "(ou 2... ou 3...) à sevanter."),
    ("As such,", "En conséquence,"),
    ("I advise you to do some light", "Je vous conseille de faire quelque stretching"),
    ("stretching beforehand to avoid sustaining a whiplash injury.", "au préalable pour éviter de vous torse-braser."),
    ("Ready?", "Prêt ?"),
    ("Let's begin.", "Commençons."),
    ("I've been digging up skeletons of Unix vx with the following goals:", "J'ai été exhumer des squelettes de vx Unix avec les objectifs suivants :"),
    ("Adapt early *nix vx techniques to write modern Linux viruses (all written", "Adapter les techniques de vx *nix anciennes pour écrire des virus Linux modernes (tous écrits"),
    ("in assembly, of course) and use those viruses to make art with a variety", "en assembleur, bien sûr) et utiliser ces virus pour créer de l'art avec une variété"),
    ("of low-level graphics programming constructs.", "de structures de programmation graphique de bas niveau."),
    ("Provide a roadmap for you to adapt early *nix vx techniques in your own", "Fournir une feuille de route pour que vous puissiez adapter les techniques de vx"),
    ("modern Linux vx writing.", "de vx Linux moderne dans votre propre écriture."),
    ("This article is structured into three parts,", "Cet article est structuré en trois parties,"),
    ("outlined here.", "définies ici."),
    ("In part 1,", "Dans la partie 1,"),
    ("to set the stage for our first archaeological study,", "pour établir le décor de notre première étude archéologique,"),
    ("I'll discuss the", "j'discute le"),
    ("work of several authors of early Linux vx -- sourced from the 29a zine archives,", "travail de plusieurs auteurs de vx Linux ancien -- extrait des archives du zine 29a,"),
    ("currently hosted on VX-Underground.", "actuellement hébergé sur VX-Underground."),
    ("In part 2 we'll dive into the work of Silvio Cesare (silvio) whose articles", "Dans la partie 2, nous plongeons dans le travail de Silvio Cesare (silvio) dont les articles"),
    ("\"UNIX ELF Parasites and virus\"[1] and \"UNIX Viruses\"[2], function as our", "\"\nUNIX ELF Parasites and virus\"[1] et \"UNIX Viruses\"[2] servent de"),
    ("foundational holy scripture in crafting gnarly Linux vx.", "sacre du saint-écrit fondamental dans la création de vx Linux."),
    ("All hail silvio. Amen.", "Tous honneurs à silvio. Amen."),
    ("I'll focus primarily on one of the four techniques introduced in silvio's", "J'me concentrerai principalement sur une des quatre techniques introduites dans les"),
    ("papers:", "papiers de silvio :"),
    ("the text segment padding infection technique.", "la technique d'infection par remplissage de segment texte."),
    ("I'll walk through the", "Je vais détailler"),
    ("details of the virus' algorithm,", "les détails de l'algorithme du virus,"),
    ("along with code snippets from my PoC,", "avec des extraits de code de mon PoC,"),
    ("and discuss design choices and potential challenges of implementing this ELF virus", "et discuter des choix de conception et des défis potentiels de la mise en œuvre de cette technique de virus ELF"),
    ("technique.", "technique."),
    ("This article is accompanied by the complete source code for my PoC virus", "Cet article est accompagné du code source complet de mon virus PoC"),
    ("\"gospel\", written in x86-64 asm,", "\"gospel\", écrit en asm x86-64,"),
    ("which implements Silvio's text segment padding", "qui implémente la technique de remplissage de segment texte de Silvio"),
    ("infection technique to infect x86-64 ELF PIE binaries on a modern Linux host.", "pour infecter des binaires ELF PIE x86-64 sur un hôte Linux moderne."),
    ("In part 3 of this article,", "Dans la partie 3 de cet article,"),
    ("I'll provide an introduction to polymorphism,", "je fournirai une introduction au polymorphisme,"),
    ("and build on the techniques covered in parts 1 and 2.", "et jappuie sur les techniques couvertes dans les parties 1 et 2."),
    ("I'll discuss several works", "Je discuterai de plusieurs travaux"),
    ("of early *nix vx that used polymorphism (and metamorphism).", "de vx *nix ancien qui utilisaient le polymorphisme (et la métamorphisme)."),
    ("Using these works", "En utilisant ces travaux"),
    ("as a guide,", "comme guide,"),
    ("I'll walk through my implementation of a polymorphic version of", "je détaillerai ma mise en œuvre d'une version polymorphe de"),
    ("gospel.", "gospel."),
    ("Part 3 in its entirety will be in a future tmp.0ut volume,", "La partie 3 dans son ensemble sera dans un futur volume de tmp.0ut,"),
    ("but stay", "mais restez"),
    ("tuned until the end of the article for a fun sneak peek!", "branchés jusqu'à la fin de l'article pour un aperçu amusant !"),
    ("Let's get to writing our Linux vx, shall we?", "Allons-y pour écrire notre vx Linux, d'accord ?"),
    ("Part 1: For this evening's entertainment,", "Partie 1 : Pour le divertissement de cette soirée,"),
    ("a virus' evolution in 7 acts!", "l'évolution d'un virus en 7 actes !"),
    ("I've taken the liberty of excavating some cadavers from the 29A archives to show", "J'ai pris la liberté d'exhumer quelques cadavres des archives 29A pour montrer"),
    ("you, a few interesting examples of early Linux vx.", "quelques exemples intéressants de vx Linux ancien."),
    ("I've even saved you the", "J'ai même épargné"),
    ("trouble of having to clean out the dirt from under your fingernails.", "le tracas de devoir nettoyer la saleté sous vos ongles."),
    ("We can't very well dive in right away to silvio's works.", "Nous ne pouvons pas plonger tout de suite dans les travaux de silvio."),
    ("They are complex and", "Ils sont complexes et"),
    ("merit a close analysis,", "méritent une analyse approfondie,"),
    ("but in order to get to that point,", "mais pour arriver à ce point,"),
    ("we have to lay some", "nous devons poser quelques"),
    ("ground rules and establish our foundation of Linux VX fundamentals.", "règles de base et établir nos fondamentaux du VX Linux."),
    ("Our first two examples provide such a foundation:", "Nos deux premiers exemples fournissent une telle base :"),
    ("\"ASM TUTORIAL FOR LINUX n' ELF", "\"ASM TUTORIAL FOR LINUX n'ELF"),
    ("FILE FORMAT by LiTlLe VxW\" [7] and \"Linux virus writing tutorial\" [8] by", "FILE FORMAT\" par LiTlLe VxW\" [7] et \"Linux virus writing tutorial\" [8] par"),
    ("Part 2: Silvio cesare's Unix VX techniques", "Partie 2 : Techniques VX Unix de Silvio Cesare"),
    ("\"UNIX ELF Parasites and virus\"[1] and \"UNIX Viruses\"[2] by Silvio Cesare (aka", "« UNIX ELF Parasites and virus »[1] et « UNIX Viruses »[2] par Silvio Cesare (alias"),
    ("silvio), were both published in 1998.", "silvio), ont tous deux été publiés en 1998."),
    ("There is a fair chance that if you're", "Il y a une bonne chance que si vous êtes"),
    ("reading this article,", "en train de lire cet article,"),
    ("you're already familiar with silvio's work.", "vous soyez déjà familier avec le travail de silvio."),
    ("See elfmaster's excellent retrospective on \"Unix Viruses\" in this issue of", "Voir la rétrospective excellente d'elfmaster sur « Unix Viruses » dans ce numéro de"),
    ("tmp.0ut for more about the articles and their legacy.", "tmp.0ut pour plus d'informations sur les articles et leur héritage."),
    ("Silvio's articles on a myriad of Unix/Linux vx techniques that he", "Les articles de Silvio sur un myriade de techniques de vx Unix/Linux qu'il a"),
    ("discovered/invented/brewed in his home lab and simmered to vx excellence", "découvertes/inventées/brewées dans son laboratoire personnel et réduites au vx"),
    ("(Again,", "(Encore,"),
    ("dear reader,", "cher lecteur,"),
    ("you are invited to call in with your thoughts on the best term for", "vous êtes invité à appeler avec vos pensées sur le meilleur terme pour"),
    ("this.", "cela."),
    ("Operators are standing by at the vx hotline,", "Les opérateurs sont en attente à la hotline vx,"),
    ("but be warned that they are", "mais soyez averti qu'ils sont"),
    ("prone to excessively long smoke breaks and they will only answer if you call", "suscités à des pauses fumerie excessivement longues et ne répondront que si vous appelez"),
    ("collect.) are well-known and highly regarded.", "collect.) sont bien connus et hautement appréciés."),
    ("Another example of a great silvio", "Un autre exemple d'un excellent papier de silvio"),
    ("paper is [5],", "est [5]," ),
    ("which I won't be covering today but is an excellent read", "que je ne couvrirai pas aujourd'hui mais qui est une excellente lecture"),
    ("nevertheless.", "nonobstant."),
    ("Since his work is so foundational to Linux vx,", "Puisque son travail est si fondamental pour le vx Linux,"),
    ("it only makes sense that we start there.", "il n'y a que du sens que nous commencions là."),
    ("If you're thinking \"but I'm baby with Linux vx!!\" then", "Si vous pensez \"mais je suis un bébé avec le vx Linux !!\" alors"),
    ("consider our foray into these articles your first bb steps.", "considérez notre exploration de ces articles comme vos premiers pas bb."),
    ("There is a fair amount of overlap between the two articles.", "Il y a une certaine chevauchement entre les deux articles."),
    ("In fact,", "En fait,"),
    ("reading these articles in succession yields some surprising and", "lire ces articles successivement génère des découvertes surprenantes et"),
    ("unexpected gems.", "inattendues."),
    ("For example,", "Par exemple,"),
    ("in [1], Silvio notes \"If the parasite code is to", "dans [1], Silvio note « Si le code parasite doit être"),
    ("be inserted by extending the text segment backwards and using this extra memory,", "inséré en étendant le segment texte vers l'arrière et en utilisant cette mémoire supplémentaire,"),
    ("problems can arise because these ELF headers may have to move in memory and thus", "des problèmes peuvent survenir car ces en-têtes ELF peuvent devoir se déplacer en mémoire et"),
    ("cause problems with absolute referencing.\"", "ainsi causer des problèmes avec la référence absolue.\"."),
    ("And in [2], he notes: \"Extending the text segment backwards is a viable solution and is documented and implemented further in this article.\"", "Et dans [2], il note : « Étendre le segment texte vers l'arrière est une solution viable et est documentée et mise en œuvre plus loin dans cet article.\"."),
    ("This was a cool way to observe someone discovering a new technique over time", "C'était une façon sympa d'observer quelqu'un découvrir une nouvelle technique au fil du temps"),
    ("and tbh it was a nice researcher vignette. Yay silvio!", "et c'était une chouette vignette de chercheur. Yay silvio !"),
    ("Overall,", "Dans l'ensemble,"),
    ("there are four infection techniques presented in these two articles:", "il y a quatre techniques d'infection présentées dans ces deux articles :"),
    ("* file infection", "* infection de fichier"),
    ("* data (segment) infection", "* infection (segment) de données"),
    ("reverse text (segment) infection", "injection de code relocalisable, techniques de code indépendant de la position, détection de virus ELF, et plus encore."),
    ("* reverse text (segment) infection", "* infection (segment) de texte inversé"),
    ("* text segment padding infection", "* infection par remplissage de segment texte"),
    ("The latter three infection techniques are specific to infecting ELF binaries,", "Les trois dernières techniques d'infection sont spécifiques à l'infection de binaires ELF,"),
    ("whereas the first one is a generic file infection technique for any executable.", "où la première est une technique d'infection de fichier générique pour tout exécutable."),
    ("Along with Silvio's articles,", "Avec les articles de Silvio,"),
    ("an accompanying PoC demo virus (both C source and", "un virus de démonstration PoC accompagnant (source C et"),
    ("compiled binary) was initially published and hosted on the website; this site no", "binaire compilé) a été initialement publié et hébergé sur le site web ; ce site ne"),
    ("longer exists (rip) but a snapshot is available on the Wayback Machine, and the", "n'existe plus (rip) mais un Instantané est disponible sur la Wayback Machine, et le"),
    ("tarball is still accessible [see 4].", "tarball est toujours accessible [voir 4]."),
    ("Of these three ELF-specific infection techniques,", "Parmi ces trois techniques d'infection spécifiques à ELF,"),
    ("I will be covering one in this", "je couvrirai une dans cet article —"),
    ("article — Text segment padding infection.", "technique d'infection par remplissage de segment texte."),
    ("For an excellent demo of one of the other techniques (Reverse text segment infection technique),", "Pour une excellente démo de l'une des autres techniques (technique d'infection de segment texte inversé),"),
    ("I refer the reader", "Je renvoie le lecteur"),
    ("to TMZ's excellent Nasty.asm in tmp.0ut vol. 1, as well as qkumba's RE of", "à Nasty.asm excellent de TMZ dans tmp.0ut vol. 1, ainsi qu'au RE de qkumba de"),
    ("Nasty.asm in this current issue of tmp.0ut.", "Nasty.asm dans ce numéro actuel de tmp.0ut."),
    ("TMZ's Nasty.asm provided me with a", "Nasty.asm de TMZ m'a fourni une"),
    ("roadmap for constructing my PoC and was an invaluable resource for me in writing", "feuille de route pour construire mon PoC et a été une ressource inestimable pour moi dans"),
    ("my first Linux vx.", "mon premier vx Linux."),
    ("To briefly summarize the text segment padding infection technique,", "Pour résumer brièvement la technique d'infection par remplissage de segment texte,"),
    ("we can", "nous pouvons"),
    ("exploit the fact that different segments of an ELF binary need to be aligned on", "exploiter le fait que différents segments d'un binaire ELF doivent être alignés sur"),
    ("a page boundary in memory and thus will have a set number of padding bytes", "une frontière de page en mémoire et auront donc un nombre fixe d'octets de remplissage"),
    ("between segments (i.e. .text, .data, etc.).", "entre les segments (c.-à-d..text, .data, etc.)."),
    ("By inserting our virus payload into the padding bytes themselves,", "En insérant notre charge utile de virus dans les octets de remplissage eux-mêmes,"),
    ("ensuring that", "en veillant à ce que la"),
    ("proper page alignment remains intact,", "bonne alignement de page reste intact,"),
    ("then we'll simply need to patch the", "alors nous devrons simplement corriger"),
    ("corresponding fields in the ELF header (and program headers, and section headers)", "les champs correspondants dans l'en-tête ELF (et les en-têtes de programme, et les en-têtes de section)"),
    ("to update relevant offsets and match the changes that result after inserting our", "pour mettre à jour les décalages pertinents et correspondre aux changements qui"),
    ("virus code into the host ELF.", "résultent après l'insertion de notre code de virus dans l'ELF hôte."),
    ("Below is a visual overview of the use of the padding bytes as a code cave:", "Ci-dessous, un aperçu visuel de l'utilisation des octets de remplissage comme galerie de code :"),
    ("With the diagrams,", "Avec les diagrammes,"),
    ("I am using the same technique for describing this as Silvio", "j'utilise la même technique pour décrire cela que Silvio"),
    ("used in [1] and [2].", "utilisé dans [1] et [2]."),
    ("Describing the infection techniques by using ASCII art", "Décrire les techniques d'infection en utilisant l'art ASCII"),
    ("diagrams that show the virus code,", "des diagrammes montrant le code de virus,"),
    ("padding,", "le remplissage,"),
    ("data and text segments", "les données et les segments texte"),
    ("is such an excellent visual teaching tool that is worth adapting here.", "est un excellent outil pédagogique visuel qui vaut la peine d'être adapté ici."),
    ("Seriously though,", "Sérieusement,"),
    ("plz read silvio's articles first.]", "lisez d'abord les articles de silvio.]"),
    ("[Program prior to infection]", "[Programme avant infection]"),
    ("[After vx infection (using text segment padding infection technique)]", "[Après infection vx (en utilisant la technique de remplissage de segment texte)]"),
    ("text segment", "segment texte"),
    ("data segment", "segment de données"),
    ("Padding", "Remplissage"),
    ("Virus", "Virus"),
    ("This insertion step requires some minor bookkeeping,", "cette étape d'insertion nécessite quelques opérations de comptabilité,"),
    ("(e.g. changing p_filesz", "(c.-à-d.changer p_filesz"),
    ("and p_memsz in the Program Header for the .text segment).", "et p_memsz dans l'en-tête de programme pour le segment .text)."),
    ("In addition to implementing routines for patching the ELF Header and the Program", "En plus de la mise en œuvre de routines pour corriger l'en-tête ELF et les"),
    ("Headers,", "En-têtes,"),
    ("the virus writer must implement an additional patching routine to", "l'auteur du virus doit implémenter une routine de correction supplémentaire pour"),
    ("successfully infect stripped binaries.", "infecter correctement les binaires strippés."),
    ("Our virus code will be inserted into the padding bytes between the .text and", "Le code de notre virus sera inséré dans les octets de remplissage entre .text et"),
    (".data segments. This padding is viewed as essentially purgatory/limbo/no man's", "les segments .data. Ce remplissage est considéré comme essentiellement le purgatoire/l'entre-deux"),
    ("land and it is not associated with a section in the ELF.", "et il n'est pas associé à une section dans l'ELF."),
    ("If our virus infects a host ELF that is a stripped binary,", "Si notre virus infecte un ELF hôte qui est un binaire strippé,"),
    ("then the virus cannot rely on the binary's", "le virus ne peut pas compter sur le"),
    ("symbols to resolve addresses.", "symboles pour résoudre les adresses."),
    ("Without a workaround,", "Sans solution de contournement,"),
    ("the resulting infected ELF will not run,", "l'ELF infecté résultant ne fonctionnera pas,"),
    ("and our virus' efficacy will be limited to infecting unstripped", "et l'efficacité de notre virus sera limitée à l'infection de binaires non strippés."),
    ("binaries.", ""),
    ("To ensure that our virus remains \"strip-safe,\"", "Pour garantir que notre virus reste « strip-safe »,"),
    ("then we must implement an", "nous devons implémenter une"),
    ("additional routine: associate the virus code with the last section in the .text", "routine supplémentaire : associer le code de virus avec la dernière section du segment .text"),
    ("segment by adjusting the sh_len field of that section to account for the newly", "en ajustant le champ sh_len de cette section pour tenir compte du"),
    ("inserted virus code.", "code de virus nouvellement inséré."),
    ("The pseudocode outline of the algorithm for the infection routine (which makes", "Le plan de pseudocode de l'algorithme pour la routine d'infection (qui constitue"),
    ("up the bulk of our virus code) follows.", "le gros du code de virus) suit."),
    ("It is adapted from the algorithm defined", "Il est adapté de l'algorithme défini"),
    ("by Silvio in [2],", "par Silvio dans [2],"),
    ("with my own additional notes added for clarity during my vx", "avec mes propres notes supplémentaires ajoutées pour plus de clarté pendant mon"),
    ("development process:", "développement vx :"),
    ("assumes the following:", "suppose ce qui suit :"),
    ("vlen == length of virus code", "vlen == longueur du code virus"),
    ("PAGESIZE == 4096", "PAGESIZE == 4096"),
    ("1. Find and save original entry point (OEP) of ELF host", "1. Trouver et sauvegarder le point d'entrée original (OEP) de l'ELF hôte"),
    ("2. Patch ELF header values to account for newly inserted virus code", "2. Corriger les valeurs d'en-tête ELF pour tenir compte du code virus nouvellement inséré"),
    ("Patch the entry point in the ELF header to point to the beginning of the virus code", "Corriger le point d'entrée dans l'en-tête ELF pour pointer vers le début du code virus"),
    ("change e_shoff in virus ELF header to new_vx_e_shoff s.t. new_vx_e_shoff = host_e_shoff + PAGESIZE", "changer e_shoff dans l'en-tête ELF virus à new_vx_e_shoff tel que new_vx_e_shoff = host_e_shoff + PAGESIZE"),
    ("3. a. Loop through all Phdrs to find text segment Phdr", "3. a. Boucler à travers tous les Phdrs pour trouver le Phdr du segment texte"),
    ("Find and save original entry point (OEP) of ELF host", "Trouver et sauvegarder le point d'entrée original (OEP) de l'ELF hôte"),
    ("b. if curr_Phdr == text_segment_Phdr then, do the following:", "b. si curr_Phdr == text_segment_Phdr alors, faire ce qui suit :"),
    ("increase p_filesz by vlen [p_filesz += vlen]", "augmenter p_filesz de vlen [p_filesz += vlen]"),
    ("increase p_memsz by vlen, [p_memsz += vlen]", "augmenter p_memsz de vlen, [p_memsz += vlen]"),
    ("c. Else, for all Phdrs corresponding to segments located after the inserted", "c. Sinon, pour tous les Phdrs correspondant à des segments situés après le code de virus"),
    ("virus code (aka for each Phdr of a segment after the text segment),", "inséré (aka pour chaque Phdr d'un segment après le segment texte),"),
    ("then, do the following:", "alors, faire ce qui suit :"),
    ("i. increase p_offset by PAGESIZE", "i. augmenter p_offset de PAGESIZE"),
    ("4. Loop through all Shdrs", "4. Boucler à travers tous les Shdrs"),
    ("If curr_shdr == last_shdr_text_segment then,", "Si curr_shdr == last_shdr_text_segment alors,"),
    ("For our code ingredients, we can use the algorithm from silvio's paper as a", "Pour nos ingrédients de code, nous pouvons utiliser l'algorithme du papier de silvio comme"),
    ("guide,", "guide,"),
    ("as it outlines the virus' infection routine.", "car il décrit la routine d'infection du virus."),
    ("My implementation of this algorithm follows in [part 2c].", "Ma mise en œuvre de cet algorithme suit dans [partie 2c]."),
    ("We will need other routines in our virus, such as for identifying viable target", "Nous avons besoin d'autres routines dans notre virus, comme pour identifier les fichiers"),
    ("files.", "cible viables."),
    ("This will answer questions like \"How do we even find files to infect?\"", "Cela répond à des questions comme « Comment trouvons-nous même des fichiers à infecter ? »"),
    ("and \"How do we verify that each candidate file is a valid target ELF???", "et « Comment vérifions-nous que chaque fichier candidat est un ELF cible valide ???"),
    ("Of course,", "Bien sûr,"),
    ("there are many ways one could go about a check_file routine.", "il y a plusieurs façons de procéder avec une routine check_file."),
    ("In my", "Dans ma"),
    ("implementation,", "mise en œuvre,"),
    ("I devised an approach based on the techniques of works by", "j'ai devisu une approche basée sur les techniques d'œuvres par"),
    ("silvio[1,2], TMZ[14], and elfmaster[13],", "silvio[1,2], TMZ[14], et elfmaster[13]," ),
    ("as these were the virii that I", "car ceux-ci étaient les virus que j'ai"),
    ("referenced most often while writing this PoC.", "référencés le plus souvent pendant l'écriture de ce PoC."),
    ("In my PoC,", "Dans mon PoC,"),
    ("to find target files to infect,", "pour trouver les fichiers à infecter,"),
    ("gospel does the following:", "gospel fait ce qui suit :"),
    ("* Use the getdents64 syscall to get the dirent structs for the current working", "* Utiliser l'appel système getdents64 pour obtenir les structures dirent du répertoire de travail actuel"),
    ("directory.", "courant."),
    ("* Iterate through each entry (if getdents64 returns a positive integer value;", "* Itérer à travers chaque entrée (si getdents64 renvoie une valeur entière positive ;"),
    ("otherwise, uh oh) and perform checks.", "sinon, oh non) et effectuer des vérifications."),
    ("* After each file has been checked,", "* Après que chaque fichier a été vérifié,"),
    ("it either calls the infection routine (if", "il appelle soit la routine d'infection (si"),
    ("the candidate file is a valid target ELF) or the check_file routine will check", "le fichier candidat est un ELF cible valide) ou la routine check_file vérifiera"),
    ("the file in the next dirent struct.", "le fichier dans la structure dirent suivante."),
    ("It calculates the offset to the next dirent entry by using the d_reclen field value of the current dirent struct.", "Il calcule le décalage vers la structure dirent suivante en utilisant la valeur du champ d_reclen de la structure dirent actuelle."),
    ("What are the requirements that we want the file we are checking to satisfy?", "Quelles sont les exigences que nous voulons que le fichier que nous vérifions satisfasse ?"),
    ("Minimally, the target file has to be an ELF.", "Minimel",),
    ("Beyond that,", "Au-delà de cela,"),
    ("the required elements", "les éléments requis"),
    ("of the ELF target will be specific to the virus being implemented and the target", "de l'ELF cible seront spécifiques au virus implémenté et au"),
    ("system.", "système."),
    ("Here are the requirements I used to determine valid ELF infection targets:", "Voici les exigences que j'ai utilisées pour déterminer les cibles d'infection ELF valides :"),
    ("check_file:", "check_file :"),
    ("open file -> fstat file (get file size) -> use fstat.size for mmap call & mmap file", "ouvrir le fichier -> fstat le fichier (obtenir la taille du fichier) -> utiliser fstat.size pour mmap & mapper le fichier"),
    ("upon successful mmap, close file", "après un mmap réussi, fermer le fichier"),
    ("use mmap'd file for checks to confirm that the target file satisfies the following:", "utiliser le fichier mappé pour vérifier que le fichier cible satisfait ce qui suit :"),
    ("1. the target file is an executable*", "1. le fichier cible est un exécutable*"),
    ("2. the target file is an ELF", "2. le fichier cible est un ELF"),
    ("3. the target file is a 64-bit ELF", "3. le fichier cible est un ELF 64 bits"),
    ("4. the target file arch is x86_64", "4. l'architecture du fichier cible est x86_64"),
    ("5. The target file is neither \".\" (cwd) nor \"..\" (Parent dir)", "5. Le fichier cible n'est ni « . » (répertoire courant) ni « .. » (répertoire parent)"),
    ("6. the target file is not already infected (check w signature at known offset)", "6. le fichier cible n'est pas déjà infecté (vérifier avec une signature à un décalage connu)"),
    ("Note: we want to confirm that a candidate file is a regular file and an", "Note : nous voulons confirmer qu'un fichier candidat est un fichier régulier et un"),
    ("executable file,", "fichier exécutable,"),
    ("so that we don't waste time checking a dirent that corresponds", "pour ne pas perdre du temps à vérifier un dirent qui correspond"),
    ("to a directory.", "à un répertoire."),
    ("If you want to confirm that a target is a regular file,", "Si vous voulez confirmer qu'une cible est un fichier régulier,"),
    ("you could check whether curr_d_entry->d_type == DT_REG but the d_type field is", "vous pourriez vérifier si curr_d_entry->d_type == DT_REG mais le champ d_type"),
    ("technically not a required field in a dirent struct and of course it wasn't", "est techniquement pas un champ requis dans une structure dirent et bien sûr,"),
    ("present on my machine.", "il n'était pas présent sur ma machine."),
    ("Another option is to check a field in the fstat structure (after making an", "Une autre option est de vérifier un champ dans la structure fstat (après avoir fait un"),
    ("fstat syscall of course): st_mode.", "appel système fstat bien sûr) : st_mode."),
    ("We can query the st_mode field in the", "Nous pouvons interroger le champ st_mode dans la"),
    ("returned stat struct to determine if the file we are currently examining is", "structure stat retournée pour déterminer si le fichier que nous examinons actuellement est"),
    ("a regular file;", "un fichier régulier ;"),
    ("our check will pass when the st_mode field satisfies the requirements of S_ISREG.", "notre vérification passera quand le champ st_mode satisfait les exigences de S_ISREG."),
    ("But not so fast!", "Mais pas si vite !"),
    ("If you're coding this in asm,", "Si vous codez cela en asm,"),
    ("then you'll realize that", "vous réaliserez que"),
    ("S_ISREG is actually a macro,", "S_ISREG est en fait une macro,"),
    ("which expands to be:", "qui se développe en :"),
    ("where:", "où :"),
    ("Eventually you might just be tired of trying to define a macro in NASM that", "Éventuellement, vous pourriez être fatigué d'essayer de définir une macro dans NASM qui"),
    ("performs bitwise operations on integers of varying widths and say,", "effectue des opérations binaires sur des entiers de largeurs variées et dires,"),
    ("\"fuck it, we ball.\"", "\"putain, on va-y aller.\""),
    ("Which here translates to: just perform checks on the Ehdr.e_type.", "Ici, cela se traduit par : effectuez simplement des vérifications sur Ehdr.e_type."),
    ("If Ehdr.e_type == 0x0200 (DYN) or 0x0300 (EXEC) then this check passes.", "Si Ehdr.e_type == 0x0200 (DYN) ou 0x0300 (EXEC) alors cette vérification passe."),
    ("If all of the above conditions hold,", "Si toutes les conditions ci-dessus sont remplies,"),
    ("then call the infection routine", "appelez la routine d'infection"),
    ("Otherwise, continue looping through remaining files in the directory", "Sinon, continuez à boucler sur les fichiers restants dans le répertoire"),
    ("At this point we have a clear understanding of all of the components that we", "À ce stade, nous avons une compréhension claire de tous les composants dont nous avons besoin"),
    ("need in order to whip up a PoC for the text segment padding infection technique", "pour créer un PoC de la technique d'infection par remplissage de segment texte"),
    ("and apply what we've learned.", "et appliquer ce que nous avons appris."),
    ("Let's recap our vx requirements here:", "Récapitulons nos exigences vx ici :"),
    ("1. An implementation of the infection algorithm", "1. Une implémentation de l'algorithme d'infection"),
    ("2. A routine for validating that a candidate file satisfies a clearly defined", "2. Une routine pour valider qu'un fichier candidat satisfait un ensemble clairement"),
    ("set of requirements for a valid ELF target", "défini d'exigences pour une cible ELF valide"),
    ("3. A routine for finding candidate files on the system that we will infect with", "3. Une routine pour trouver des fichiers candidats sur le système que nous infecterons avec"),
    ("our virus payload", "notre charge utile de virus"),
    ("4. Two separate work areas — one work area for parsing various components in our", "4. Deux zones de travail séparées — une zone de travail pour analyser divers"),
    ("host ELF file and one \"staging\" area (temp file) where we will incrementally", "composants dans notre fichier ELF hôte et une zone « d'étalonnage » (fichier temporaire)"),
    ("build up our final infected host+virus ELF.", "où nous construirons progressivement notre ELF hôte+virus infecté final."),
    ("5. Clearly defined data structures to target and use/manipulate", "5. Structures de données clairement définies à cibler et utiliser/manipuler"),
    ("6. A siq payload", "6. Une charge utile siq"),
    ("7. Misc.: error handling and all the other boring + nec stuff. Implement at your", "7. Divers : gestion des erreurs et tout le autre truc ennuyeux + nec. Implémentez à votre"),
    ("leisure (or fail to implement at your peril)", "convenance (ou échouez à votre péril)"),
    ("Item #6 is up to the discretion of the vx writer.", "L'élément #6 dépend du bon sens de l'auteur du virus."),
    ("Of course,", "Bien sûr,"),
    ("the implementation", "la mise en œuvre"),
    ("of any of these items is up to the discretion of the vx writer.", "de n'importe lequel de ces éléments dépend du bon sens de l'auteur du virus."),
    ("Do whatever you want.", "Faites ce que vous voulez."),
    ("I told you,", "Je vous l'ai dit,"),
    ("I'll just be over here,", "je serai juste par ici,"),
    ("stitching up monsters like a good", "boutefie un monstre comme un bon"),
    ("delinquent.", "délinquant."),
    ("At the end of the day,", "À la fin de la journée,"),
    ("I just hope your vx isn't boring.", "j'espère juste que votre vx n'est pas ennuyeux."),
    ("Item #6 in my PoC (gospel) draws a piece of ASCII art to the screen.", "L'élément #6 dans mon PoC (gospel) dessine un morceau d'art ASCII à l'écran."),
    ("For peak spooky daemonic malware witch vibes,", "Pour des vibes maximales de sorcière malveillante démoniaque,"),
    ("I used a Python script to transform one of", "j'ai utilisé un script Python pour transformer l'un de"),
    ("my pen&ink drawings of a skull into a scaled down piece of ASCII art.", "mes dessins à l'encre de ma main d'un crâne en un morceau d'art ASCII réduite."),
    ("The virus", "Le virus"),
    ("payload of gospel displays this ASCII art skull drawing and then jumps to the saved", "charge utile de gospel affiche ce dessin de crâne ASCII puis saute vers le"),
    ("original entry point of the host ELF.", "point d'entrée original de l'ELF hôte."),
    ("Part 2c: Infection algorithm implementation", "Partie 2c : Implémentation de l'algorithme d'infection"),
    ("We have arrived at the juiciest part of our virus: the infection routine.", "Nous sommes arrivés à la partie la plus savoureuse de notre virus : la routine d'infection."),
    ("the infection routine will consist mainly of two parts: a", "la routine d'infection consistera principalement en deux parties : une"),
    ("PHdr patching routine and an SHdr patching routine.", "routine de correction PHdr et une routine de correction SHdr."),
    ("gospel infection routine", "routine d'infection gospel"),
    ("location on stack for saved address of", "emplacement sur la pile pour l'adresse sauvegardée de"),
    ("mmap'd host ELF", "ELF hôte mappé"),
    ("offset of host ELF Program Header Table", "décalage de la table des en-têtes de programme ELF hôte"),
    ("offset of host ELF Section Header Table", "décalage de la table des en-têtes de section ELF hôte"),
    ("offset of host ELF original entry point", "décalage du point d'entrée original de l'ELF hôte"),
    ("infection marker string", "chaîne de marqueur d'infection"),
    ("stored in elf_ehdr.e_padding", "stockée dans elf_ehdr.e_padding"),
    ("Update program headers of infected ELF", "Mettre à jour les en-têtes de programme de l'ELF infecté"),
    ("entry virus addr (evaddr)=", "adresse du virus d'entrée (evaddr)="),
    ("phdr->p_vaddr + phdr->p_filesz", "phdr->p_vaddr + phdr->p_filesz"),
    ("save evaddr to (r14 + 400)", "sauvegarder evaddr à (r14 + 400)"),
    ("load address of OEP from ELF header", "charger l'adresse d'OEP depuis l'en-tête ELF"),
    ("new entry point of infected file = evaddr", "nouveau point d'entrée du fichier infecté = evaddr"),
    ("patch ELF header entry point to start of vx code", "corriger le point d'entrée de l'en-tête ELF vers le début du code vx"),
    ("vxoffset = elf_phdr.p_offset+elf_phdr.p_filesz", "vxoffset = elf_phdr.p_offset+elf_phdr.p_filesz"),
    ("save vxoffset to stack", "sauvegarder vxoffset sur la pile"),
    ("phdr.p_filesz += vlen+10(size of jmp to OEP)", "phdr.p_filesz += vlen+10(taille du jmp vers OEP)"),
    ("phdr.p_memsz += vlen+10(size of jmp to OEP)", "phdr.p_memsz += vlen+10(taille du jmp vers OEP)"),
    ("Now patch section headers of infected ELF", "Maintenant corriger les en-têtes de section de l'ELF infecté"),
    ("We will use a very similar schema as was used in the", "Nous utiliserons un schéma très similaire à celui utilisé dans la"),
    ("PHdr patching routine above for our SHdr patching routine,", "routine de correction PHdr ci-dessus pour notre routine de correction SHdr,"),
    ("with a few modifications.", "avec quelques modifications."),
    ("the ELF Header", "l'en-tête ELF"),
    ("ELF Program Headers", "En-têtes de programme ELF"),
    ("ELF Section headers", "En-têtes de section ELF"),
    ("dirent struct", "structure dirent"),
    ("the stat struct", "la structure stat"),
    ("Originally,", "Originellement,"),
    ("I placed all of the struct definitions for the relevant data", "J'ai placé toutes les définitions de structures pour les données"),
    ("structures in a .bss section in my virus.", "pertinentes dans une section .bss dans mon virus."),
    ("However,", "Cependant,"),
    ("due to the logic of the virus' infection/replication routines", "en raison de la logique des routines d'infection/réplication du virus"),
    ("(specifically how it reconstructs a", "(spécifiquement la façon dont il reconstruit une"),
    ("copy of itself in a newly infected host ELF),", "copie de lui-même dans un ELF hôte nouvellement infecté),"),
    ("these struct definitions had to", "ces définitions de structures devaient"),
    ("be moved from the .bss section to the .text section.", "être déplacées de la section .bss à la section .text."),
    ("Defining them in the .bss section would have required the addition of a routine for copying the", "Les définir dans la section .bss aurait nécessité l'ajout d'une routine pour"),
    (".bss section from the virus,", ".bss du virus,"),
    ("and I preferred the simpler logic (and smaller overall code size) of a virus that was entirely self-contained (so to speak) within the .text segment.", "et j'ai préféré la logique plus simple (et la taille de code plus petite) d'un virus entièrement autonome (pour ainsi dire) dans le segment .text."),
    ("Several of the variable names stored on the stack may appear obtuse to you", "Plusieurs des noms de variables stockées sur la pile peuvent vous sembler étranges"),
    ("for the moment,", "pour le moment,"),
    ("dear reader,", "cher lecteur,"),
    ("but smile and nod your greetings and I'll catch", "souriez et hochez la tête en disant bonjour et je vous rattraperai"),
    ("you up on the details in due time.", "sur les détails en temps opportun."),
    ("Now without further ado,", "Sans autre formalité,"),
    ("the stack layout of gospel:", "le disposition de la pile de gospel :"),
    ("stacks on stacks on stacks", "empilements sur empilements d'empilements"),
    ("I'm doing this because a .bss section for a virus", "Je le fais parce qu'une section .bss pour un virus"),
    ("is a nightmare to deal with", "est un cauchemar à gérer"),
    ("so, yw,", "donc, yw,"),
    ("I've written out the stack layout 4 u", "j'ai écrit la disposition de la pile 4 u"),
    ("il n'y a plus de cauchemars", "il n'y a plus de cauchemars"),
    ("jtm", "jtm"),
    ("xoxo", "xoxo"),
    ("Note that I use r14 here rather than rsp", "Notez que j'utilise r14 ici plutôt que rsp"),
    ("This is because gospel begins by reserving 0x2000 bytes on the stack and then", "C'est parce que gospel commence par réserver 0x2000 octets sur la pile puis"),
    ("moving the saved value of [rsp - 0x2000] to r14", "en déplaçant la valeur sauvegardée de [rsp - 0x2000] vers r14"),
    ("filestat struct", "structure filestat"),
    ("stack layout: ", "disposition de la pile :"),
    ("IDdevcontainingfile", "IDdevcontenantfichier"),
    ("inode#", "inode#"),
    ("mode", "mode"),
    ("#ofhardlinks", "#deliensdurs"),
    ("useridofowner", "useriddupropriétaire"),
    ("groupIdofowner", "groupIddu propriétaire"),
    ("devID", "devID"),
    ("totalsizeinbytes", "tailletotaleenoctets"),
    ("blocksizeforfsi/o", "tailledublocpourfsi/o"),
    ("#of512bblocksalloc'd", "#deblocsd512balloués"),
    ("timelastfileaccess", "heuredernieracces aufichier"),
    ("timeoflastfilemod", "heuredernièremodifdufichier"),
    ("timelastfilechange", "heuredernierchangementsdefichier"),
    ("end struc", "fin struc"),
    ("Return to Original Entry Point Despite PIE", "Retour au Point d'Entrée Original malgré PIE"),
    ("Instructions for returning to original entry point of PIE host ELF", "Instructions pour retourner au point d'entrée original de l'ELF hôte PIE"),
    ("after conclusion of vx routines; appended to end of vx body", "après la conclusion des routines vx ; ajouté à la fin du corps vx"),
    ("Shout to MalcolmVX for the guidance and help on figuring out the ret2oep routine", "Hommage à MalcolmVX pour le guide et l'aide pour résoudre la routine ret2oep"),
    ("References:", "Références :"),
    ("Return To Original Entry Point Despite PIE", "Retour au Point d'Entrée Original malgré PIE"),
    ("Part 2d: PoC", "Partie 2d : Preuve de concept (PoC)"),
    ("The accompanying PoC for this article is my implementation of the text segment", "Le PoC accompagnant cet article est ma mise en œuvre de la"),
    ("padding virus, written in x86-64 asm.", "technique de virus de remplissage de segment texte, écrite en asm x86-64."),
    ("It infects ELF x86-64 PIE executables in", "Il infecte les exécutables ELF PIE x86-64"),
    ("the current working directory.", "du répertoire de travail courant."),
    ("The infected file will run the virus payload —", "Le fichier infecté exécutera la charge utile du virus —"),
    ("printing an ASCII art skull drawing to stdout — and then ret to the OEP and run", "en imprimant un dessin de crâne ASCII sur stdout — puis retourner au OEP et exécuter"),
    ("the host ELF code.", "le code ELF hôte."),
    ("Source code: https://tmpout.sh/3/Linux.gospel.asm", "Code source : https://tmpout.sh/3/Linux.gospel.asm"),
    ("Source code, as well as copies of the 29a archive references for this article,", "Le code source, ainsi que les copies des références d'archives 29a pour cet article,"),
    ("are also available on the GitHub repo here:", "sont également disponibles sur le repo GitHub ici :"),
    ("Part 2e: Reflections:", "Partie 2e : Réflexions :"),
    ("where's my polymorphism uwu", "où est mon polymorphisme uwu"),
    ("The main obstacle in turning the current version of Linux.gospel.asm into a", "L'obstacle principal pour transformer la version actuelle de Linux.gospel.asm en"),
    ("polymorphic virus is the permissions used for the .text segment in an ELF —", "virus polymorphe est les Permissions utilisées pour le segment .text dans un ELF —"),
    ("which will be mapped to a page with RX permissions but not RW permissions.", "lesquelles seront mappées sur une page avec des Permissions RX mais pas RW."),
    ("We won't be able to insert self-modifying code into this page without modifying", "Nous ne pourrons pas insérer du code auto-modifiant dans cette page sans modifier"),
    ("the permissions of the .text segment in the infected ELF.", "les Permissions du segment .text dans l'ELF infecté."),
    ("This would look suspicious and that's not a cute look for us.", "Cela ressemblerait suspect et ce n'est pas un joli look pour nous."),
    ("The RX page permissions of the mapped .text segment and its limitations for", "Les Permissions de page RX du segment .text mappé et ses limites pour"),
    ("storing/saving variables created some initial difficulty.", "le stockage/sauvegarde des variables a créé certaines difficultés initiales."),
    ("In my PoC,", "Dans mon PoC,"),
    ("the virus", "le virus"),
    ("needs to store variables which won't be defined prior to runtime.", "doit stocker des variables qui ne seront pas définies avant l'exécution."),
    ("Without the use of a .data or .bss segment,", "Sans l'utilisation d'un segment .data ou .bss,"),
    ("(which we want to avoid) we have to store all", "(que nous voulons éviter) nous devons stocker toutes les"),
    ("variables on the stack.", "variables sur la pile."),
    ("A better option for writing a polymorphic virus is to use a segment with RW", "Une meilleure option pour écrire un virus polymorphe est d'utiliser un segment avec RW"),
    ("permissions as a target region for injecting virus code.", "Permissions en tant que région cible pour injecter du code de virus."),
    ("The .data segment is", "Le segment .data est"),
    ("a good candidate for this.", "un bon candidat pour cela."),
    ("A virus writer could even use another of Silvio's", "Un auteur de virus pourrait même utiliser une autre des techniques de Silvio"),
    ("techniques as a guide: the .data segment infection technique.", "comme guide : la technique d'infection du segment .data."),
    ("Perhaps if one were so inclined,", "Peut-être si quelqu'un est ainsi disponible,"),
    ("they could write a virus that splits its", "ils pourraient écrire un virus qui divise sa"),
    ("payload and combines the text segment padding infection technique with the", "charge utile et combine la technique de remplissage de segment texte avec la"),
    ("data segment infection technique.", "technique d'infection du segment .data."),
    ("But that's a virus for another time.", "Mais c'est un virus pour une autre fois."),
    ("Part 3: A squeeze of LiME", "Partie 3 : Une touche de LiME"),
    ("We have arrived at the penultimate section of our article.", "Nous sommes arrivés à la section pénultième de notre article."),
    ("Congratulations for", "Félicitations pour"),
    ("making it this far.", "avoir réussi jusque là."),
    ("As a treat,", "En guise de récompense,"),
    ("in addition to your party favor (don't forget your goodie bag with the Linux vx I wrote 4 u! Don't forget your hat or your gloves!", "en plus de votre cadeau de fête (n'oubliez pas votre sac de friandises avec le vx Linux que j'ai écrit pour toi ! N'oubliez pas ton chapeau ou tes gants !"),
    ("Do you want me to pack you a Tupperware with some leftovers? Of course", "Tu veux que je t'emballe un Tupperware avec des restes ? Bien sûr"),
    ("you do.) there's an extra special surprise just 4 u:", "que tu veux.) il y a une surprise spéciale juste pour toi :"),
    ("a brief introduction to", "une brève introduction à"),
    ("early polymorphic and metamorphic Linux vx.", "vx Linux polymorphe et métamorphique ancien."),
    ("This article series is titled", "Cette série d'articles est intitulée"),
    ("after all.", "après tout."),
    ("So,", "Donc,"),
    ("in the spirit of Drake sampling from early hip-hop artists of the late", "dans l'esprit de Drake qui prélève des artistes de hip-hop anciens des"),
    ("'90s/early. 2000s,", "'90s/early 2000s,"),
    ("we will be sampling from Benny, the Mental Driller and", "nous allons prélever de Benny, du Mental Driller et"),
    ("zhugejin and their works of the late '90s/early 2000s.", "zhugejin et leurs œuvres des années 1990/début 2000."),
    ("I use the term \"sampling\" here to draw an important distinction:", "J'utilise le terme « échantillonnage » ici pour souligner une distinction importante :"),
    ("just as the work of Ms. Lauryn Hill", "tout comme le travail de Ms. Lauryn Hill"),
    ("stands on its own,", "se tient seul,"),
    ("deserves the time and attention of a dedicated listen and", "mérite le temps et l'attention d'une écoute dédiée et"),
    ("will reward a listener who dives in after hearing a hook in \"Nice for What\"", "récompense un auditeur qui plonge après avoir entendu un hook dans « Nice for What »"),
    ("(as anyone who has ever listened to \"The Miseducation of Lauryn Hill\" on loop", "(comme quiconque a écouté « The Miseducation of Lauryn Hill » en boucle"),
    ("for months on end will tell you),", "pendant des mois me dirait),"),
    ("so too do the works referenced in this article", "ainsi que les œuvres référencées dans cet article"),
    ("merit reading in their entirety.", "méritent d'être lues dans leur intégralité."),
    ("This article \"samples\" these works to provide an introduction,", "Cet article « prélève » ces œuvres pour fournir une introduction,"),
    ("but is by no means an exhaustive or detailed examination of the", "mais n'est en aucun cas une examination exhaustive ou détaillée des"),
    ("works themselves.", "travaux eux-mêmes."),
    ("The reader is encouraged to explore these works and read them", "Le lecteur est encouragé à explorer ces œuvres et à les lire"),
    ("in full.", "intégralement."),
    ("The reader is also encouraged to listen to \"The Miseducation of Lauryn Hill.\",", "Le lecteur est également encouragé à écouter « The Miseducation of Lauryn Hill. »,"),
    ("The works we will be digging into that exemplify two different types of", "Les œuvres que nous allons creuser exemplifient deux types différents de"),
    ("polymorphic virus writing are the following:", "écriture de virus polymorphe :"),
    ("written by", "écrit par"),
    ("zhugejin at Taipei, Taiwan; Date: 2000/10/10,", "zhugejin à Taipei, Taïwan ; Date : 2000/10/10,"),
    ("Last update: 2001/02/28, 29A issue #6", "Dernière mise à jour : 2001/02/28, numéro 29A #6"),
    ("The third article deals with *metamorphism*", "Le troisième article traite de *métamorphisme*"),
    ("and not *polymorphism.*", "et non de *polymorphisme.*"),
    ("However,", "Cependant,"),
    ("in order to understand metamorphism,", "pour comprendre le métamorphisme,"),
    ("we must build up to it with polymorphism.", "nous devons progresser avec le polymorphisme."),
    ("So let us begin there.", "Commençons donc par là."),
    ("we will work our way up to metamorphism...", "nous progresserons jusqu'au métamorphisme..."),
    ("It's time for us to put our vx cadavers back in their cases and into the", "Il est temps pour nous de remettre nos cadavres de vx dans leurs cASICA et dans le"),
    ("freezer.", "congélateur."),
    ("We've completed our study for the day and we want to keep our virus", "Nous avons terminé notre étude pour la journée et nous voulons garder notre virus"),
    ("bodies well-preserved.", "corps bien préservés."),
    ("We'll return to more in our next da Vinci vx morgue", "Nous reviendrons avec plus dans notre prochaine morgue de vx da Vinci"),
    ("excursion.", "excursion."),
    ("I hope you've been taking notes this whole time.", "J'espère que vous avez pris des notes pendant ce temps."),
    ("There's no", "Il n'y a pas de"),
    ("guarantee that I'll be there to guide you the next time you feel like doing", "garantie que je serai là pour vous guider la prochaine fois que vous aurez envie de"),
    ("studies of ELF internals.", "étudier les internes de ELF."),
    ("Alright, fine.", "Très bien,"),
    ("I'll leave you with some techniques I use to find my way when", "Je vous laisse avec quelques techniques que j'utilise pour me retrouver"),
    ("things go awry writing vx.", "quand les choses vont de travers dans l'écriture de vx."),
    ("There's lots of things that go bump in the night", "Il y a beaucoup de choses qui bougent dans la nuit"),
    ("out there in spooky scary ~*cyberspace*~ so it's best you make friends with", "par là-bas dans l'~*cyberspace*~ effrayant, il vaut mieux que vous vous fassiez des"),
    ("your daemons now:", "amis avec vos démons maintenant :"),
    ("Whether you're searching for a roadmap to human anatomical structures or a", "Que vous cherchiez un itinéraire vers des structures anatomiques humaines ou un"),
    ("roadmap to a beautiful virus,", "itinéraire vers un virus magnifique,"),
    ("sometimes the only way forward is to create your own.", "parfois, la seule façon d'avancer est de créer le vôtre."),
    ("Along the way,", "En chemin,"),
    ("there will be broken bones and covert operations undertaken in", "il y aura des os brisés et des opérations secrètes entreprises dans"),
    ("the dead of night.", "la nuit."),
    ("And as you dear reader,", "Et en tant que vous, cher lecteur,"),
    ("dust yourself off once again,", "essuyez-vous la poussière une autre fois,"),
    ("after making a foray of missteps and pitfalls,", "après avoir fait une exploration de pas et de précipices,"),
    ("and you're feeling lost and", "et vous vous sentez perdu et"),
    ("adrift between the mausoleum and the obelisk,", "égaré entre le mausolée et l'obélisque,"),
    ("wondering if it's worth it to", "se demandant si c'est worth it"),
    ("continue trudging forward in the mud,", "de continuer à trébucher dans la boue,"),
    ("I offer you this: look for the footsteps of those who traversed these paths before you,", "Je vous offre ceci : cherchez les empreintes de ceux qui ont parcouru ces chemins avant vous,"),
    ("follow them with an open mind and your conviction for what you set out to find.", "suivez-les avec un esprit ouvert et votre conviction pour ce que vous avez cherché à trouver."),
    ("The knowledge and insight of the early Unix/Linux vx writers is evergreen and", "La connaissance et la perspective des premiers écrivains de vx Unix/Linux sont intemporelles et"),
    ("can lead you to breakthroughs and new ideas in your own work.", "peuvent vous mener à des avancées et de nouvelles idées dans votre propre travail."),
    ("A virus, like any work of art,", "Un virus, comme toute œuvre d'art,"),
    ("has power both to wreak havoc and to be goddamn beautiful;", "a le pouvoir de semer la discorde et d'être gddm beau;"),
    ("a virus can be horrifying or clever or charming or sinister or", "un virus peut être effrayant ou malin ou charmant ou sinistre ou"),
    ("inspiring or thought-provoking or all of the above,", "inspirant ou stimulant la réflexion ou tout cela,"),
    ("but,", "mais,"),
    ("above all else,", "par-dessus tout,"),
    ("a virus should", "un virus devrait"),
    ("should *never* be boring.", "*jamais* être ennuyeux."),
    ("Enclosed in this GitHub repo is a playlist to accompany this article,", "Inclus dans ce repo GitHub est une playlist pour accompagner cet article,"),
    ("itself aptly titled \"gospel for a new epoch.\"", "elle-même intitulée « gospel for a new epoch »."),
    ("This playlist is part of a collaborative", "Cette playlist est une"),
    ("ongoing project by myself and Travis Goodspeed.", "projet collaboratif entre moi et Travis Goodspeed."),
    ("Travis has been kind enough to", "Travis a été assez gentil pour"),
    ("make the repo public so that you too can enjoy the delights of spiritual tunes", "rendre le repo public pour que vous puissiez également profiter des délices des"),
    ("for the punk rock ne'er do well and the cosmically deranged.", "tunes spirituels pour le punk rock ne'er do well et le cosmiquement fou."),
    ("Listen to these tracks while you're writing your own Linux vx:", "Écoutez ces morceaux pendant que vous écrivez votre propre vx Linux :"),
    ("k that's all for now", "k c'est tout pour l'instant"),
    ("luv u all so much", "luv you all so much"),
    ("xoxo", "xoxo"),
    ("Extra special shoutouts and thank you to netspooky and sblip for all of their", "Un grand merci spécial à netspooky et sblip pour tout leur"),
    ("support and feedback on this project!", "support et commentaires sur ce projet !"),
    ("Everyone on the tmp.0ut team for the support/feedback/debugging sessions.", "Toute l'équipe tmp.0ut pour le support/les commentaires/les sessions de débogage."),
    ("richinseattle, elfmaster, TMZ, B3nny, MalcolmVX, and everyone on the vc", "richinseattle, elfmaster, TMZ, B3nny, MalcolmVX, et tout le monde au vc"),
    ("debugging calls for being rad 3", "appels de débogage pour être rad 3"),
    ("jduck, botvx, mrphrazer, lauriewired", "jduck, botvx, mrphrazer, lauriewired"),
    ("0daysimpson, zeta, dnz, srsns, xcellerator, bane, h0wdy, gren", "0daysimpson, zeta, dnz, srsns, xcellerator, bane, h0wdy, gren"),
    ("Aaron DeVera", "Aaron DeVera"),
    ("Everyone in the slop pit/the Haunted Computer Club and all my homies near + far", "Tout le monde dans la fosse à déchets / le club informatique hanté et tous mes potes proches et lointains"),
    ("ilysm xoxoxoxoxoxxo", "ilysm xoxoxoxoxoxxo"),
    ("Full Source: <a href=\"./Linux.gospel.asm\">Linux.gospel.asm</a>", "Code source complet : <a href=\"./Linux.gospel.asm\">Linux.gospel.asm</a>"),
    ("Part 2: Silvio cesare's Unix VX techniques", "Partie 2 : Techniques VX Unix de Silvio Cesare"),
    ("where's my polymorphism uwu", "où est mon polymorphisme uwu"),
    ("vx", "vx"),
    ("PoC", "PoC"),
    ("asm", "asm"),
    ("ELF", "ELF"),
    ("UNIX", "UNIX"),
    ("Linux", "Linux"),
    ("virus", "virus"),
    ("viruses", "virus"),
    ("polymorphism", "polymorphisme"),
    ("metamorphism", "métamorphisme"),
    ("shellcode", "shellcode"),
    ("memfd_create", "memfd_create"),
    ("fexecve", "fexecve"),
    ("mmap", "mmap"),
    ("mprotect", "mprotect"),
    ("getdents64", "getdents64"),
    ("syscall", "appel système"),
    ("PIE", "PIE"),
    ("OEP", "OEP"),
    ("ELF", "ELF"),
    ("Phdr", "Phdr"),
    ("SHdr", "SHdr"),
    ("Ehdr", "Ehdr"),
    ("Perl", "Perl"),
     ("glibc", "glibc")
])

print("Batch done: 12.html")
