#!/usr/bin/env python3
import re
import os

def translate_file(src_path, dst_path, title_fr, translations):
    with open(src_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', content)
    
    for orig, trans in translations:
        content = content.replace(orig, trans)
    
    credit = '\n[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    elif '</pre></div>' in content:
        content = content.replace('</pre></div>', credit + '</pre></div>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {os.path.basename(src_path)}")

# 10.html - in-memory-only fd-less ELF execution (with Perl)
translate_file('/home/ubuntu/tmpout-fr/3/10.html', '/home/ubuntu/tmpout-fr/3/fr/10.html',
    'exécution ELF en mémoire uniquement (sans descripteur de fichier, avec Perl)', [
    ("in-memory-only fd-less ELF execution (with Perl)", "exécution ELF en mémoire uniquement (sans descripteur de fichier, avec Perl)"),
    ("in-memory-only fd-less ELF execution (with Perl)       ", "exécution ELF en mémoire uniquement (sans descripteur de fichier, avec Perl)       "),
    ("====[ motivation ]==============================================================", "====[ motivation ]=============================================================="),
    ("Approaches for in-memory-only ELF execution[1] typically use memfd_create() and", "Les approches pour l'exécution ELF en mémoire[1] utilisent typiquement memfd_create() et"),
    ("fexecve() syscalls which rely on the existence of file descriptors in the /proc", "fexecve() qui dépendent de l'existence de descripteurs de fichiers dans le système de fichiers /proc"),
    ("filesystem. This behaviour can be monitored and detected without much effort[2].", "Ceci peut être contrôlé et détecté sans trop d'effort[2]."),
    ("Therefore, the following questions arise:", "Par conséquent, les questions suivantes se posent :"),
    ("Is it possible to achieve in-memory-only ELF execution without using file", "Est-il possible d'atteindre une exécution ELF en mémoire sans utiliser de"),
    ("descriptors?", "descripteurs ?"),
    ("If so, can it be done using the default toolset of a common Linux distribution", "Si oui, peut-on le faire avec l'ensemble des outils par défaut d'une distribution Linux"),
    ("(i.e. without installing additional tools)?", "(c'est-à-dire sans installer d'outils supplémentaires) ?"),
    ("The answer is yes,", "La réponse est oui,"),
    ("thanks to Perl's standard modules and a bit of peek & poke.", "grâce aux modules standards de Perl et un peu de peek & poke."),
    ("This article will describe the implementation of exec_elf64.pl, a script for", "Cet article décrira l'implémentation de exec_elf64.pl, un script pour"),
    ("in-memory-only ELF execution without touching the filesystem.", "l'exécution ELF en mémoire sans toucher le système de fichiers."),
    ("This approach has the following considerations:", "Cette approche a les considérations suivantes :"),
    ("- The ELF's binary content is hardcoded into the script's source code.", "- Le contenu binaire ELF est codé en dur dans le code source du script."),
    ("- The ELF is parsed and loaded into memory.", "- L'ELF est analysé et chargé en mémoire."),
    ("- The loading process supports relocations and use of external symbols from", "- Le processus de chargement prend en charge les réadressements et l'utilisation de symboles externes du"),
    ("shared objects. In this case, external symbols are loaded from glibc.", "objets partagés. Dans ce cas, les symboles externes sont chargés depuis glibc."),
    ("- Supports x64 ELFs.", "- Prend en charge les ELF x64."),
    ("- The script is written in Perl, an interpreted language available by default", "- Le script est écrit en Perl, un langage interprété disponible par défaut"),
    ("on most Linux x64 distributions. Version 5.008001 or higher is required.", "sur la plupart des distributions Linux x64. La version 5.008001 ou supérieure est requise."),
    ("Full source code can be found at:", "Le code source complet peut être trouvé à :"),
    ("====[ preliminaries  ]=====================================================", "====[ préliminaires  ]====================================================="),
    ("The steps for loading and executing an ELF in memory can be summarized as", "Les étapes pour charger et exécuter un ELF en mémoire peuvent être résumées ainsi"),
    ("1) Read ELF's binary content.", "1) Lire le contenu binaire ELF."),
    ("2) Parse ELF's headers (sections, segments, etc).", "2) Analyser les en-têtes ELF (sections, segments, etc)."),
    ("3) Use headers information to map ELF code and data into memory.", "3) Utiliser les informations d'en-tête pour mapper le code et les données ELF en mémoire."),
    ("4) Apply relocations (including external symbols).", "4) Appliquer les réadressements (y compris les symboles externes)."),
    ("5) Execute ELF's mapped functions.", "5) Exécuter les fonctions ELF mappées."),
    ("Each of these steps will be discussed in the next sections,", "Chacune de ces étapes sera discutée dans les sections suivantes,"),
    ("considering the following ELF object:", "en considérant l'objet ELF suivant :"),
    ("====[ part 1: read ELF ]========================================================", "====[ partie 1 : lire ELF ]========================================================"),
    ("The usual approach for opening a file and perform I/O operations on it", "L'approche usuelle pour ouvrir un fichier et effectuer des opérations d'entrée/sortie"),
    ("(such as read, write, seek, etc.) is by specifying a path to an existing file on the", "(telles que read, write, seek, etc.) consiste à spécifier un chemin vers un fichier"),
    ("filesystem or by specifying a file descriptor,", "existant sur le système de fichiers ou en spécifiant un descripteur de fichier,"),
    ("which in some cases may represent an \"anonymous\" or memory-only file[1].", "qui peut dans certains cas représenter un fichier \"anonyme\" ou en mémoire seulement[1]."),
    ("These options require interaction with the regular filesystem and proc filesystem respectively.", "Ces options nécessitent une interaction avec le système de fichiers régulier et le système de fichiers proc respectivement."),
    ("However, Perl provides an alternative method to open a filehandle by using a", "Cependant, Perl fournit une méthode alternative pour ouvrir un filehandle en utilisant une"),
    ("reference to a scalar variable instead of a filename.", "référence à une variable scalaire au lieu d'un nom de fichier."),
    ("The above code creates a filehandle $fh using a reference to the string $str", "Le code ci-dessus crée un filehandle $fh en utilisant une référence à la chaîne $str"),
    ("and successfully reads 5 bytes into $buff by using the read() function.", "et lit avec succès 5 octets dans $buff en utilisant la fonction read()."),
    ("This method can also be applied to open the contents of an ELF object from a string", "Cette méthode peut également être appliquée pour ouvrir le contenu d'un objet ELF à partir d'une chaîne"),
    ("reference and perform I/O operations on it.", "de référence et effectuer des opérations d'entrée/sortie sur lui."),
    ("First, the read_elf() subroutine is defined as follows:", "Premièrement, la sous-routine read_elf() est définie comme suit :"),
    ("The string $code and the filehandle $fh are returned since both will be used", "La chaîne $code et le filehandle $fh sont retournés car les deux seront utilisés"),
    ("later during the parsing and mapping processes.", "plus tard pendant les processus d'analyse et de cartographie."),
    ("To create the string $code the", "Pour créer la chaîne $code,"),
    ("following perl one-liner is used:", "l'utilisation suivante de perl est utilisée :"),
    ("The command above generates a string $code that contains the binary data of the", "La commande ci-dessus génère une chaîne $code qui contient les données binaires de l'objet ELF."),
    ("ELF object. The string $code can then be included in the get_code() subroutine:", "La chaîne $code peut ensuite être incluse dans la sous-routine get_code() :"),
    ("For simplicity, the get_code() subroutine is defined at the end of the", "Pour plus de simplicité, la sous-routine get_code() est définie à la fin du"),
    ("exec_elf64.pl script to make it easy to replace the string $code by a new one.", "script exec_elf64.pl pour faciliter le remplacement de la chaîne $code par une nouvelle."),
    ("====[ part 2: parse ELF ]=======================================================", "====[ partie 2 : analyser ELF ]======================================================="),
    ("Perl does not provide an standard module for parsing ELFs.", "Perl ne fournit pas de module standard pour l'analyse des ELF."),
    ("However, the unpack() function can be used to extract the ELF's binary content", "Cependant, la fonction unpack() peut être utilisée pour extraire le contenu binaire ELF"),
    ("based on a set of fixed data templates[3]:", "basée sur un ensemble de modèles de données fixes[3] :"),
    ("an unsigned char value (1 byte).", "une valeur unsigned char (1 octet)."),
    ("a string with arbitrary binary data (1 byte).", "une chaîne avec des données binaires arbitraires (1 octet)."),
    ("a null byte.", "un octet nul."),
    ("an unsigned short value (2 bytes).", "une valeur unsigned short (2 octets)."),
    ("a signed integer value (4 bytes).", "un entier signé (4 octets)."),
    ("an unsigned integer value (4 bytes).", "un entier non signé (4 octets)."),
    ("a signed quad value (8 bytes).", "une valeur quad signée (8 octets)."),
    ("An unsigned quad value (8 bytes).", "Une valeur quad non signée (8 octets)."),
    ("The ELF header, section header table, symbol table, string table and relocations", "L'en-tête ELF, la table des en-têtes de section, la table des symboles, la table des"),
    ("are parsed based mostly on the Linux referenced specifications[4][5][6][7] and", "chaînes et les relocalisations sont analysés principalement basés sur les"),
    ("the logic implemented in readelf.pl[8].", "spécifications référencées Linux[4][5][6][7] et la logique implémentée dans readelf.pl[8]."),
    ("two auxiliary subroutines", "deux sous-routines auxiliaires"),
    ("for reading/unpacking data and for creating hashes", "pour la lecture/déballage de données et pour la création de hachages"),
    ("associated to the parsed headers,", "associés aux en-têtes analysés,"),
    ("respectively.", "respectivement."),
    ("Then, the initial ELF header is read and parsed as follows (using the field names defined in @e_keys):", "Ensuite, l'en-tête ELF initial est lu et analysé comme suit (en utilisant les noms de champ définis dans @e_keys) :"),
    ("the section header table is represented by the @shtab array", "La table des en-têtes de section est représentée par le tableau @shtab"),
    ("and its entries are represented as hashes", "et ses entrées sont représentées sous forme de hachages"),
    ("based on the field names defined in the @sh_keys array.", "basés sur les noms de champ définis dans le tableau @sh_keys."),
    ("Additionally,", "De plus,"),
    ("when a section header table entry of sh_type = 3 (STRTAB) is", "lorsqu'une entrée de la table des en-têtes de section de sh_type = 3 (STRTAB) est"),
    ("found,", "trouvée,"),
    ("the $efh filehandle position is set to its sh_offset for reading the", "la position du filehandle $efh est définie sur son sh_offset pour la lecture du"),
    ("entry's content and store it in %strtab,", "contenu de l'entrée et le stocker dans %strtab,"),
    ("the hash that represents the string table.", "le hachage qui représente la table de chaînes."),
    ("The section header table is parsed a second time to retrieve the name of each", "La table des en-têtes de section est analysée une seconde fois pour récupérer le"),
    ("entry based on the contents of the string table.", "nom de chaque entrée basé sur le contenu de la table de chaînes."),
    ("The indexes for the text, data,", "Les index pour le texte, les données,"),
    ("symtab, rodata and rela.text sections (in @shtab) are stored for direct access", "symtab, rodata et rela.text (dans @shtab) sont stockés pour un accès direct"),
    ("to such sections later in the parsing and mapping processes.", "à ces sections plus tard dans les processus d'analyse et de cartographie."),
    ("Next, the symbol table is read and parsed as follows:", "Ensuite, la table des symboles est lue et analysée comme suit :"),
    ("====[ part 3: map ELF ]=========================================================", "====[ partie 3 : mapper ELF ]========================================================="),
    ("Most of the mapping process is based on [9] which consists basically in three", "La majeure partie du processus de cartographie est basée sur [9] qui se compose essentiellement de trois"),
    ("steps:", "étapes :"),
    ("Memory mapping", "Cartographie mémoire"),
    ("Copying data into mapped area", "Copie de données dans la zone mappée"),
    ("Memory access protection", "Protection d'accès mémoire"),
    ("Memory mapping can be achieved by using Perl's syscall() to call mmap:", "La cartographie mémoire peut être réalisée en utilisant syscall() de Perl pour appeler mmap :"),
    ("Where:", "Où :"),
    ("9 is the number of the mmap syscall in Linux x86_64.", "9 est le numéro de l'appel système mmap sous Linux x86_64."),
    ("$addr is the starting address for the new mapping.", "$addr est l'adresse de départ pour le nouvelle cartographie."),
    ("If 0, mmap will choose a suitable address and return it.", "Si 0, mmap choisira une adresse appropriée et la retournera."),
    ("$size is the size of the mapping.", "$size est la taille de la cartographie."),
    ("$protect is an integer that indicates the memory protection of the mapping.", "$protect est un entier qui indique la protection mémoire de la cartographie."),
    ("Possible values can be checked at [10].", "Les valeurs possibles peuvent être vérifiées à [10]."),
    ("In this case the value", "Dans ce cas, la valeur"),
    ("is used.", "est utilisée."),
    ("$flags is an integer that indicates visibility of mapping changes and the", "$flags est un entier qui indique la visibilité des changements de cartographie et l'utilisation de"),
    ("use of files.", "fichiers."),
    ("The remaining parameters are related to file mapping and can be ignored by using", "Les paramètres restants sont liés à la cartographie de fichiers et peuvent être ignorés en utilisant"),
    ("the values -1 and 0.", "les valeurs -1 et 0."),
    ("mmap will return the starting address of the mapped area on success and -1 on failure.", "mmap retournera l'adresse de départ de la zone mappée en cas de réussite et -1 en cas d'échec."),
    ("Unlike mmap,", "Contrairement à mmap,"),
    ("there is no syscall for copying data into memory.", "il n'y a pas d'appel système pour copier des données en mémoire."),
    ("There is also no built-in function in Perl for copying raw data into memory.", "Il n'y a également aucune fonction intégrée dans Perl pour copier des données brutes en mémoire."),
    ("However, there are some memory tricks that can be used to that end:", "Cependant, il existe quelques astuces mémoire qui peuvent être utilisées à cet effet :"),
    ("the code used for peek & poke is from [11], a script for syscall/shellcode", "le code utilisé pour le peek & poke vient de [11], un script pour l'injection"),
    ("injection in OSX,", "de syscall/shellcode sous OSX,"),
    ("which allows to copy arbitrary data $bytes into a memory", "qui permet de copier des données arbitraires $bytes dans une mémoire"),
    ("address $location of choice.", "adresse $location de choix."),
    ("NOTE: some comments and checks were redacted for simplicity;", "NOTE : certains commentaires et vérifications ont été supprimés pour simplifier ;"),
    ("the remaining comments are from the original author)", "les commentaires restants proviennent de l'auteur original)"),
    ("In short,", "En bref,"),
    ("poke() modifies Perl's internal data types to force the creation of", "poke() modifie les types de données internes de Perl pour forcer la création d'une"),
    ("a temporary variable pointing to a string located at $location and then change", "variable temporaire pointant vers une chaîne située à $location puis change"),
    ("the string's content with $bytes.", "le contenu de la chaîne avec $bytes."),
    ("To have a better understanding of how poke() works it's necessary to dig deeper into advanced concepts of Perl internals,", "Pour mieux comprendre le fonctionnement de poke(), il est nécessaire de plonger plus profondément dans des concepts avancés des"),
    ("which is beyond the scope of this article.", "internes de Perl, ce qui est au-delà du cadre de cet article."),
    ("The reader can check [12][13] for more information.", "Le lecteur peut vérifier [12][13] pour plus d'informations."),
    ("Similar to memory mapping,", "Similaire à la cartographie mémoire,"),
    ("Perl's syscall() is used to call mprotect:", "syscall() de Perl est utilisé pour appeler mprotect :"),
    ("10 is the number of the mprotect syscall in Linux x86_64.", "10 est le numéro de l'appel système mprotect sous Linux x86_64."),
    ("$addr an $size define the interval of the mapping area where access", "$addr et $size définissent l'intervalle de la zone mappée où les protections"),
    ("protections will be updated.", "d'accès seront mises à jour."),
    ("$protect is an integer that indicates the memory protection[14] for", "$protect est un entier qui indique la protection mémoire[14] pour"),
    ("the specified interval.", "l'intervalle spécifié."),
    ("mprotect will return 0 on success and -1 on failure.", "mprotect retournera 0 en cas de réussite et -1 en cas d'échec."),
    ("The mapping process can now be done following the steps described on [9].", "Le processus de cartographie peut maintenant être effectué en suivant les étapes décrites dans [9]."),
    ("First,", "Premièrement,"),
    ("the ELF object code is mapped and its content copied into the mapped area.", "le code de l'objet ELF est mappé et son contenu est copié dans la zone mappée."),
    ("Then the text, data, and rodata segments are mapped and copied into memory next", "Ensuite, les segments texte, données et rodata sont mappés et copiés en mémoire"),
    ("to each other,", "les uns à côté des autres,"),
    ("along with an auxiliary jump table (described later).", "avec une table de saut auxiliaire (décrite plus tard)."),
    ("Given that the $code variable is a string that contains the binary content", "Étant donné que la variable $code est une chaîne qui contient le contenu binaire"),
    ("of the ELF object (as discussed in part 1),", "de l'objet ELF (comme discuté dans la partie 1),"),
    ("the content of each segment can be obtained by extracting a substring of $code based on their sh_offset and sh_size values.", "le contenu de chaque segment peut être obtenu en extrayant une sous-chaîne de $code basée sur leurs valeurs sh_offset et sh_size."),
    ("After this the relocations are applied and the memory access protections are set", "Après cela, les réadressements sont appliqués et les protections d'accès mémoire sont"),
    ("for the text segment,", "fixées pour le segment texte,"),
    ("rodata segment and jump table.", "le segment rodata et la table de saut."),
    ("====[ part 4: relocations and external symbols ]================================", "====[ partie 4 : réadressements et symboles externes ]================================"),
    ("Similar to the mapping process,", "Similaire au processus de cartographie,"),
    ("relocations are performed following the steps", "les réadressements sont effectués en suivant les étapes"),
    ("described in [15] which only considers relocations of type R_X86_64_PLT32 = 4", "décrites dans [15] qui ne considère que des réadressements de type R_X86_64_PLT32 = 4"),
    ("and R_X86_64_PC32 = 2 for the text, data and rodata segments.", "et R_X86_64_PC32 = 2 pour les segments texte, données et rodata."),
    ("Once again,", "Une fois de plus,"),
    ("the use of poke() allows copying the calculated relocation address into the", "l'utilisation de poke() permet de copier l'adresse de réadressage calculée dans l'adresse"),
    ("original patch offset address.", "de décalage de correctif original."),
    ("External symbols,", "Symboles externes,"),
    ("identified by having st_shndx = 0 (UND),", "identifiés par st_shndx = 0 (UND),"),
    ("are handled during the relocation process following the steps described in [16].", "sont gérés pendant le processus de relocalisation en suivant les étapes décrites dans [16]."),
    ("To achieve that,", "Pour réaliser cela,"),
    ("a simplified PLT/GOT is implemented by using an auxiliary jump table to resolve", "un PLT/GOT simplifié est implémenté en utilisant une table de saut auxiliaire pour résoudre"),
    ("external references.", "les références externes."),
    ("Each entry in the jump table contains:", "Chaque entrée de la table de saut contient :"),
    ("The address of the external symbol (8 bytes).", "L'adresse du symbole externe (8 octets)."),
    ("A fixed jump instruction", "Une instruction de saut fixe"),
    ("\"\\xff\\x25\\xf2\\xff\\xff\\xff\" (6 bytes).", "\"\\xff\\x25\\xf2\\xff\\xff\\xff\" (6 octets)."),
    ("For simplicity,", "Pour plus de simplicité,"),
    ("the jump table is implemented by mapping N*14 bytes after the rodata segment", "la table de saut est implémentée en mappant N*14 octets après le segment rodata"),
    ("and each entry on the jump table starts at position i*14,", "et chaque entrée de la table de saut commence à la position i*14,"),
    ("where 'N' is the number of external symbols and 'i' is a value between 0 and N-1 that", "où 'N' est le nombre de symboles externes et 'i' est une valeur entre 0 et N-1 qui"),
    ("represents the i-th external symbol found during the parsing process.", "représente le i-ème symbole externe trouvé pendant le processus d'analyse."),
    ("Given that the jump table is close enough in memory to the rest of the sections,", "Étant donné que la table de saut est assez proche en mémoire du reste des sections,"),
    ("the relocation for an external symbol must be calculated against the fixed jump", "le réadressage pour un symbole externe doit être calculé par rapport à l'instruction de saut fixe"),
    ("instruction in its jump table's entry,", "dans son entrée de la table de saut,"),
    ("which performs a backwards jump (-14 bytes) to the start of the entry,", "qui effectue un saut arrière (-14 octets) vers le début de l'entrée,"),
    ("where the actual address of the external symbol is stored.", "où l'adresse réelle du symbole externe est stockée."),
    ("The external symbol address can be obtained by using Perl's DynaLoader standard", "L'adresse du symbole externe peut être obtenue en utilisant le module standard DynaLoader de Perl qui"),
    ("module that \"Dynamically load C libraries into Perl code\"[17].", "« charge dynamiquement les bibliothèques C dans le code Perl »[17]."),
    ("First,", "Premièrement,"),
    ("a library reference for looking up the symbol must be loaded with dl_load_file().", "une référence de bibliothèque pour la recherche du symbole doit être chargée avec dl_load_file()."),
    ("In this case the glibc shared object is used:", "Dans ce cas, l'objet partagé glibc est utilisé :"),
    ("The external symbol address is looked up using dl_find_symbol() with the library", "L'adresse du symbole externe est recherchée à l'aide de dl_find_symbol() avec la bibliothèque"),
    ("reference and the symbol's name as parameters.", "de référence et le nom du symbole en tant que paramètres."),
    ("The jump table entry is then built by packing the external address in little-endian order", "L'entrée de la table de saut est ensuite construite en compressant l'adresse externe dans l'ordre",),
    ("and appending the jump instruction.", "et en ajoutant l'instruction de saut."),
    ("Finally,", "Enfin,"),
    ("the jump table entry is copied into memory at the position $jmptab_ndx calculated before.", "l'entrée de la table de saut est copiée en mémoire à la position $jmptab_ndx calculée précédemment."),
    ("After this the relocation process is", "Après cela, le processus de relocalisation est"),
    ("resumed using $jmptab_ndx + 8 as the symbol address for the relocation formula.", "relogé en utilisant $jmptab_ndx + 8 comme adresse de symbole pour la formule de relocalisation."),
    ("====[ part 5: execute ELF ]===================================================", "====[ partie 5 : exécuter ELF ]==================================================="),
    ("Perl's DynaLoader standard module is used once again to execute the ELF's mapped", "Le module standard DynaLoader de Perl est utilisé à nouveau pour exécuter les"),
    ("functions.", "fonctions mappées ELF."),
    ("In addition to loading external libraries and finding symbols,", "En plus du chargement de bibliothèques externes et de la recherche de symboles,"),
    ("DynaLoader can install \"external subroutines\" by using dl_install_xsub():", "DynaLoader peut installer des « sous-routines externes » en utilisant dl_install_xsub () :"),
    ("This method creates a new Perl external subroutine named $perl_name using", "Cette méthode crée une nouvelle sous-routine externe Perl nommée $perl_name en utilisant"),
    ("$symref as a pointer to the function which implements the routine.", "$symref comme pointeur vers la fonction qui implémente la routine."),
    ("On success,", "En cas de réussite,"),
    ("dl_install_xsub() returns a reference to the \"installed function\".", "dl_install_xsub() retourne une référence à la « fonction installée »."),
    ("According to the DynaLoader documentation:", "Selon la documentation de DynaLoader :"),
    ("It must be stressed that the DynaLoader,", "Il faut souligner que DynaLoader,"),
    ("by itself,", "par lui-même,"),
    ("is practically useless", "est pratiquement inutile"),
    ("for accessing non-Perl libraries because it provides almost no Perl-to-C", "pour accéder aux bibliothèques non-Perl car il fournit presque aucune"),
    ("'glue'.", "colle Perl-vers-C'. "),
    ("There is, for example, no mechanism for calling a C library function or supplying arguments", "Il n'existe, par exemple, aucun mécanisme pour appeler une fonction de bibliothèque C ou fournir des arguments"),
    ("However, it is possible to use dl_install_xsub() providing the st_value of an ELF's mapped function as pointer and successfully achieve execution.", "Cependant, il est possible d'utiliser dl_install_xsub() en fournissant la valeur st_value d'une fonction ELF mappée comme pointeur et d'obtenir avec succès l'exécution."),
    ("In this case the name of the function to be executed is \"main\". Finally,", "Dans ce cas, le nom de la fonction à exécuter est « main ». Enfin,"),
    ("the main logic of the script can be reduced to:", "la logique principale du script peut être réduite à :"),
    ("And then:", "Et ensuite :"),
    ("====[ after math  ]=============================================================", "====[ après coup  ]============================================================="),
    ("To achieve complete fd-less execution,", "Pour obtenir une exécution complète sans descripteur de fichier,"),
    ("one option is encoding the script's source code in base64 on a remote host,", "une option est de coder le code source du script en base64 sur un hôte distant,"),
    ("decode it on the target machine and then", "le décoder sur la machine cible et ensuite"),
    ("pipe it to the perl interpreter:", "le rediriger vers l'interpréteur perl :"),
    ("on a remote host", "sur un hôte distant"),
    ("on the target machine", "sur la machine cible"),
    ("On the other hand,", "D'un autre côté,"),
    ("to make it easier to test and debug exec_elf64.pl with other", "pour faciliter le test et le débogage de exec_elf64.pl avec d'autres"),
    ("ELFs objects the read_elf() subroutine can be adapted to open regular files as follows:", "objets ELF, la sous-routine read_elf() peut être adaptée pour ouvrir des fichiers réguliers comme suit :"),
    ("For completeness an additional test is performed with a more elaborated ELF,", "Pour la complétude, un test supplémentaire est effectué avec un ELF plus élaboré,"),
    ("in this case,", "dans ce cas,"),
    ("the \"self-mutating x86_64 C program\"[18] which implements", "le programme C « auto-mutant x86_64 »[18] qui implémente"),
    ("self-mutating code to spawn a /bin/sh shell:", "du code auto-mutant pour lancer un shell /bin/sh :"),
    ("====[ extra mile  ]=============================================================", "====[ effort supplémentaire ]============================================================="),
    ("The original script for syscall/shellcode injection in OSX[11] can be easily", "Le script original pour l'injection de syscall/shellcode sous OSX[11] peut facilement être"),
    ("adapted for Linux x64 by using the mmap() and mprotect() subroutines described", "adapté pour Linux x64 en utilisant les sous-routines mmap() et mprotect() décrites"),
    ("in part 3,", "dans la partie 3,"),
    ("achieving assembly code execution with the use of DynaLoader and", "obtenant l'exécution de code assembleur avec l'utilisation de DynaLoader et"),
    ("peek & poke.", "peek & poke."),
    ("BEGIN code.s", "BEGIN code.s"),
    ("END code.s", "END code.s"),
    ("Then, using the hexadecimal representation of the text section of code.o:", "Ensuite, en utilisant la représentation hexadécimale de la section texte de code.o :"),
    ("END CODE", "FIN DU CODE"),
    ("Which can also be executed fd-less by using the approach mentioned before", "Ce qui peut également être exécuté sans descripteur de fichier en utilisant l'approche mentionnée ci-dessus"),
    ("(base64 encoding and decoding).", "(codage et décodage en base64)."),
    ("====[ references  ]=============================================================", "====[ références  ]============================================================="),
    ("====[ source code ]=============================================================", "====[ code source ]============================================================="),
    ("memory", "mémoire"),
    ("execution", "exécution"),
    ("ELF", "ELF"),
    ("Perl", "Perl"),
    ("Linux", "Linux"),
    ("syscall", "appel système"),
    ("mmap", "mmap"),
    ("mprotect", "mprotect"),
    ("shellcode", "shellcode"),
    ("DynaLoader", "DynaLoader"),
    ("peek", "peek"),
    ("poke", "poke"),
])

print("Batch done: 10.html")
