#!/usr/bin/env python3
import re
import os

def translate_file(src_path, dst_path, title_fr, translations):
    with open(src_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'<title>.*?</title>', f'<title>{title_fr}</title>', content)
    
    for orig, trans in translations:
        content = content.replace(orig, trans)
    
    credit = '\n[ Traduction par Tedsig42 ]\n'
    if '</pre></div></body>' in content:
        content = content.replace('</pre></div></body>', credit + '</pre></div></body>')
    elif '</pre></div>' in content:
        content = content.replace('</pre></div>', credit + '</pre></div>')
    
    with open(dst_path, 'w') as f:
        f.write(content)
    
    print(f"Translated: {os.path.basename(src_path)}")

# 06.html - Concealing Namespaces Within a File Descriptor
translate_file('/home/ubuntu/tmpout-fr/3/06.html', '/home/ubuntu/tmpout-fr/3/fr/06.html',
    "Cacher des espaces de noms au sein d'un descripteur de fichier", [
    ("Concealing Namespaces Within a File Descriptor", "Cacher des espaces de noms au sein d'un descripteur de fichier"),
    ("===[ Abstract ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Résumé ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Introduction: What Are Linux Namespaces Anyway? ]~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Introduction : Qu'est-ce que sont les espaces de noms Linux ? ]~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("In this paper, we will delve into several techniques that can help us hide an", "Dans cet article, nous allons approfondir plusieurs techniques qui peuvent nous aider à cacher un"),
    ("entire namespace within a seemingly innocent file descriptor. This can be", "espace de noms entier au sein d'un descripteur de fichier apparemment innocup."),
    ("particularly useful during the post-exploitation phase when we need a concealed", "Ceci peut être particulièrement utile pendant la phase post-exploitation quand nous avons besoin d'un tunnel"),
    ("tunnel.", "cach."),
    ("We will explore some aspects related to namespaces. We will begin by discussing", "Nous explorerons certains aspects liés aux espaces de noms. Nous commencerons par discuter"),
    ("how the user can interface with namespaces and how they are referenced. We will", "de la façon dont l'utilisateur peut interagir avec les espaces de noms et comment ils sont référencés."),
    ("then look at the technique of hiding a network namespace within a single socket", "Nous verrons ensuite la technique de cacher un espace de noms réseau au sein d'une socket unique"),
    ("and explore how inotify can be used as a path obfuscator. Throughout our", "et comment inotify peut être utilisé comme obfuscateur de chemin. Pendant notre exploration,"),
    ("exploration, we will also examine the available detection mechanisms. Finally,", "nous examinerons également les mécanismes de détection disponibles. Enfin,"),
    ("we will demonstrate the practical application of these techniques by creating a", "nous démontrerons l'application pratique de ces techniques en créant un"),
    ("simple kernelspace \"reverse-proxy\" within a dormant userspace process.", "simple \"reverse-proxy\" dans l'espace noyau au sein d'un processus en mode utilisateur dormant."),
    ("===[ Interacting with Namespaces ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Interagir avec les espaces de noms ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("Here is a crash course on working with namespaces from userspace [ref2]:", "Voici un cours accéléré sur le travail avec les espaces de noms depuis l'espace utilisateur [ref2] :"),
    ("===[ Death by Lack of Reference: How Namespaces Die? ]~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ La mort par manque de référence : comment les espaces de noms meurent ? ]~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Hiding a Network Namespace within a Socket ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Cacher un espace de noms réseau au sein d'une socket ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Detecting a Network Namespace within a Socket ]~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Détecter un espace de noms réseau au sein d'une socket ]~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Hiding a Namespace with an Inotify Watch ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Cacher un espace de noms avec une surveillance inotify ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Battle of the Techniques: Socket vs Inotify ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Bataille des techniques : Socket vs Inotify ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Honorable mention: Referring to a Namespace via Bind-Mount ]~~~~~~~~~~~~~~", "===[ Mention honorifique : Référence à un espace de noms via bind-mount ]~~~~~~~~~~~~~~"),
    ("===[ Peering into the Abyss: Userspace Information About Namespaces ]~~~~~~~~~~", "===[ Plonger dans le gouffre : Informations sur les espaces de noms en espace utilisateur ]~~~~~~~~~~"),
    ("===[ Side quest: Process Resiliency ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Quête parallèle : Résilience du processus ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Good Luck, I'm Behind 7 Proxies ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Bonne chance, je suis derrière 7 proxies ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ Conclusion ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Conclusion ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("===[ References ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "===[ Références ]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"),
    ("Linux namespaces are simple in concept, yet complicated in implementation.", "Les espaces de noms Linux sont simples en concept, mais compliqués dans la mise en œuvre."),
    ("Namespaces serve as fundamental building blocks for containers [ref2], utilized", "Les espaces de noms servent de blocs de construction fondamentaux pour les conteneurs [ref2], utilisés"),
    ("by platforms like Docker and LXC. They provide a mechanism to alter a process'", "par des plateformes comme Docker et LXC. Ils fournissent un mécanisme pour altérer la perspective"),
    ("perspective of the system. The true power of namespaces lies in their ability", "d'un processus du système. Le véritable pouvoir des espaces de noms réside dans leur capacité"),
    ("to function independently.", "à fonctionner indépendamment."),
    ("The main downfall of namespaces or Linux in general is their limited", "Le principal revers des espaces de noms ou de Linux en général est leur observabilité limitée."),
    ("observability. And I'm not talking about tracing, which is nearly perfect.", "Et je ne parle pas de la trace, qui est presque parfaite."),
    ("What I am referring to is making a good assessment about the state of the", "Ce que je veux dire, c'est établir une bonne évaluation de l'état du système en cours d'exécution,"),
    ("running system, especially for those who are not kernel developers.", "surtout pour ceux qui ne sont pas des développeurs noyau."),
    ("In this article, we will primarily focus on the network namespace due to its", "Dans cet article, nous nous concentrerons principalement sur l'espace de noms réseau en raison de ses"),
    ("highly practical applications.", "applications hautement pratiques."),
    ("Sockets have three intriguing aspects:", "Les sockets ont trois aspects intrigants :"),
    ("1. They are (more or less) associated with a network namespace.", "1. Ils sont (plus ou moins) associés à un espace de noms réseau."),
    ("2. They are a commonly used functionality. (No suspicion there, right?)", "2. Ils sont une fonctionnalité couramment utilisée. (Pas de suspicion là-dessus, non ?)"),
    ("3. We can retrieve the network namespace associated with them.", "3. Nous pouvons récupérer l'espace de noms réseau associé."),
    ("Neato! We are effectively holding the entire network namespace with just one", "Génial ! Nous tenons effectivement l'espace de noms réseau entier avec une seule socket."),
    ("socket. Let's take it a step further and create something more practical.", "Prenons-le un cran plus loin et créons quelque chose de plus pratique."),
    ("If we want to restrict an application's network access to a", "Si nous voulons restreindre l'accès réseau d'une application à un"),
    ("specific network, we can easily create a new network namespace, bind a (SOCKS)", "réseau spécifique, nous pouvons facilement créer un nouvel espace de noms réseau, lier une socket (SOCKS)"),
    ("socket as the sole interface to the external world, create firewall rules for", "comme interface unique vers le monde externe, créer des règles de pare-feu pour"),
    ("redirection, and move the process into the network namespace.", "la redirection, et déplacer le processus dans l'espace de noms réseau."),
    ("In this scenario, if the (SOCKS) socket stops working, the application will be", "Dans ce scénario, si la socket (SOCKS) cesse de fonctionner, l'application ne pourra pas"),
    ("unable to access any other network", "accéder à aucun autre réseau"),
    ("Don't worry, we will make use of them later on.", "Ne t'inquiète pas, nous les utiliserons plus tard."),
    ("The lifetime of a namespace mostly depends on the last standing process that is", "La durée de vie d'un espace de noms dépend principalement du dernier processus"),
    ("referencing it. In most cases, when the referencing process terminates, any", "qui le référence. Dans la plupart des cas, lorsque le processus référant se termine,"),
    ("namespaces without any reference are automatically removed.", "les espaces de noms sans aucune référence sont automatiquement supprimés."),
    ("Each namespace has its own reference counter(s). When a new namespace is", "Chaque espace de noms a son propre compteur de référence(s). Lorsqu'un nouvel espace"),
    ("created, the counter is set to 1, because the process calling the syscall is", "de noms est créé, le compteur est initialisé à 1, car le processus appelant"),
    ("referencing it.", "l'appel système le référence."),
    ("The increment and decrement operations are primarily performed by these inline", "Les opérations d'incrément et de décrément sont principalement effectuées par ces fonctions en ligne"),
    ("A socket can still draw attention as it indicates network communication.", "Une socket peut toujours attirer l'attention car elle indique une communication réseau."),
    ("Ultimately, all we want is a reference to our network namespaces with minimal", "En fin de compte, tout ce que nous voulons, c'est une référence à nos espaces de noms réseau"),
    ("information about the original file descriptor.", "avec des informations minimales sur le descripteur de fichier original."),
    ("Is that too much to ask for?", "Est-ce demander trop ?"),
    ("Maybe not. In fact, there is a slick way to hold such a reference using", "Peut-être pas. En fait, il existe une façon élégante de tenir une telle référence"),
    ("''inotify(7)''.", "en utilisant ''inotify(7)''."),
    ("Inotify provides a mechanism for monitoring file system events on a specified", "Inotify fournit un mécanisme pour surveiller les événements du système de fichiers sur un chemin"),
    ("path [ref10]. It works by opening a file path and returning a special inotify", "spécifié [ref10]. Il fonctionne en ouvrant un chemin de fichier et en retournant"),
    ("file descriptor known as a watch descriptor.", "un descripteur de fichier inotify spécial appelé descripteur de surveillance."),
    ("We can use this watch descriptor to listen for events", "Nous pouvons utiliser ce descripteur de surveillance pour écouter les événements"),
    ("Once an inotify watch is initialized, it finds the inode number for the file", "Une fois qu'une surveillance inotify est initialisée, elle trouve le numéro d'inode du fichier"),
    ("path being watched. However, after initialization, the path name itself becomes", "surveillé. Cependant, après l'initialisation, le nom du chemin devient inutile,"),
    ("unnecessary, and subsequent operations are performed on the inode.", "et les opérations suivantes sont effectuées sur l'inode."),
    ("Amazing! This technique not only increases the reference counter for the", "Magnifique ! Cette technique augmente non seulement le compteur de référence pour"),
    ("specific namespace or file descriptor but also effectively hides the reference", "l'espace de noms ou le descripteur de fichier spécifique, mais cache aussi efficacement"),
    ("itself.", "la référence elle-même."),
    ("A similar approach can be applied to a socket, although not through", "Une approche similaire peut être appliquée à une socket, bien pas via"),
    ("bind-mounting since ''sockfs'' is not mountable in userspace [ref14].", "le bind-mount car ''sockfs'' n'est pas montable dans l'espace utilisateur [ref14]."),
    ("In general, Linux does not provide a lot of information about the kernelspace,", "En général, Linux ne fournit pas beaucoup d'informations sur l'espace noyau,"),
    ("and the available information about namespaces is no exception.", "et les informations disponibles sur les espaces de noms ne font pas exception."),
    ("Simply scanning the ''/proc/'' and ''/sys/'' directories is not sufficient,", "Une simple analyse des répertoires ''/proc/'' et ''/sys/'' n'est pas suffisante,"),
    ("the information provided by syscalls is sparse, and processing ''/proc/kcore'' is", "les informations fournies par les appels système sont rares, et le traitement de ''/proc/kcore''"),
    ("challenging due to the complexity and evolving structure of kernel structures.", "est difficile en raison de la complexité et de l'évolution des structures du noyau."),
    ("Active logging is a viable option.", "La journalisation active est une option viable."),
    ("Linux offers powerful instrumentation", "Linux offre des capacités d'instrumentation puissantes,"),
    ("capabilities, such as kprobes [ref16], which can be used to log the creation", "comme les kprobes [ref16], qui peuvent être utilisées pour consigner la création"),
    ("and cleanup of namespaces on the system. This logging mechanism can help", "et le nettoyage des espaces de noms sur le système. Ce mécanisme de journalisation"),
    ("identify active namespaces and determine their original parent processes.", "peut aider à identifier les espaces de noms actifs et déterminer leurs processus parents d'origine."),
    ("However, it is important to note that when a process forks, its child inherits all", "Cependant, il est important de noter que lorsqu'un processus fork, son enfant hérite de"),
    ("the namespaces from its parent. The same can be true for ''execve(2)'' when", "tous les espaces de noms de son parent. Il en va de même pour ''execve(2)''"),
    ("file descriptors have not been set with the ''O_CLOEXEC'' flag.", "lorsque les descripteurs de fichiers n'ont pas été définis avec le drapeau ''O_CLOEXEC''."),
    ("Regardless, let's explore some options that are available to us:", "Quoi qu'il en soit, explorons certaines options qui nous sont disponibles :"),
    ("The PID actively using a namespace can be found by dereferencing the", "Le PID utilisant activement un espace de noms peut être trouvé en déréférençant le"),
    ("''/proc/PID/ns/*'' path:", "chemin ''/proc/PID/ns/*'' :"),
    ("The opened file descriptor of the namespace can be obtained by accessing the", "Le descripteur de fichier ouvert de l'espace de noms peut être obtenu en accédant au"),
    ("''/proc/PID/fd/*'' path:", "chemin ''/proc/PID/fd/*'' :"),
    ("The ''nsfs'' bind-mount can be found by inspecting the", "Le bind-mount ''nsfs'' peut être trouvé en inspectant les"),
    ("''/proc/PID/mountinfo'' files:", "fichiers ''/proc/PID/mountinfo'' :"),
    ("The ''tcpdump'' tool on the host can capture and view all traffic on the", "L'outil ''tcpdump'' sur l'hôte peut capturer et visualiser tout le trafic sur l'interface"),
    ("interface (even when using macvlan in private mode within our network", "(même lors de l'utilisation de macvlan en mode privé dans notre espace de noms réseau)."),
    ("Moreover, with eBPF, we may have the capability to trace the exact", "De plus, avec eBPF, nous pouvons avoir la capacité de tracer la source exacte"),
    ("source of the traffic.", "du trafic."),
    ("Monitoring kernel functions with kprobes (e.g., using eBPF, perf, ftrace) is", "La surveillance des fonctions du noyau avec des kprobes (par ex., en utilisant eBPF, perf, ftrace)"),
    ("a viable approach, although it does have some flaws.", "est une approche viable, bien qu'elle ait quelques défauts."),
    ("One of the main challenges is that certain functions are inlined and cannot be", "L'un des principaux défis est que certaines fonctions sont inline et ne peuvent pas"),
    ("directly instrumented (for instance, initialization and cleanup of the UTS", "être directement instrumentées (par exemple, l'initialisation et le nettoyage de"),
    ("namespace [ref17]). However, there are still several functions that are suitable", "l'espace de noms UTS [ref17]). Cependant, il existe encore plusieurs fonctions appropriées"),
    ("and can be effectively instrumented.", "qui peuvent être efficacement instrumentées."),
    ("Extracting data from the relevant structures within the ''/proc/kcore''", "L'extraction de données à partir des structures pertinentes dans le pseudo-fichier ''/proc/kcore''"),
    ("pseudo-file can be an excellent source of truth (unless the system is", "peut être une excellente source de vérité (à moins que le système ne soit"),
    ("compromised ;)). However, one significant drawback is the requirement for", "compromis ;)). Cependant, un inconvénient majeur est l'exigence de"),
    ("extensive knowledge about the structures specific to the current kernel", "connaissances approfondies sur les structures spécifiques à la version actuelle du"),
    ("version.", "noyau."),
    ("What we are essentially doing here is obtaining a pointer to the initial", "Ce que nous faisons essentiellement ici, c'est obtenir un pointeur vers"),
    ("network namespace from the ''init_nsproxy'' global variable [ref21].", "l'espace de noms réseau initial à partir de la variable globale ''init_nsproxy'' [ref21]."),
    ("Using this pointer, we can iterate through the link list [ref22] that holds", "En utilisant ce pointeur, nous pouvons itérer à travers la liste chaînée [ref22]"),
    ("references to the other network namespaces.", "qui détient des références aux autres espaces de noms réseau."),
    ("By performing this traversal, we gain the ability to see the existing network", "En effectuant cette traversal, nous gagnons la capacité de voir les espaces de"),
    ("namespaces in the system.", "noms réseau existants dans le système."),
    ("Logging and observing can provide invaluable insights into the current", "La journalisation et l'observation peuvent fournir des informations précieuses sur le"),
    ("behavior, however they do not offer a direct solution for switching into or", "comportement actuel, cependant elles ne fournissent pas de solution directe pour"),
    ("terminating the hidden namespace and disarm them.", "pAsser dans ou terminer l'espace de noms caché et le désarmer."),
    ("Moreover, we can make it even more complicated...", "De plus, nous pouvons le rendre encore plus compliqué..."),
    ("One of the biggest flaws with the namespace hiding so far is its dependency", "L'un des plus grands défauts de la dissimulation des espaces de noms jusqu'ici"),
    ("on the existence of the process. And I don't know if you know this, but", "est sa dépendance à l'existence du processus. Et je ne sais pas si vous le savez,"),
    ("userspace processes can be killed!", "mais les processus en espace utilisateur peuvent être tués !"),
    ("Making a process unkillable is indeed an interesting topic on its own.", "Rendre un processus intrépassable est en effet un sujet intéressant en soi."),
    ("We can make our process somewhat resilient to killing by utilizing signal", "Nous pouvons rendre notre processus relativement résistant aux tueries en utilisant"),
    ("filtering with tools like AppArmor or SElinux (see [ref23] for more details).", "le filtrage de signaux avec des outils comme AppArmor ou SELinux (voir [ref23] pour plus de détails)."),
    ("Additionally, we should not forget to forbid ptrace attach with the classic", "De plus, nous ne devrions pas oublier d'interdire l'attachement ptrace avec le classique"),
    ("''ptrace (PTRACE_TRACEME, 0, 0, 0)'' and ideally on a system-wide level with", "''ptrace (PTRACE_TRACEME, 0, 0, 0)'' et idéalement au niveau système avec"),
    ("Yama (see [ref24]).", "Yama (voir [ref24])."),
    ("If possible, let the kernel handle all the operations you need, as it offers", "Si possible, laissons le noyau gérer toutes les opérations dont nous avons besoin, car il offre"),
    ("various offloading capabilities (we will explore an example in the following", "divantes capacités de délégation (nous explorerons un exemple dans la section suivante)."),
    ("section).", ""),
    ("Moreover, kernel workers operate independently of userspace", "De plus, les travailleurs du noyau fonctionnent indépendamment de l'espace utilisateur"),
    ("processes, meaning that a functional userspace process is not necessary for", "ce qui signifie qu'un processus utilisateur fonctionnel n'est pas nécessaire"),
    ("the kernel to function properly. So, in the event that an uninterpretable D is", "pour le bon fonctionnement du noyau. Ainsi, dans l'éventualité où un 'D'"),
    ("inadvertently created within our process, the process itself may be lost", "incompréhensible serait créé dans notre processus, le processus lui-même peut être perdu"),
    ("indefinitely, but the kernel functionalities referenced by the process will", "indéfiniment, mais les fonctionnalités du noyau référencées par le processus"),
    ("remain available and functional.", "restent disponibles et fonctionnelles."),
    ("One of the notable advantages of network namespaces is that they provide a", "Avantage notable des espaces de noms réseau, ils fournissent une"),
    ("complete implementation of a network stack, allowing us to configure the", "implémentation complète d'une pile réseau, nous permettant de configurer le"),
    ("netfilter firewall according to our specific needs. This is particularly", "pare-feu netfilter selon nos besoins spécifiques. Ceci est particulièrement"),
    ("significant because netfilter rules are primarily processed in the kernelspace,", "significatif car les règles netfilter sont principalement traitées dans l'espace"),
    ("eliminating the requirement for a functional userspace process.", "noyau, éliminant la nécessité d'un processus utilisateur fonctionnel."),
    ("We have learned a very sophisticated and big brain technique that enables us to", "Nous avons appris une technique très sophistiquée et élaborée qui nous permet de"),
    ("hide references to any namespace using inotify.", "cacher des références à n'importe quel espace de noms en utilisant inotify."),
    ("One notable advantage of this approach is its integration within the main", "Un avantage notable de cette approche est son intégration dans la fonctionnalité"),
    ("functionality of the system,", "principale du système,"),
    ("eliminating the need for potentially restricted kernel modules, especially in", "éliminant le besoin de modules noyau potentiellement restreints, surtout"),
    ("situations where the kernel is signed.", "dans les situations où le noyau est signé."),
    ("However, we have barely touched upon the possibilities and applications of this", "Cependant, nous avons à peine effleuré les possibilités et applications de"),
    ("method. One simple and useful application is a netfilter tunnel, but the", "cette méthode. Une application simple et utile est un tunnel netfilter, mais le"),
    ("potential extends much further.", "potentiel s'étend beaucoup plus loin."),
    ("To sum up this article, I would like to cite the bestest hacking movie of all", "Pour résumer cet article, j'aimerais citer le meilleur film de hack de tous les temps"),
    ("time [ref25]:", "[ref25] :"),
    ("We have a fully functional network hidden within a socket. How awesome is", "Nous avons un réseau entièrement fonctionnel caché dans une socket. Incroyable, non ?"),
    ("that?!", "non ?!"),
    ("To be elite, you have to do a righteous hack, not this accidental shit.", "Pour être élite, faut faire un hack légitime, pas cette merde accidentelle."),
    ("Oh, wait...", "Oh, attends..."),
    ("Special \"yo!\" to richinseattle, elfmaster, xcellerator and tmp0ut crew!", "Un grand \"yo !\" à richinseattle, elfmaster, xcellerator et l'équipe tmp0ut !"),
    ("Thanks for reading, you absolute legends!", "Merci d'avoir lu, vous êtes des légendes absolues !"),
    ("When we inspect the running program, it appears innocent enough.", "Lorsque nous inspectons le programme en cours d'exécution, il semble suffisamment innocent."),
    ("The network namespace is the same as init's network namespace:", "L'espace de noms réseau est le même que celui de l'init :"),
    ("The only open file descriptors are stdin, stdout, stderr, and a", "Les seuls descripteurs de fichiers ouverts sont stdin, stdout, stderr, et une"),
    ("totally-non-suspicious TCP socket:", "socket TCP totalement non suspecte :"),
    ("The socket does not carry any special information, and the information we can", "La socket ne porte aucune information spéciale, et les informations que nous"),
    ("gather through regular means is limited:", "pouvons rassembler par des moyens ordinaires est limitée :"),
    ("From the ''flags'', we can determine that the socket is ''O_RDWR'' [ref8], this", "À partir des ''flags'', nous pouvons déterminer que la socket est ''O_RDWR'' [ref8],"),
    ("is not helpful at all.", "ce n'est pas du tout utile."),
    ("If we try to find the ''mnt_id'' (mount identifier), for example, using the", "Si nous essayons de trouver l''mnt_id' (identifiant de montage), par exemple, en"),
    ("command ''grep '^9 ' /proc/*/mountinfo'', we will not find a match.", "utilisant la commande ''grep '^9 ' /proc/*/mountinfo'', nous ne trouverons aucune correspondance."),
    ("Okay, on its own, this information can be helpful in some situations as we can", "D'accord, isolément, ces informations peuvent être utiles dans certaines situations,"),
    ("deduce that it might be a hidden kernel file system. But not here, as it is the", "car nous pouvons déduire qu'il s'agit peut-être d'un système de fichiers noyau"),
    ("''sockfs'' pseudo file system, which is used for all sockets.", "caché. Mais pas ici, car c'est le système de fichiers pseudo ''sockfs'', utilisé pour toutes les sockets."),
    ("If we call the ''getxattr(2)'' syscall (or use the ''getfattr'' command) on", "Si nous appelons l'appel système ''getxattr(2)'' (ou utilisons la commande ''getfattr'') sur"),
    ("the ''/proc/PID/fd/SOCK_FD'' [ref9], we can retrieve that it is a TCP socket,", "le ''/proc/PID/fd/SOCK_FD'' [ref9], nous pouvons récupérer qu'il s'agit d'une socket TCP,"),
    ("which provides us with slightly more information than before, but it is still", "ce qui nous fournit un peu plus d'informations qu'avant, mais il est toujours"),
    ("not particularly useful.", "pas particulièrement utile."),
    ("Furthermore, if we attempt to search for the socket inode across all available", "De plus, si nous essayons de rechercher l'inode de la socket dans toutes les"),
    ("network information in all visible network namespaces, for example, by running", "informations réseau disponibles dans tous les espaces de noms réseau visibles,"),
    ("the command ''grep -r 1149645 /proc/[0-9]*/net'', we will not find any matches.", "par exemple en exécutant la commande ''grep -r 1149645 /proc/[0-9]*/net'', nous ne trouverons aucune correspondance."),
    ("Of course, this should raise a red flag, as on a normally behaving system, we", "Bien sûr, cela devrait lever un drapeau rouge, car sur un système se comportant normalement,"),
    ("should be able to observe all network stacks.", "nous devrions pouvoir observer toutes les piles réseau."),
    ("Although the socket cannot be found in the ''/proc'' directory, it can still be", "Bien que la socket ne puisse pas être trouvée dans le répertoire ''/proc'', elle peut toujours"),
    ("detected using ''tcpdump'' when there is active traffic.", "être détectée en utilisant ''tcpdump'' lorsqu'il y a du trafic actif."),
    ("For example, by running ''tcpdump'' directly on the backend interface for the", "Par exemple, en exécutant ''tcpdump'' directement sur l'interface backend pour le"),
    ("macvlan (e.g., ''eth0''), we can observe packets that originate from or are", "macvlan (par ex., ''eth0''), nous pouvons observer des paquets qui proviennent de ou"),
    ("directed towards our network namespace.", "sont dirigés vers notre espace de noms réseau."),
    ("Unfortunately, we cannot pinpoint the specific process, especially if the process", "Malheureusement, nous ne pouvons pas identifier le processus spécifique, surtout si le"),
    ("itself is not generating any traffic!", "processus lui-même ne génère aucun trafic !"),
    ("We will create a scenario demonstrating such behavior later on.", "Nous créerons un scénario démontrant ce comportement plus tard."),
    ("There is one hint that can reveal the ''nsfs'': the device number", "Il y a un indice qui peut révéler l''nsfs'': le numéro de périphérique"),
    ("''sdev''. When we encounter something like ''sdev:4'', it indicates that the", "'sdev''. Lorsque nous rencontrons quelque chose comme ''sdev:4'', cela indique que"),
    ("device number is ''0:4'' (major:minor) [ref12], and if we cannot find it in the", "le numéro de périphérique est ''0:4'' (majeur:mineur) [ref12], et si nous ne le trouvons pas dans le"),
    ("''/proc/PID/mountinfo'' file [ref13], it stinks with an in-kernel pseudo file system.", "fichier ''/proc/PID/mountinfo'' [ref13], c'est un système de fichiers pseudo noyau."),
    ("We can easily verify this by bind mounting some ''nsfs'' namespace", "Nous pouvons facilement vérifier cela en bind-montant un lien symbolique d'espace"),
    ("symlink:", "de noms ''nsfs' :"),
    ("A similar approach can be applied to a socket, although not through", "Une approch similaire peut être appliquée à une socket, bien pas via"),
    ("This is great news for us, as we can utilize the ''inotify_add_watch(2)''", "C'est une excellente nouvelle pour nous, car nous pouvons utiliser ''inotify_add_watch(2)''"),
    ("syscall as an obfuscator. We will provide the ''/proc/PID/fd/FD'' file path to", "comme obfuscateur. Nous fournirons le chemin du fichier ''/proc/PID/fd/FD'' à"),
    ("it, which will create a reference to the ''FD'' file descriptor, and when we", "cela, ce qui créera une référence au descripteur de fichier ''FD', et quand nous"),
    ("subsequently close the original file descriptor ''FD'', the association with", "fermerons le descripteur de fichier original ''FD', l'association avec"),
    ("the file path will be lost, but the file descriptor will still retain its", "le chemin du fichier sera perdue, mais le descripteur de fichier conservera encore"),
    ("reference.", "la référence."),
    ("That sounds arousing, but can we actually use it?", "Cela sonne excitant, mais pouvons-nous l'utiliser ?"),
    ("Let's refer to the", "Référons-nous à la"),
    ("While man pages are indeed a great source of information, they can sometimes be", "Les pages de manuel sont effectivement une excellente source d'informations, mais elles"),
    ("misleading. \"Not being monitorable\" does not imply failure.", "peuvent parfois être trompeuses. \"Ne pas être surveillable\" n'implique pas l'échec."),
    ("The following experiment demonstrates that an inotify watch can create a reference", "L'expérience suivante démontre qu'une surveillance inotify peut créer une référence"),
    ("to a ''nsfs'' pseudo file (the same applies to ''sockfs'') and that it is capable of", "à un fichier pseudo ''nsfs'' (il en va de même pour ''sockfs'') et qu'il est capable de"),
    ("holding a (network) namespace:", "tenir un espace de noms (réseau) :"),
    ("Although the socket cannot be found in the ''/proc'' directory, it can still be", "Bien que la socket ne puisse pas être trouvée dans le répertoire ''/proc'', elle peut toujours"),
    ("detected using ''tcpdump'' when there is active traffic. For example, by running", "être détectée en utilisant ''tcpdump'' lorsqu'il y a du trafic actif. Par exemple, en exécutant"),
    ("''tcpdump'' directly on the backend interface for the macvlan (e.g., ''eth0''),", "''tcpdump'' directement sur l'interface backend pour le macvlan (par ex., ''eth0''),"),
    ("we can observe packets that originate from or are directed towards our network", "nous pouvons observer des paquets qui proviennent de ou sont dirigés vers notre espace"),
    ("namespace.", "de noms réseau."),
    ("Inotify seems like a superior option due to the difficulty of discovering the", "Inotify semble être une option supérieure en raison de la difficulté de découverte"),
    ("original file descriptor.", "du descripteur de fichier original."),
    ("a socket has a valuable property: we can retrieve its network namespace.", "une socket a une propriété précieuse : nous pouvons récupérer son espace de noms réseau."),
    ("Imagine a scenario where we create a backdoor program that hides a malicious network", "Imaginez un scénario où nous créons un programme porte-drapeau qui cache un espace de noms réseau"),
    ("namespace within a socket most of the time. When needed, such as for network or", "malicieux au sein d'une socket la plupart du temps. Quand c'est nécessaire,"),
    ("firewall reconfiguration, the program can retrieve the network namespace using a simple", "comme pour la reconfiguration réseau ou le pare-feu, le programme peut récupérer l'espace de"),
    ("''ioctl()'' call:", "noms réseau en utilisant un simple appel ''ioctl()'':"),
    ("On the other hand, this capability can also be used to our disadvantage.", "D'un autre côté, cette capacité peut également être utilisée à notre désavantage."),
    ("When some aggressor connects to our innocent backdoor process, steals the socket", "Lorsque qu'un agresseur se connecte à notre processus porte-drapeau innocent, vole la socket"),
    ("file descriptor, and uses the ''ioctl(2)'' call described above, they can", "descripteur de fichier, et utilise l''ioctl(2)'' décrit ci-dessus, ils peuvent"),
    ("potentially perform unholy forensics on it.", "effectuer une forensic profane sur celui-ci."),
    ("At first glance, there is a cool way to hold a namespace. Namely, files from the", "À première vue, il existe une façon sympa de tenir un espace de noms. En effet,"),
    ("''nsfs'' pseudo file system can be bind-mounted. (This technique is", "les fichiers du système de fichiers pseudo ''nsfs'' peuvent être bind-mountés. (Cette technique est"),
    ("utilized by ''iproute2'' for the ''ip netns add'' command [ref15]).", "utilisée par ''iproute2'' pour la commande ''ip netns add'' [ref15])."),
    ("This approach is kinda elegant, but unfortunately, it is quite easy to find", "Cette approche est assez élégante, mais malheureusement, il est assez facile de la trouver"),
    ("because it has a distinct file system type called ''nsfs'':", "parce qu'elle a un type de système de fichiers distinct appelé ''nsfs'' :"),
    ("If we were looking to identify such a bind-mount, we could simply search", "Si nous voulions identifier un tel bind-mount, nous pourrions simplement chercher"),
    ("through every process and its corresponding ''/proc/self/mountinfo'' file for", "dans chaque processus et son fichier ''/proc/self/mountinfo'' correspondant pour"),
    ("the presence of ''nsfs'':", "la présence de ''nsfs'' :"),
    ("Dealing with bind-mounted ''nsfs'' is relatively straightforward process.", "Gérer un ''nsfs'' bind-mounté est un processus relativement simple."),
    ("We first switch to the mount namespace and then, from there, switch to the", "Nous passons d'abord à l'espace de noms de montage et ensuite, à partir de là,"),
    ("bind-mounted network namespace, giving us full access to the network.", "à l'espace de noms réseau bind-mounté, nous donnant un accès complet au réseau."),
    ("While we are at it, let's again look at some detection methodologies.", "Pendant que nous y sommes, regardons à nouveau certaines méthodologies de détection."),
    ("These rules can be chained across multiple hosts, with the last host serving as", "Ces règles peuvent être chaînées à travers plusieurs hôtes, le dernier hôte servant de"),
    ("a SOCKS proxy (see [ref3]).", "proxy SOCKS (voir [ref3])."),
    ("It would be unstable as heck, but then we will be behind 7 proxies and that", "Ça serait instable, mais on sera derrière 7 proxies et ça compte pour quelque chose !"),
    ("counts for something!", ""),
    ("The demo doesn't have room to do much.", "Le demo n'a pas beaucoup d'espace pour faire des choses."),
    ("When we apply these rules in our ''socket_container'', it can be utilized as a", "Lorsque nous appliquons ces règles dans notre ''socket_container'', il peut être utilisé comme"),
    ("jump host. For instance, when we go to ''172.19.1.222:1337'', our traffic will be", "host de saut. Par exemple, lorsque nous allons sur ''172.19.1.222:1337'', notre trafic sera"),
    ("transparently redirected to ''1.1.1.1:443''.", "redirigé de manière transparent vers ''1.1.1.1:443''."),
    ("This can be easily tested using the ''curl'' command:", "Cela peut être facilement testé en utilisant la commande ''curl'' :"),
    ("We have a fully functional network hidden within a socket. How awesome is", "Nous avons un réseau entièrement fonctionnel caché dans une socket. Incroyable, non ?"),
    ("that?!", "non ?!"),
    ("The hacker's oath", "Le serment du hacker"),
    ("PoC || GTFO", "PoC || GTFO"),
    ("Opportunity makes the hacker.", "L'opportunité crée le hacker."),
    ("sockets", "sockets"),
    ("containers", "conteneurs"),
    ("docker", "docker"),
    ("LXC", "LXC"),
    ("TCP", "TCP"),
    ("SOCKS", "SOCKS"),
    ("iptables", "iptables"),
    ("VPN", "VPN"),
    ("macvlan", "macvlan"),
    ("veth", "veth"),
    ("nsfs", "nsfs"),
    ("sockfs", "sockfs"),
    ("tcpdump", "tcpdump"),
    ("eBPF", "eBPF"),
    ("kprobes", "kprobes"),
    ("ftrace", "ftrace"),
    ("inotify", "inotify"),
    ("kernel", "noyau"),
    ("userspace", "espace utilisateur"),
    ("kernelspace", "espace noyau"),
    ("namespace", "espace de noms"),
    ("syscall", "appel système"),
    ("filesystem", "système de fichiers"),
    ("socket", "socket"),
])

print("Batch done: 06.html")
